### ISSUE TITLE
error in vb.net

### ISSUE THREAD

**Issue by mzelecom** [jchristn/WatsonTcp#1]
i used watsontcp in vb.net but when run this error occurd.i can i fix it.
mycode:
Dim server As New WatsonTcpServer("192.168.1.5", 2992, AddressOf ClientConnected, AddressOf ClientDisconnected, AddressOf MessageReceived, False)

error:
An unhandled exception of type 'System.TypeLoadException' occurred in System.Windows.Forms.dll

Additional information: Could not load type 'WatsonTcp.WatsonTcpServer' from assembly 'WatsonTcp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

**Comment by jchristn** [comment]
Hi @mzelecom sorry I just saw this, I'm not sure why I didn't get a notification on it.  Is the DLL in the output directory of your app?

**Comment by jchristn** [comment]
Hi @mzelecom  going to assume you got this resolved or no longer want me to look at this, closing it out.  Again sorry I didn't get a notification on this issue to respond sooner.  Please re-open if you'd like to revisit it.  Thanks!
