### ISSUE TITLE
Receiving and Sending Show Progress   

### ISSUE THREAD

**Issue by Mehsoor** [jchristn/WatsonTcp#100]
Please Help.
I want to Show Receiving and Sending Progress in Progress Bar.
Thank you.

**Comment by jchristn** [comment]
Hi @Mehsoor which ```Send``` methods are you using specifically - string, byte[], or stream?

**Comment by Antwns** [comment]
Hi @Mehsoor , you could try to use the .Send method to send the length of the byte array you're willing to send first, then the byte array, then on the client side add an int variable that increments for each byte received which in turn calls a UI update method (At least, that's how I'd have done it)

**Comment by Mehsoor** [comment]
> Hi @Mehsoor which `Send` methods are you using specifically - string, byte[], or stream?

I'm using byte[] Method for 'Send' data.

**Comment by jchristn** [comment]
Hi @Mehsoor thank you.  We could add a new series of ```Send``` APIs that take an ```Action``` as a parameter that gets invoked every time input data is read and then written to the underlying network.  That invocation could relay the number of bytes sent and the total number of bytes.  For receiving data, if you are consuming data from the network using ```StreamReceived``` you are already given the number of bytes to read and you control reads against the stream.  It wouldn't make sense to report progress on ```MessageReceived```.

Would the enhancement above be sufficient?

**Comment by Mehsoor** [comment]
> Hi @Mehsoor thank you. We could add a new series of `Send` APIs that take an `Action` as a parameter that gets invoked every time input data is read and then written to the underlying network. That invocation could relay the number of bytes sent and the total number of bytes. For receiving data, if you are consuming data from the network using `StreamReceived` you are already given the number of bytes to read and you control reads against the stream. It wouldn't make sense to report progress on `MessageReceived`.
> 
> Would the enhancement above be sufficient?

thank you brother god bless you...
