### ISSUE TITLE
Client remains frozen while receiving long byte[]

### ISSUE THREAD

**Issue by Antwns** [jchristn/WatsonTcp#101]
Hello, I'm sending a .wav file via WatsonTCP through the network as byte[] and then making it play in a stream, however the client remains locked because it's still receiving data from the server, is there a way to make it asyncronous? Should I use the .SendAsync method instead? Thanks in advance! 😄

**Comment by Antwns** [comment]
Turns out it's because I was writing to the console (for debugging purposes) and it was keeping the UI thread busy, No need to look into it anymore! 👍

**Comment by jchristn** [comment]
Glad you got it working @Antwns - would definitely recommend using the stream variants for send if you can, too!
