### ISSUE TITLE
My nightmare returns...

### ISSUE THREAD

**Issue by Antwns** [jchristn/WatsonTcp#102]
Hello. It would appear that I'm doing something wrong (Once more)
I believe that the client gets disposed at some point after receiving a long byte[] from remote connections... I have checked with the client.test and server.test those work perfectly fine. I'm just doing something wrong in my own implementation of the package... How can I move the client and the server networking to a separate class and instantiate it ?(You talked to me about this before) Do I need to use the { get; set; } ? This issue has me really confused, I'm sure that my router network works fine, I'm just doing something wrong in the code... It used to work fine for small byte[] but when I try to send a .wav file for example it just disposes itself or something like that... I get the following error:
`Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.`

Edit: Here are the full errors in both exception and .json formats.
`[ERROR] System.IO.IOException: Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.Send(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at WatsonTcp.WatsonTcpServer.SendDataStream(ClientMetadata client, Int64 contentLength, Stream stream)
   at WatsonTcp.WatsonTcpServer.SendInternal(ClientMetadata client, WatsonMessage msg, Int64 contentLength, Stream stream)`

`  "ClassName": "System.IO.IOException",
  "Message": "Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.",
  "Data": null,
  "InnerException": {
    "NativeErrorCode": 10054,
    "ClassName": "System.Net.Sockets.SocketException",
    "Message": "An existing connection was forcibly closed by the remote host",
    "Data": null,
    "InnerException": null,
    "HelpURL": null,
    "StackTraceString": "   at System.Net.Sockets.Socket.Send(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)\r\n   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)",
    "RemoteStackTraceString": null,
    "RemoteStackIndex": 0,
    "ExceptionMethod": "8\nSend\nSystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\nSystem.Net.Sockets.Socket\nInt32 Send(Byte[], Int32, Int32, System.Net.Sockets.SocketFlags)",
    "HResult": -2147467259,
    "Source": "System",
    "WatsonBuckets": null
  },
  "HelpURL": null,
  "StackTraceString": "   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)\r\n   at WatsonTcp.WatsonTcpServer.SendDataStream(ClientMetadata client, Int64 contentLength, Stream stream)\r\n   at WatsonTcp.WatsonTcpServer.SendInternal(ClientMetadata client, WatsonMessage msg, Int64 contentLength, Stream stream)",
  "RemoteStackTraceString": null,
  "RemoteStackIndex": 0,
  "ExceptionMethod": "8\nWrite\nSystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\nSystem.Net.Sockets.NetworkStream\nVoid Write(Byte[], Int32, Int32)",
  "HResult": -2146232800,
  "Source": "System",
  "WatsonBuckets": null`

Edit2: These errors specifically happen when sending large byte[] with the Server.Send(IpPort, byte[]) method

Edit3: I looked a bit more into it, I believe that this could be caused by "IpPort" mismatches, like, the server sends data to a port the client doesn't expect to receive them from? I noticed that more ports than the one initially set up as the actual port to use are being used to send/receive data

**Comment by jchristn** [comment]
Hi @Antwns good to hear from you and sorry the issue is still plaguing you.  I would try defining the WatsonTcpServer instance in your App.xaml.cs, and then instantiate it there.  If the class is instantiated from within one of your views, it's likely to get disposed (garbage collected) if the view changes.  Weird things happen in views/forms that way.  You should be able to access things defined in your App.xaml.cs, i.e. ```WatsonTcpServer Server = new...``` and then accessing it using ```App.Server(...```.

Do you still have the code that I sent your way?  I believe I followed this model.  Cheers, Joel

**Comment by jchristn** [comment]
I believe this is the patch I sent: https://github.com/jchristn/WatsonTcp/files/5424294/patch.zip

In your case, WatsonTcpServer would be instantiated in your AntVaultServer App.xaml.cs:
```
    public partial class App : Application
    {
        public static MainServerWorker Server = null;
    }
```

And then instantiated in your MainServerWindow.xaml.cs:
```

        public MainWindow()
        {
            InitializeComponent();

            App.Server = new MainServerWorker();
        }
```

And then used MainServerWorker.cs class:
```
            _AntVaultServer = new WatsonTcpServer("192.168.1.39", _Port);
```

Have you had a chance to give that a try?  Cheers, Joel

**Comment by Antwns** [comment]
I did but the problem is that I switched to a console app instead for the server. I have implemented the above changes to the client, should I do the same for the server? I noticed that the client connects for a bit, asks the basic information(strings) from the server and then somehow it just gets disconnected before it can send a login request(strings) to the server, how would I implement the above changes on a console app? Thanks for all the help so far, I really appreciate it 😀

**Comment by Antwns** [comment]
If I understand correctly, I need to move everything about WatsonTCP to a SINGLE class, event the events_messagereceived and then simply instantiate it in parts of my code where I need to use it?

**Comment by Antwns** [comment]
UPDATE: I have moved everything server and client related to their own classes and instantiated them later on, however things keep getting disposed, in the seperate classes I created nothing has the static modifier... I don't understand...

**Comment by jchristn** [comment]
Hi @Antwns if you invite me to your repo, I'll be happy to clone, take a look, and contribute recommendations.

**Comment by Antwns** [comment]
I did it! Thank you so much!

**Comment by jchristn** [comment]
Haven't forgotten about you @Antwns - the week kinda got away from me.  Still on my list.

**Comment by Antwns** [comment]
I'm sorry but the newest version completely bricked my app... I moved on to a different package and cross-network communication works too. I'm sorry @jchristn , I waited ~4 days I understand you had alot to work with and that's okay

**Comment by jchristn** [comment]
Thank you Antwns - glad to hear you have a working solution!
