### ISSUE TITLE
Serialization/Deserialization of Metadata

### ISSUE THREAD

**Issue by code-pug** [jchristn/WatsonTcp#103]
Hi,

I'm not sure this is an issue, but I'm struggling with deserialization metadata send using the method: 

`client.SendAndWait(metadata, totalMilliseconds, "my string");`

Currently, I'm adding a class to the metadata dictionary. It's a simple one, which should be serializable/de-serializable using Json.NET. The class in question has a few string properties, with a constructor sufficient for de-serialization again.

It looks similar to:

```
public class MyClass
{
        public MyClass(string property)
        {
            MyProperty = property ?? throw new ArgumentNullException(nameof(subscriptionFile));
        }

        public string Property { get; }
}
```

My understanding was that I should be able to add this as a value to the metadata dictionary on the client side, and then on the server side, it should be deserialized into my type again. (Going over the wire in JSON.)

What I see is that the metadata dictionary on the server side contains a JObject type which represents the original class as JSON, not an instance of the original concrete class.

From the JObject, I can call 

`o.ToObject<MyClass>()`

Which turns it into my concrete object again.

Is there a reason I have to manually call ToObject on my metadata to deserialize it?

It's not a particular pain, I just don't want to be abusing how this otherwise brilliant framework should be used. :)

Alternatively, would you recommend against using classes in the metadata dictionary?

Ta,

**Comment by jchristn** [comment]
Hi @code-pug interesting - you shouldn't have to further deserialize when you access a known dictionary key that contains an instance of a class as a value.  Assuming your client and server have the same assemblies with the same classes, it should deserialize into an instance.  

I assume you're wanting to do something like the following?

```
using System;
using System.Collections.Generic;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using WatsonTcp;

namespace Test.Metadata
{
    class Program
    {
        static void Main(string[] args)
        {
            using (WatsonTcpServer server = new WatsonTcpServer("127.0.0.1", 8000))
            {
                server.Events.MessageReceived += ServerMessageReceived;
                server.Start();
                Task.Delay(1000).Wait();
                using (WatsonTcpClient client = new WatsonTcpClient("127.0.0.1", 8000))
                {
                    client.Events.MessageReceived += ClientMessageReceived;
                    client.Start();

                    for (int i = 0; i < 10; i++)
                    {
                        Person p = new Person("hello", "world", i);
                        Dictionary<object, object> md = new Dictionary<object, object>();
                        md.Add("person", p);
                        client.Send(md, ("Message " + i));
                        Task.Delay(1000).Wait();
                    }
                }
            }
        }

        #region Events

        private static void ServerMessageReceived(object sender, MessageReceivedFromClientEventArgs args)
        {
            Console.WriteLine(Encoding.UTF8.GetString(args.Data) + ": " + SerializeJson(args.Metadata, false));
        }

        private static void ClientMessageReceived(object sender, MessageReceivedFromServerEventArgs args)
        {

        }

        #endregion

        #region Serialization

        private static readonly JsonSerializerSettings HardenedSerializerSettings = new JsonSerializerSettings
        {
            TypeNameHandling = TypeNameHandling.None // Prevents CS2328 style attacks if a project is allowing automatic type resolution elsewhere.
        };

        private static readonly JsonSerializerSettings SerializerDefaults = new JsonSerializerSettings
        {
            NullValueHandling = NullValueHandling.Ignore,
            DateTimeZoneHandling = DateTimeZoneHandling.Local,
        };

        internal static T DeserializeJson<T>(string json)
        {
            if (String.IsNullOrEmpty(json)) throw new ArgumentNullException(nameof(json));
            return JsonConvert.DeserializeObject<T>(json, HardenedSerializerSettings);
        }

        internal static string SerializeJson(object obj, bool pretty)
        {
            if (obj == null) return null;
            string json;

            if (pretty)
            {
                json = JsonConvert.SerializeObject(
                    obj,
                    Newtonsoft.Json.Formatting.Indented,
                    SerializerDefaults
                );
            }
            else
            {
                json = JsonConvert.SerializeObject(
                    obj,
                    SerializerDefaults
                );
            }

            return json;
        }

        #endregion
    }

    public class Person
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int Number { get; set; }

        public Person()
        {

        }

        public Person(string first, string last, int num)
        {
            FirstName = first;
            LastName = last;
            Number = num;
        }
    }
}
```
![image](https://user-images.githubusercontent.com/1421081/98554305-6f4fd700-2255-11eb-96b7-d0f32524af4f.png)

**Comment by code-pug** [comment]
Hey,

Thanks for the quick reply. 

Yes, that very much what I'm doing. My class is shared between the client and server using a common library. The only difference I note is that my properties are get-only, but I have a constructor marked with the JsonConstructor attribute, and it deserializes manually, so I guess that's not the problem.

I'll do some more debugging into it soon, and update the thread as I go.

Thanks,

**Comment by jchristn** [comment]
I think I see the issue you may be running into.  

You would want something like
```
Person p = DeserializeJson<Person>(args.Metadata["person"]);
Console.WriteLine(p.FirstName + " " + p.LastName);
```
Or similar in your code, if I'm not mistaken.

My solution above didn't test out the deserialization path, I just reserialized on the receiving end.  Let me give that a whirl.

**Comment by jchristn** [comment]
Hi @code-pug I think I just ran into the same thing you were seeing.
```

        private static void ServerMessageReceived(object sender, MessageReceivedFromClientEventArgs args)
        { 
            try
            {
                object o = args.Metadata["person"];
                Console.WriteLine(SerializeJson(o, true));
                Person p = (Person)o; 
                Console.WriteLine(p.FirstName + " " + p.LastName + ": " + p.Number);
            }
            catch (Exception e)
            {
                Console.WriteLine(e.ToString());
            }
        }
```
produced:
```
{
  "FirstName": "hello",
  "LastName": "world",
  "Number": 0
}
System.InvalidCastException: Unable to cast object of type 'Newtonsoft.Json.Linq.JObject' to type 'Test.Metadata.Person'.
   at Test.Metadata.Program.ServerMessageReceived(Object sender, MessageReceivedFromClientEventArgs args) in C:\Code\Watson\WatsonTcp-4.5\Test.Metadata\Program.cs:line 45
```
This is likely due to the metadata dictionary being ```<object, object>```.  Thanks for pointing this out.

**Comment by jchristn** [comment]
Hi @code-pug I believe the reason this is happening and the reason you have to do a ```JObject.ToObject<[type]>...``` is because the metadata dictionary is defined as ```<object, object>```.  I'm glad you pointed this out, because I wasn't aware this would happen.  

I'll leave this open in case anyone has a suggestion on how the library could be amended to allow the object to be deserialized automatically.

**Comment by jchristn** [comment]
Also I'll be sure to update the README on this one.  Thanks for catching it.
