### ISSUE TITLE
In this version, the server connection and disconnect events seem to fail?

### ISSUE THREAD

**Issue by wf-soft** [jchristn/WatsonTcp#104]
@jchristn Hi! jchristn.
![image](https://user-images.githubusercontent.com/62228539/99068637-d4098980-25e7-11eb-93d5-7f2b200dbd39.png)

**Comment by jchristn** [comment]
Hi @wf-soft - are the events not firing for you?  Or are you experiencing some other error?  Cheers, Joel

**Comment by wf-soft** [comment]
@jchristn 
Yes, server events cannot be triggered. I'm using. Net 5

**Comment by jchristn** [comment]
Awesome catch, I must have accidentally removed them on a recent update.  Fixing now.

**Comment by wf-soft** [comment]
@jchristn Great, my system can't work now. Thank you

**Comment by jchristn** [comment]
Hi @wf-soft this should fix the issue.  Please re-open if it doesn't.  Thanks for finding and reporting!

NuGet: https://www.nuget.org/packages/WatsonTcp/4.5.0.2
Commit: https://github.com/jchristn/WatsonTcp/commit/c35b561da58c2642f967b66530feab3d9ab79bbb

**Comment by wf-soft** [comment]
@jchristn Vray Good!
