### ISSUE TITLE
_Events.IsUsingMessages  and   _Events.IsUsingStreams 

### ISSUE THREAD

**Issue by kzonesoft** [jchristn/WatsonTcp#105]
_Events.IsUsingMessages  and   _Events.IsUsingStreams  always true.

I only put event Events.StreamReceived

![Screenshot_2](https://user-images.githubusercontent.com/73275292/99894666-a3e17b00-2cb8-11eb-89a3-5b07adbc0ae6.png)
![Screenshot_1](https://user-images.githubusercontent.com/73275292/99894668-a6dc6b80-2cb8-11eb-9428-85ad00a3f7fa.png)

**Comment by jchristn** [comment]
Thanks - probably because by default I'm setting the event handlers to ```delegate { };``` - let me test to make sure leaving them empty doesn't create an issue, and I'll push a patch.  Thanks for letting me know

**Comment by jchristn** [comment]
Hi @kzonesoft thanks for letting me know - this should fix it.  Please re-open if it doesn't!  And thanks for making the library better!  Cheers, Joel

NuGet: https://www.nuget.org/packages/WatsonTcp/4.6.0.1
Commit: https://github.com/jchristn/WatsonTcp/commit/5854847742b9d85603c7e22b35ee3ff841f94202

**Comment by kzonesoft** [comment]
OK. it's working bro :+1:
