### ISSUE TITLE
WatsonTcpClientEvents - AuthenticationSucceeded is never fired

### ISSUE THREAD

**Issue by crotella** [jchristn/WatsonTcp#106]
Hi 
I noticed that the AuthenticationSucceeded event is never fired on the client side,  I believe it's due to having the HandleAuthenticationSucceeded method invoke the ServerConnected event, instead of the AthenticationSucceed event.

 internal void HandleAuthenticationSucceeded(object sender, EventArgs args)
        {
            WrappedEventHandler(() => ServerConnected?.Invoke(sender, args), "ServerConnected", sender); 
        }

**Comment by jchristn** [comment]
Ah, thanks @crotella looking at this now!

**Comment by jchristn** [comment]
Great catch @crotella - fixed in 4.6.0.2, please re-open if it doesn't!

NuGet: https://www.nuget.org/packages/WatsonTcp/4.6.0.2
Commit: https://github.com/jchristn/WatsonTcp/commit/4457ae03df47ff4861d540241e4aa217c78b6e9a

**Comment by crotella** [comment]
Np

Thanks for the great product

Been using simpletcp for years now

Giving WatsonTcp a try now.
