### ISSUE TITLE
Less performance in .net framework

### ISSUE THREAD

**Issue by shanto462** [jchristn/WatsonTcp#109]
Is there any problem or why I am getting huge CPU usage and less throughput in .Net framework?
In .Net Core and .Net 5 it's working great.

Most of the cpu usage in this call
 

>  bool buildSuccess = await msg.BuildFromStream(token).ConfigureAwait(false);

Thanks in advance.

**Comment by jchristn** [comment]
Hi @shanto462 which version of the library and which version of .NET Framework are you using?  Do you see the CPU utilization go high when it's idle, or only when receiving a message?  

Also do you see this same behavior in the ```Test.Client``` and ```Test.Server``` projects?

Cheers, Joel

**Comment by shanto462** [comment]
Thank you @jchristn for responding.
You guys are maintaining an awesome project.

I tried with .Net Framework 4.72 and 4.8.
I am using the latest version of the library.

CPU utilization is going high when receiving a message.

I faced really bad performance in the Test.Throughput project comparing with .net core and .net 5.

I was testing by sending 10000 messages from a client. 
It took 3-4 seconds to transfer all the messages. But client was using up to 60% of the cpu. And server is taking few minutes to receive all the message and cpu usage is same as client. My cpu is core i 7 9900k. so I guess 60% of the cpu is huge deal.

But in .net core and .net 5, cpu usage is nothing to be worried and time is as expected.

**Comment by jchristn** [comment]
Hi @shanto462 thanks for the kind words.  What message size were you using in the Test.Throughput project?  I just tested with 4 clients, 4096 messages, 65536 bytes/message on .NET Framework 4.6.1
```
Results:
  Number of clients             : 4
  Number of messages per client : 4096

  Expected message count        : 16384
  Messages sent successfully    : 16384
  Messages failed               : 0

  Expected bytes                : 1073741824
  Bytes sent successfully       : 1073741824
  Bytes received successfully   : 1073741824

  Elapsed time (ms)             : 0ms
  Elapsed time (seconds)        : 1s

  Messages per second           : 16384 msg/s
  Bytes per second              : 1073741824B/s
  Kilobytes per second          : 1048576kB/s
  Megabytes per second          : 1024MB/s
```
CPU utilization spiked as expected, but dropped quickly.  

I'll also re-target to both 4.7.2 and 4.8 on my side to see if I can reproduce.

**Comment by jchristn** [comment]
Results from 4.7.2:
```
Results:
  Number of clients             : 4
  Number of messages per client : 4096

  Expected message count        : 16384
  Messages sent successfully    : 16384
  Messages failed               : 0

  Expected bytes                : 1073741824
  Bytes sent successfully       : 1073741824
  Bytes received successfully   : 1073741824

  Elapsed time (ms)             : 0ms
  Elapsed time (seconds)        : 1s

  Messages per second           : 16384 msg/s
  Bytes per second              : 1073741824B/s
  Kilobytes per second          : 1048576kB/s
  Megabytes per second          : 1024MB/s
```
Results from 4.8:
```
Results:
  Number of clients             : 4
  Number of messages per client : 4096

  Expected message count        : 16384
  Messages sent successfully    : 16384
  Messages failed               : 0

  Expected bytes                : 1073741824
  Bytes sent successfully       : 1073741824
  Bytes received successfully   : 1073741824

  Elapsed time (ms)             : 0ms
  Elapsed time (seconds)        : 1s

  Messages per second           : 16384 msg/s
  Bytes per second              : 1073741824B/s
  Kilobytes per second          : 1048576kB/s
  Megabytes per second          : 1024MB/s
```

What message size were you using from the client?  Were you using single client or multiple clients?  Which OS and version were you using?  My tests were done on Win10 Pro on my laptop; it's 16GB with an i7-8550U, which is definitely less powerful than yours, so something weird must be going on.

**Comment by shanto462** [comment]
Now I was using the async variant of the send function.
That function was causing problem for me.
Now it is ok, but there is a lot difference between .net framework and .net core/ .net 5 performance

**Comment by jchristn** [comment]
Ok - let me try amending Test.Throughput to include an async variant.  Will report back and see how they compare.

**Comment by jchristn** [comment]
Just pushed an update with async variants for Test.Throughput, here are the results.  All tests were 4 clients sending 4096 messages of size 65536 using async send.

net461
```
Results:
  Number of clients             : 4
  Number of messages per client : 4096

  Expected message count        : 16384
  Messages sent successfully    : 16384
  Messages failed               : 0

  Expected bytes                : 1073741824
  Bytes sent successfully       : 1073741824
  Bytes received successfully   : 1073741824

  Elapsed time (ms)             : 0ms
  Elapsed time (seconds)        : 1s

  Messages per second           : 16384 msg/s
  Bytes per second              : 1073741824B/s
  Kilobytes per second          : 1048576kB/s
  Megabytes per second          : 1024MB/s
```
net472
```
Results:
  Number of clients             : 4
  Number of messages per client : 4096

  Expected message count        : 16384
  Messages sent successfully    : 16384
  Messages failed               : 0

  Expected bytes                : 1073741824
  Bytes sent successfully       : 1073741824
  Bytes received successfully   : 1073741824

  Elapsed time (ms)             : 0ms
  Elapsed time (seconds)        : 1s

  Messages per second           : 16384 msg/s
  Bytes per second              : 1073741824B/s
  Kilobytes per second          : 1048576kB/s
  Megabytes per second          : 1024MB/s
```
net48
```
Results:
  Number of clients             : 4
  Number of messages per client : 4096

  Expected message count        : 16384
  Messages sent successfully    : 16384
  Messages failed               : 0

  Expected bytes                : 1073741824
  Bytes sent successfully       : 1073741824
  Bytes received successfully   : 1073741824

  Elapsed time (ms)             : 0ms
  Elapsed time (seconds)        : 1s

  Messages per second           : 16384 msg/s
  Bytes per second              : 1073741824B/s
  Kilobytes per second          : 1048576kB/s
  Megabytes per second          : 1024MB/s
```
I'm having a hard time reproducing what you are seeing - could you reduce the code down to something you can share that highlights the behavior?  Definitely want to help get to the bottom of this...  Thanks, Joel

**Comment by shanto462** [comment]
I don't know what is going on. I am using the Test.Throughput  Project.
I was thinking is there any problem with stream.readasync() method in .net framework.
This method is the critical path.

**Comment by shanto462** [comment]
This is the result I am getting
using 1 client, 65536 message size and 4096 messages :(

> Messages sent after 31 seconds
> Waiting on 108 to complete processing (1 second pause)
> 
> Results:
>   Messages sent successfully     : 4096
>   Messages failed                : 0
>   Bytes sent successfully        : 268435456
>   Bytes received successfully    : 268435456
>   Elapsed time sending (ms)      : 31911ms
>   Elapsed time sending (seconds) : 31s
>   Send bytes per second          : 8659208.26B/s
>   Send kilobytes per second      : 8456.26kB/s
>   Send megabytes per second      : 8.26MB/s
>

**Comment by shanto462** [comment]
After starting without any debugger

Too much difference but still lacking performance than .net core and .net 5

> Messages sent after 5 seconds
> Waiting on 108 to complete processing (1 second pause)
> 
> Results:
>   Messages sent successfully     : 4096
>   Messages failed                : 0
>   Bytes sent successfully        : 268435456
>   Bytes received successfully    : 268435456
>   Elapsed time sending (ms)      : 5322ms
>   Elapsed time sending (seconds) : 5s
>   Send bytes per second          : 53687091.2B/s
>   Send kilobytes per second      : 52428.8kB/s
>   Send megabytes per second      : 51.2MB/s
>

**Comment by jchristn** [comment]
Hi @shanto462 were you able to find anything more on this?  I wasn't able to reproduce on my end, and you mentioned you were using the test.throughput project - were you able to use ANTS or something similar to track it down?  If not I'll close.
