### ISSUE TITLE
Is it scalable?

### ISSUE THREAD

**Issue by ygl-rg** [jchristn/WatsonTcp#11]
Hi. I am interested in this lib. I want to know whether it is capable to server 10K+ connections?

Thanks

**Comment by jchristn** [comment]
Hi @ygl-rg , I've never tested it to that scale.  I've tested to dozens and it was fine.  If you happen to test it to scale, let us know your results!

**Comment by mdawood1991** [comment]
@ygl-rg  how did you testing go?

**Comment by ygl-rg** [comment]
@mdawood1991 I haven't got time to test yet.
