### ISSUE TITLE
Considering about upgrade to .netstandard/.net5?

### ISSUE THREAD

**Issue by BigDream324** [jchristn/WatsonTcp#111]
.net framework will not be supported by microsoft, would you like upgrade this amazing project to .net standard or .net5?

**Comment by jchristn** [comment]
Hi, it already also targets .NET Core, .NET Standard, and .NET 5.

**Comment by BigDream324** [comment]
oh. sorry for bothering you , I was misled by the release page of this repo.

**Comment by jchristn** [comment]
Thanks @BigDream324 I don't manage the releases tab any longer, as most users of the library get it through Github packages or NuGet rather than using the releases tab.  Have a nice holiday
