### ISSUE TITLE
Problem automatically loss the client from the server

### ISSUE THREAD

**Issue by sapurtcomputer30** [jchristn/WatsonTcp#112]
Hi, I have Watson server installed on a real server
But when the client connects, everything is fine, but after 1 second, the client is automatically disconnected from the server

While in LAN and IP 127.0.0.1 these problems do not exist and everything is fine

How can this problem be solved?
![server](https://user-images.githubusercontent.com/26039089/103084569-2b5e2a80-4594-11eb-8964-026fce43b1a2.png)

**Comment by jchristn** [comment]
I see you are using Forms. Are you instantiating the client or server within a form?  Please post code to reproduce the problem. Thanks

**Comment by jchristn** [comment]
Closing, no code/steps to reproduce provided.
