### ISSUE TITLE
SSL from Stream

### ISSUE THREAD

**Issue by Jyck** [jchristn/WatsonTcp#113]
Hi

sometimes i want to deliver the certificate within in the application and not within a file.
if possible please support a second override of  WatsonTcpServer, WatsonTcpClient with byte[] for pfxCertFile
X509Certificate2 supports it with:  X509Certificate2(byte[] rawData, SecureString password);

greetings and thanks for the project!

Edit:  WatsonTcpClient  contains X509Certificate2 override. this can be used the same way.

**Comment by jchristn** [comment]
Thanks @Jyck - would it make life easier if I added the constructors that created the X509Certificate2 on your behalf using the supplied byte array?  Cheers

**Comment by Jyck** [comment]
hi @jchristn optional, only if you have time. 
I transfered the pfx file file onetime to a byte Array -> hex -> string.
the string is stored inside the client application an can also obfuscated.

on client application start: string->hex-> byteArray->X509Certificate2
