### ISSUE TITLE
Best approach - Zip file uploads from Client to Server (plus hash value check)

### ISSUE THREAD

**Issue by bukkideme** [jchristn/WatsonTcp#114]
Hello Everyone, and Happy New Year when it comes at your local time zone! :)

I am asking for advice for best approach how I should use this WatsonTcp package.
I need to upload ZIP files, one file per day from a Client application to a Server application. At both ends I would like to use WatsonTcp. The size of the Zip files varies between 50-150 MBytes.

I am thinking about the following:

1. I create a FileStream from the zip file in the following way at the Client side (i only show part of the code):
```
using (FileStream fss = new FileStream(zipFilePath, FileMode.Open, FileAccess.Read))
                                    {
                                        using (SHA256 mySHA256 = SHA256.Create())
                                        {
                                            byte[] hashValue = mySHA256.ComputeHash(fss);
                                            Dictionary<object, object> metadata = new Dictionary<object, object>();
                                            metadata.Add(MetaData.FileName, Path.GetFileName(zipFilePath));
                                            metadata.Add(MetaData.FileSize, length);
                                            metadata.Add(MetaData.UploadStarted, DateTime.Now);
                                            metadata.Add(MetaData.CheckSum, hashValue);

                                            SyncResponse resp = Client.SendAndWait(ClientTimeout, fss.Length, fss, metadata);
                                            
                                            bool repliedHashOK = (bool)resp.Metadata[MetaData.CheckSumOK];
                                            if (repliedHashOK)  {}
                                            else {}
                                         }
                                    }

```
2. At the server side, I register for the Callback "private static SyncResponse SyncRequestReceived(SyncRequest req)". Inside this, I should recalculate the hash value of the FileStream, compare to the Value of the MetaData.CheckSum Key, then set the MetaData.CheckSumOK accordingly before sending the SyncResponse back to the Client.

Question:

I need to create the ZIP file at the Server side if the hash values match. For this, what data element can I use in the "private static SyncResponse SyncRequestReceived(SyncRequest req)" callback method? The "req.Data" is a byte array, I guess this array contains the same data what was sent by the Client.SendAndWait() method in the form of a FileStream? So I can calculate hash on this byte array, and I should be able to create the zip file from the byte array, yes?

Thanks very much for help, and any suggestions how I should do this file transfer better!
Best Regards,

**Comment by jchristn** [comment]
Hi @bukkideme thanks for your note.  The main reason for the payload field ```Data``` within ```SyncRequest``` being a byte array is that it is meant for synchronous messaging.  I've considered adding a ```Stream``` variant, but had not gotten to it yet.  Seems like now I might have a good reason to do that :)

For your implementation, I'd create a ```MemoryStream``` from the data, i.e.

```
MemoryStream ms = new MemoryStream();
ms.Write(args.Data, 0, args.Data.Length);
ms.Seek(0, SeekOrigin.Begin);
```

Then run the hash computation over the ```MemoryStream```, and if valid, write it out to a ```FileStream```.

Something you may want to consider doing: when you run your hash function over a stream, it would be good to confirm whether or not the hash function resets the stream's position.  Otherwise after you run the hash, the position may be at the end of the stream, and when you pass it off to Watson, it may be unable to read the specified number of bytes.  You should consider doing a ```.Seek(0, SeekOrigin.Begin)``` before passing it into Watson.

Leaving this open in case you have any other questions etc!

Cheers and Happy New Year!  Joel

**Comment by bukkideme** [comment]
Hi @jchristn !

Thanks very much for your suggestions, also regarding how to be careful with the stream position and the MemoryStream!
I will test some cases in my implementation. 

Before that, I have another question:
I was playing a bit with the TestServerStream and the TestClientStream examples. In the Server example, inside the "`private static SyncResponse SyncRequestReceived(SyncRequest req)`" method, the last line creates and sends the reply back to the Client. At this place I would like to send the hash compare result back inside the meta data. But I do not need to send the file data back though.
This line:
`return new SyncResponse(req, retMetadata, "Here is your response!");`
Am I right about that, in this very example we just send back the whole SyncRequest object, so also including the Data part? In the case of a larger file, this is not really efficient, since I do not want the whole file data in the response back, yes?
So I guess I would create the following reply:
```
SyncRequest myReply = req;
myReply.Data = null;
return new SyncResponse(req, retMetadata, "Here is your response!");
```
The problem is that, SyncRequest is Read only property. How can i work around this?

Thanks again for your help!
Best Regards,

**Comment by jchristn** [comment]
Hi @bukkideme returning the original ```SyncRequest``` back is only to allow for efficient access to metadata used to send the response.  The original data is not sent.  Since it is a reference, you shouldn't need to worry about nulling out the ```Data``` property.  For the implementation, please feel free to check out the ```DataReceiver``` method within ```WatsonTcpServer```, specifically line 1073 in the current HEAD.
```
SyncResponse syncResp = _Callbacks.HandleSyncRequestReceived(syncReq);
if (syncResp != null)
{ 
    WatsonCommon.BytesToStream(syncResp.Data, out long contentLength, out Stream stream);
    WatsonMessage respMsg = new WatsonMessage(
        syncResp.Metadata,
        contentLength,
        stream,
        false,
        true,
        msg.Expiration.Value,
        msg.ConversationGuid,
        (_Settings.DebugMessages ? _Settings.Logger : null)); 
    SendInternal(client, respMsg, contentLength, stream);
}
```
Cheers, Joel

**Comment by bukkideme** [comment]
Thanks! So if I understood you well, I can simply call the method like this with the received SyncRequest req parameter unmodified, and only insert my own metadata variable with my Bool result info:

`return new SyncResponse(req, retMetadata, "Here is your response!");`

I will test the communication in this way, I am still working on other parts of the code.
Thanks again! :)

**Comment by jchristn** [comment]
Exactly :)

**Comment by bukkideme** [comment]
Now I will also need to figure out a proper structure and logic for a 3 PCs case. 
I will need to use my application in three different configurations (I will use config files for easy setup), running on three different PCs. PC#1 can see PC#2, PC#2 can see PC#3, but PC#1 cannot reach PC#3 directly via TCP (some security restrictions which I do not have admin right to change).

So one idea what I could do:
PC#1: running a WatsonTcpClient.
PC#2: running a WatsonTcpServer to get data from PC#1, and a WatsonTcpClient to send data to PC#3 server.
PC#3: running a WatsonTcpServer.

1. PC#1: here I create the zip file, then via a FileStream, I send it to PC#2 using Sendandwait(). I wait for metadata response, handle errors, handle Timeout case, handle hash mismatch. Logging, setup retry frequency if needed. 
2. At PC#2, If the data arrived OK, hash values match, then I use again a Sendandwait from the SyncRequestReceivedServer() method, and handle again those error/timeout cases what I did at PC#1.
3. At PC#3 gets the data OK from PC#2, then I can recreate the ZIP file and store it at local HDD. Again, I need to handle errors, etc...

I feel this approach is a bit cumbersome, due to the numerous hash values and other timeout/error checks. My knowledge quite limited (also) in TCP-IP things, I wonder if there could be a more elegant solution is such cases which I have to deal with. Maybe a kind of "TCP-IP tunnel", which could run in the middle-PC (PC#2), and would only re-direct the incoming TCP-messages back and forth between PC#1 and #3. Maybe this is even possible at the operation system level, but for that I need to figure out what configuration changes I am allowed to make at PC#2...

Thanks for any suggestions! :)

**Comment by jchristn** [comment]
Hi @bukkideme definitely nothing wrong with running your code controlling both a server instance and a client instance like you would need to do on PC #2.  The nice thing is that most of the underlying TCP work is already taken care of for you.  You could very easily just implement a proxy of sorts in #2 that would listen for incoming streams and send them to #3.  The hard part will be dealing with errors, i.e. #3 goes down prior to a response being fully sent back to #2 (that would be sent back to #1).  Best of luck to you.
