### ISSUE TITLE
WatsonTcpClient() constructor accepts "localhost", WatsonTcpServer not

### ISSUE THREAD

**Issue by bukkideme** [jchristn/WatsonTcp#115]
Hi!

I got a bit confused because I can use the "localhost" string for the WatsonTCPClient constructor, but not for the WatsonTcpServer. I get this error:
```
Server start, System.FormatException: An invalid IP address was specified.
   at System.Net.IPAddress.InternalParse(String ipString, Boolean tryParse)
   at WatsonTcp.WatsonTcpServer..ctor(String listenerIp, Int32 listenerPort)
```
If I use 172.0.0.1 instead of localhost, it works. Is there a reason I am not aware of why the server constructor does not accept "localhost" as IP input parameter?
Thanks! :)
(otherwise everything works nice and smooth so far in my project :) )

**Comment by jchristn** [comment]
Hi @bukkideme thanks for catching this!  I added better (explicit) localhost support in v4.7.1.1, which you can find using the links below.

Thanks!  Joel

NuGet: https://www.nuget.org/packages/WatsonTcp/4.7.1.1
Commit: https://github.com/jchristn/WatsonTcp/commits/master
