### ISSUE TITLE
Large FileStream sending via SendAndWait() from Client to Server

### ISSUE THREAD

**Issue by bukkideme** [jchristn/WatsonTcp#116]
Hello!

First of all, I use this package with good success, my project works fine. Only once, I have got a strange error. I did not have time to investigate it deeper yet, neither to setup a test environment to try to reproduce it.
The error is a Timeout exception thrown by the SendAndWait() method called from a Client which connects first to a Server.
Usually my application sends zip files with size around 100-200 Mbytes, in a form of a FileStream passed to the SendAndWait() method. It just works fine. 
This is the usage (only the relevant part):

```
int ClientTimeout = 120_000; //2 minutes
using (FileStream fss = new FileStream(zipFilePath, FileMode.Open, FileAccess.Read))
{
      SyncResponse resp = Client.SendAndWait(ClientTimeout, fss.Length, fss, metadata);     
}
```

At one occasion so far, the zip file size was around 1 GB instead of the few hundreds Mbytes, however I do not know if this has anything to do with the seen problem. 
The problem itself was that, the method did not throw the "System.TimeoutException: A synchronous request was not received within the timeout window..." exception after 2 minutes, but after about ~7 minutes! I also need to check if there is any possible bug in the error logging module in my code, but so far I did not find an explanation.

I know based on this info it is a long shot, but maybe someone can have an idea: can we imagine a scenario when the SendAndWait() method does not throw Timeout after the specified time span, but much later?

Thanks for any suggestions! :)
Best Regards,

**Comment by kzonesoft** [comment]
This library is perfect. 
I think you use stream event, and set timeout in task.

**Comment by bukkideme** [comment]
"I think you use stream event, and set timeout in task."
Nope. I use the blocking SendAndWait() method only.

Still no time to test again, anyway, if I notice such behavior again, I will investigate it deeper.
@jchristn , if you wish you can close this Issue, we might reopen it only if I find the root cause.
Thanks again for this great package! :)
