### ISSUE TITLE
Server.Settings.Logger - log levels

### ISSUE THREAD

**Issue by zsolt777** [jchristn/WatsonTcp#118]
Hi @jchristn!

Is there a way to get the log level (info, error, etc.) when the server raises log events?

Thank you!

**Comment by jchristn** [comment]
Hi @zsolt777, currently there is not; it's a single log method ```Settings.Logger```.  In the current implementation we would need to have separate log methods by severity, or, a single log method that includes a severity parameter.  Which would be easier for you to consume, or is there another option that you would prefer?

**Comment by zsolt777** [comment]
I would prefer the latter (with severity parameter). 
Thank you very much!

**Comment by jchristn** [comment]
Great suggestion @zsolt777 - this is implemented in v4.8.0 (incremented due to breaking change)

NuGet: https://www.nuget.org/packages/WatsonTcp/4.8.0
Commit: https://github.com/jchristn/WatsonTcp/commit/0ef4d435bc0d1a178d7e157e608d8d6e2392cc91

Please re-open if any issues.  Thanks!
