### ISSUE TITLE
how many connections can this handle simultaneously

### ISSUE THREAD

**Issue by mdawood1991** [jchristn/WatsonTcp#12]
Hi,

If yes, how many max connections can this handle simultaneously?

Because currently I have a TCP server developed using SuperSocket.NET. But having issues in sending Acknowledgement's to the devices.

So if I use this library, how many requests can it handle?

Thanks

**Comment by jchristn** [comment]
Hi @mdawood1991 , I've never tested it to scale beyond dozens of connections.  It would be straight forward to write a test program that spawns thousands of long-lived client threads.  Cheers
