### ISSUE TITLE
SSL Connection between Linux und Windows

### ISSUE THREAD

**Issue by thewidder** [jchristn/WatsonTcp#120]
Hallo,

I cant get a ssl connection working between a Linux (as ssl server) and Windows (as ssl Client) .
The following exception will be thrown:

> Received an unexpected EOF or 0 bytes from the transport stream.

> at System.Net.Security.SslStream.<ReceiveBlobAsync>d__172`1.MoveNext()\r\n   
> at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   
> at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   
> at System.Threading.Tasks.ValueTask`1.get_Result()\r\n  
> at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()\r\n   
> at System.Net.Security.SslStream.<ForceAuthenticationAsync>d__171`1.MoveNext()\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n 
> at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   
> at System.Runtime.CompilerServices.TaskAwaiter.GetResult()\r\n   
> at System.Net.Security.SslStream.ProcessAuthentication(Boolean isAsync, Boolean isApm, CancellationToken cancellationToken)\r\n   
> at System.Net.Security.SslStream.AuthenticateAsClient(SslClientAuthenticationOptions sslClientAuthenticationOptions)\r\n   
> at System.Net.Security.SslStream.AuthenticateAsClient(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)\r\n   
> at WatsonTcp.WatsonTcpClient.Connect()\r\n   

On Windows 10, with NET5
```
_wts = new WatsonTcpServer(null, port, cert);
_wts.Events.MessageReceived += Events_MessageReceived;
_wts.Settings.AcceptInvalidCertificates = true;
_wts.Settings.MutuallyAuthenticate = true;
_wts.Start();
```

On Rasbian 9 (Debian Stretch) with NET5 too.
```
WatsonTcpClient wtc = new WatsonTcpClient(address, port, cert);
wtc.Events.MessageReceived += Events_MessageReceived;
wtc.Settings.AcceptInvalidCertificates = true;
wtc.Settings.MutuallyAuthenticate = true;
wtc.Connect();
```

i use a self signed created cert:

```
string secp256r1Oid = "1.2.840.10045.3.1.7";
var ecdsa = ECDsa.Create(ECCurve.CreateFromValue(secp256r1Oid));
var certRequest = new CertificateRequest($"CN={subjectName}", ecdsa, HashAlgorithmName.SHA256);
certRequest.CertificateExtensions.Add(new X509KeyUsageExtension(X509KeyUsageFlags.DigitalSignature, true));
X509Certificate2 generatedCert = certRequest.CreateSelfSigned(from, to);
X509Certificate2(generatedCert.Export(X509ContentType.Pfx));
```

Any Idea?

**Comment by jchristn** [comment]
Hi @thewidder did you install the certificate into each machine?

**Comment by thewidder** [comment]
> 
> 
> Hi @thewidder did you install the certificate into each machine?

my certificate is generated and used "on the fly". 

sorry, is it necessary to install it?
and how to install this certificates?

**Comment by jchristn** [comment]
Yes, certificates have to be installed.  For Windows you can import the PFX (with private key) using either IIS (easier) or the Certificate Manager plug-in within the MMC.  I don't have experience doing this on Debian (and it may not be necessary to install them on Debian) but I did find this: https://unix.stackexchange.com/questions/90450/adding-a-self-signed-certificate-to-the-trusted-list

Also be sure to set ```Settings.AcceptInvalidCertificates``` to true and ```Settings.MutuallyAuthenticate``` to false.

If you'd like to test using a test certificate, the ```Test.Client``` and ```Test.Server``` projects in source both have a file ```test.pfx``` which is self-signed (password is ```password```) that you can use to try it out.

**Comment by jchristn** [comment]
Please re-open if the above doesn't solve the issue
