### ISSUE TITLE
SendAndWait works only the first time

### ISSUE THREAD

**Issue by ozrecsec** [jchristn/WatsonTcp#128]
Hi jchristin,
today I'm trying to upgrade my program to use the new 4.8.1 version of WatsonTcp from the far 4.1.5 one that always worked finely for me.

I've noticed that now it's very very quick to send messages, with my old 4.1.5 version i could send up to 65 messages per second (async messages), and now with the 4.8.1 i can reach the outstanding speed of 1500 msg/sec!! so awesome!

But sadly thre is also a problem... :-( 
If I call on client a SendAndWait it works fine, but only the first time, if then I call another SendAndWait this hangs until the timeout exception...

this is my sample client code:
```
            cli = new WatsonTcpClient("localhost", 23456);
            cli.Events.ServerConnected += Cli_ServerConnected;
            cli.Events.MessageReceived += Cli_MessageReceived;
            cli.Settings.DebugMessages = false;
            cli.Connect();
            cli.Send("Single message from client-1");
            cli.Send("Single message from client-2");
            cli.Send("Single message from client-3");

            SyncResponse srsp = cli.SendAndWait(30000, "1"); 
            Console.WriteLine(Encoding.UTF8.GetString(srsp.Data));
            srsp = cli.SendAndWait(30000, "1");  <<----- this row hangs and after 30 secondt fires a TimeoutException
            Console.WriteLine(Encoding.UTF8.GetString(srsp.Data));
```

and this is the server side that works only for the first time, for the second SendAndWait this is never fired

```
        private static SyncResponse SyncRequestReceived(SyncRequest req)
        {
            Console.WriteLine($"Syncrequest received from {req.IpPort}: {Encoding.UTF8.GetString(req.Data)}");
            SyncResponse ret;

            int delay = 0;
            int.TryParse(Encoding.UTF8.GetString(req.Data), out delay);
            if (delay == 0)
                delay = 1;

            System.Threading.Thread.Sleep(1000*delay);
            ret = new SyncResponse(req, $"Long work done :-) {delay}");

            Console.WriteLine("Syncrequest completed");
            return ret;
        }
```

many thanks in advance for your great work!
Michele

**Comment by jchristn** [comment]
Hi @ozrecsec good to hear from you.  What is your environment i.e. runtime (.NET Framework, .NET Core, .NET 5) and version?  Which operating system?  

I just tried using the ```Test.Server``` and ```Test.Client``` projects and they work without an issue sending a series of sequential ```SendAndWait``` requests (the ```Test.Server``` project automatically responds with a ```SyncResponse```).  

Cheers, Joel

**Comment by jchristn** [comment]
Here's the result on Windows 10 w/ .NET 5.0.  Right side is the client.
![image](https://user-images.githubusercontent.com/1421081/111818667-aa65b500-889c-11eb-93d2-367b8dc363a9.png)

Windows 10 w/ .NET 4.6.1
![image](https://user-images.githubusercontent.com/1421081/111818770-cb2e0a80-889c-11eb-9bb5-d5426ee3397f.png)

Windows 10 w/ .NET Core 3.1
![image](https://user-images.githubusercontent.com/1421081/111818866-e862d900-889c-11eb-95db-e7323db78801.png)

Are you running Windows 10 or a different version?  Linux/Mac?

**Comment by davidhays** [comment]
I don't know if this is another issue, but on 4.8.1, when I do WatsonTcpServer.Send (or SendAsync) multiple messages from the server, the client MessageReceived is only fired once, I've rolled back to 4.8.0 and it fires for every message.

**Comment by ozrecsec** [comment]
thank you @davidhays I've tried to reference 4.8.0 version in my test project and SendAndWait works fine.

My develop environment is on Windows server 2012R2 and Framework .NET 4.6.1.

**Comment by jchristn** [comment]
Got it - was able to reproduce.  Seems client ```DataReceiver``` isn't having its ```SemaphoreSlim``` released.

**Comment by jchristn** [comment]
Could you give v4.8.2 a try and let me know if this resolves the issue?

NuGet: https://www.nuget.org/packages/WatsonTcp/4.8.2
Commit: https://github.com/jchristn/WatsonTcp/commit/5ed315665ae71a7c9b0be7a47883aaf0542e4bbf

**Comment by davidhays** [comment]
4.8.2 works for me.

**Comment by jchristn** [comment]
Awesome. @ozrecsec please close if this fixes it!  Cheers Joel

**Comment by ozrecsec** [comment]
I've tested 4.8.2 and works fine for me too. 
thanks!
