### ISSUE TITLE
Server rejects new connections after a bad connect

### ISSUE THREAD

**Issue by MrMikeJJ** [jchristn/WatsonTcp#13]
Hi,
After a bad connect, the server rejects all new connections. This can be replicated by using the SSL server and then connecting to it with putty.
Simple fix though :)

Replace all the occurrences of  "return" with "continue" in the while loop of AcceptConnections.
thanks
Mike

**Comment by MrMikeJJ** [comment]
Still had issues with the SSL version getting stuck while waiting for a connection to finish - which would never finish.
Resolved by changing AuthenticateAsServer to BeginAuthenticateAsServer :)

**Comment by jchristn** [comment]
Thanks @MrMikeJJ for both of these, I'll incorporate now and update Github and Nuget both!

**Comment by jchristn** [comment]
Hi @MrMikeJJ for the BeginAuthenticateAsServer, can you submit a pull request?  I'd like to see your implementation.  Thanks!

**Comment by MrMikeJJ** [comment]
Sure. Will be a few days though, i will have to redo this without the other changes which I did for my use case. And won't be near the computer I did this on until Tuesday.

**Comment by MrMikeJJ** [comment]
This was fixed with the pull requests :)
