### ISSUE TITLE
Reconhecimento. 

### ISSUE THREAD

**Issue by brunotrevisan** [jchristn/WatsonTcp#134]
Tenho um projeto chamado TNavigator que é um multi emulador de jogos para xbox e pc, hoje ele conta com 55 plataformas 
Conheci ontem o WatsonTcp, e em poucas horas consegui utiliza-la para colocar o TNavigator para funcionar online, 
agora os Usuários do TNavigator vão poder jogar os jogos antigos online com os amigos graças a vocês.

O TNavigator não é gratuito mas o dinheiro é utilizado para servidores e criação de novos apps distribuído gratuitamente aos usuários. 

Após a liberação do modo online vamos utilizar uma parte desse dinheiro realizar uma doação ao projeto de vocês em forma de agradecimento. Eu e mais 150 mil usuários somos muito grato ao seu projeto.  e os devidos créditos serão dados.

Parabéns pelo projeto facilita muito a vida dos desenvolvedores.

**Comment by jchristn** [comment]
Hi @brunotrevisan I'm sorry I missed your note and that it took so long to respond!  Thank you for your kind words!  Cheers, Joel

Hola @brunotrevisan, ¡lamento haber perdido tu nota y haber tardado tanto en responder! ¡Gracias por sus amables palabras! Saludos, Joel
