### ISSUE TITLE
Identify Users by Something Faster Than String

### ISSUE THREAD

**Issue by pha3z** [jchristn/WatsonTcp#142]
I'm not sure how you are typically tracking connected users, but for myself (and I guess this is pretty common), an easy technique is to hash the IpPort string of user to form a dictionary key.

This might be an excessive micro-op (??) but some people might appreciate it:
If you're dealing with hi-thru-put of a LOT of messages, you could save some computation if hashing could be done on something better than a string.  You could expose all IpPort combinations in a (16 byte, 2 byte) tuple or 18byte array to support IPv6:Port combinations.  Hashing 18 bytes is going to be *substantially* faster than hashing a string representation.

I actually would prefer the byte-array version myself since it allows you to pass around an array pointer instead of the numeric ip values.

Thoughts?

**Comment by jchristn** [comment]
Hi @pha3z it's a great point.  The primary reason I didn't do something like this is I wanted to opt for ease of use more than anything, and the string variant is pretty simple.  

For personal projects, I generally don't rely on the ip:port for anything other than disconnection.  I use the metadata as a means of exchanging session state (which also identifies the user, etc).

Cheers, Joel

(moving to discussion; if there's consensus on this, happy to add to the backlog, or if you/someone has a PR that is in line with the spirit of the library, I'd be open to a merge)
