### ISSUE TITLE
Feature Request: Send byte[] overload with length and optional parameter offset = 0

### ISSUE THREAD

**Issue by pha3z** [jchristn/WatsonTcp#144]
Send(ipPort, byteBuffer, length, [offset = 0]);

There is an extremely popular serializer called CerasSerializer.  Its by far the best serializer I've ever seen. 

It encourages the reuse of a single byteBuffer to eliminate garbage creation.  But that requires specifying buffer length when you want to transmit it.

Can we add an overload for length and optional offset?  Of course, this also benefits anybody who wants to reuse a buffer for sending.

**Comment by jchristn** [comment]
Hi @pha3z I'm very sorry for the delay.  We moved in the past month and some other life priorities (all good things) got in the way.  Looking at this now.

**Comment by jchristn** [comment]
Hi @pha3z please let me know if this works for you.  If any issues, please re-open.  Great suggestion.

Commit: https://github.com/jchristn/WatsonTcp/commit/2a6e7b28e0357649466fcdd75a727804f7f74255
NuGet: https://www.nuget.org/packages/WatsonTcp/4.8.9
