### ISSUE TITLE
How to compile for Unity IL2CPP 

### ISSUE THREAD

**Issue by Ahmed310** [jchristn/WatsonTcp#148]
It compiles but getting runtime error while running on Android IL2CPP 64 bit. documentation mentions how to compile for mono. 

`08-05 20:03:26.004  3817  3841 I Unity   : SystemInfo CPU = ARM64 FP ASIMD AES, Cores = 8, Memory = 5500mb
08-05 20:03:26.004  3817  3841 I Unity   : SystemInfo ARM big.LITTLE configuration: 1 big (mask: 0x80), 7 little (mask: 0x7f)
08-05 20:03:26.004  3817  3841 I Unity   : ApplicationInfo com.DefaultCompany.Empty version 0.1 build 2de827ca-90f1-4fb6-91dd-44feeb7ef817
08-05 20:03:26.004  3817  3841 I Unity   : Built from '2020.1/staging' branch, Version '2020.1.6f1 (fc477ca6df10)', Build type 'Release', Scripting Backend 'il2cpp', CPU 'arm64-v8a', Stripping 'Enabled'
08-05 20:03:30.627  3817  3841 E Unity   : SocketException: mono-io-layer-error (113)
08-05 20:03:30.627  3817  3841 E Unity   :   at System.Net.Sockets.SocketAsyncResult.CheckIfThrowDelayedException () [0x00000] in <00000000000000000000000000000000>:0 
08-05 20:03:30.627  3817  3841 E Unity   :   at System.Net.Sockets.TcpClient.EndConnect (System.IAsyncResult asyncResult) [0x00000] in <00000000000000000000000000000000>:0 
08-05 20:03:30.627  3817  3841 E Unity   :   at WatsonTcp.WatsonTcpClient.Connect () [0x00000] in <00000000000000000000000000000000>:0 
08-05 20:03:30.627  3817  3841 E Unity   :   at ClientManager.Start () [0x00000] in <00000000000000000000000000000000>:0 
08-05 20:03:30.627  3817  3841 E Unity   :  
08-05 20:03:30.627  3817  3841 E Unity   : (Filename: currently not available on il2cpp Line: -1)

`

**Comment by jchristn** [comment]
Hi @Ahmed310 sorry I don't have the environment necessary to reproduce this.  Cursory google searches indicate that there may be a problem with the IP/port on which you're trying to connect.  Please share code for how you are instantiating the client and connecting to the server.

**Comment by Ahmed310** [comment]
@jchristn you are right the ip on serverside was different then client side, now the connection is established but getting exception while sending message.

here is the sample code 

`    public Button btn;
    WatsonTcpClient client;
    void Start()
    {
        client = new WatsonTcpClient("192.168.10.7", 9000);

        client.Events.ServerConnected += ServerConnected;
        client.Events.ServerDisconnected += ServerDisconnected;
        client.Events.MessageReceived += MessageReceived;
        client.Connect();

        btn.onClick.AddListener(onClickBtn);
    }

    void onClickBtn() 
    {
        if (client != null && client.Connected)
        {
            client.Send(BitConverter.GetBytes(786));
            client.Send(BitConverter.GetBytes(1010));
        }
        else
        {
            Debug.Log("Client is null or not connected");
            if (client != null)
            {
                Debug.Log($"Oh Well {client.Connected}");
            }
        }
    }` 
    
   Debugging results are as follow if I call the send function I get this exception
   
`08-06 01:00:15.957 30780 30830 E Unity   : NullReferenceException: Object reference not set to an instance of an object.
08-06 01:00:15.957 30780 30830 E Unity   :   at WatsonTcp.WatsonTcpClient.Send (System.Int64 contentLength, System.IO.Stream stream, System.Collections.Generic.Dictionary`2[TKey,TValue] metadata) [0x00000] in <00000000000000000000000000000000>:0 
08-06 01:00:15.957 30780 30830 E Unity   :   at WatsonTcp.WatsonTcpClient.Send (System.Byte[] data, System.Collections.Generic.Dictionary`2[TKey,TValue] metadata, System.Int32 start) [0x00000] in <00000000000000000000000000000000>:0 
08-06 01:00:15.957 30780 30830 E Unity   :   at ClientManager.onClickBtn () [0x00000] in <00000000000000000000000000000000>:0 
08-06 01:00:15.957 30780 30830 E Unity   :   at UnityEngine.Events.UnityAction.Invoke () [0x00000] in <00000000000000000000000000000000>:0 
08-06 01:00:15.957 30780 30830 E Unity   :   at UnityEngine.Events.UnityEvent.Invoke () [0x00000] in <00000000000000000000000000000000>:0 
08-06 01:00:15.957 30780 30830 E Unity   :   at UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1].Invoke (T1 handler, UnityEngine.EventSystems.BaseEventData eventData) [0x00000] in <00000000000000000000000000000000>:0 
08-06 01:00:15.957 30780 30830 E Unity   :   at UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, U

`
   
   The client itself is not null but the status Connected remains false
   in logs it prints Oh Well false : meaning Connected is false

**Comment by jchristn** [comment]
Can you set ```client.Events.ExceptionEncountered``` and paste the event argument contents here?  Also please set ```client.Settings.Logger``` and paste any relevant log messages.

**Comment by Ahmed310** [comment]
sure I will by tomorrow

**Comment by Ahmed310** [comment]
After enabling logs & exceptions it turns out the Newtonsoft was throwing the exception as it was not compatible with il2cpp.

here are the steps I did to make it functional
1: Use source code of WatsonTCP rather dll
2: use il2cpp compatible Newtonsoft, I used this [ https://github.com/jilleJr/Newtonsoft.Json-for-Unity/tree/13.0.102 ]

**Comment by jchristn** [comment]
Good to know.  Thanks for sharing @Ahmed310.  I may have to look into implementing custom serializers.

**Comment by Ahmed310** [comment]
custom serializer will be even better as It will remove the dependency of newtonsoft
