### ISSUE TITLE
(Unity) Connects but can not send message

### ISSUE THREAD

**Issue by deathbull** [jchristn/WatsonTcp#154]
In editor everything works normal, no problem. But when i built and run it, it only connects but can not send message.

**Comment by deathbull** [comment]
Also no return for Send function

**Comment by jchristn** [comment]
For Unity you have to clone and build using the correct Newtonsoft.Json.

**Comment by deathbull** [comment]
> For Unity you have to clone and build using the correct Newtonsoft.Json.

You mean cloning the source code ?

**Comment by deathbull** [comment]
Did not work.

**Comment by jchristn** [comment]
Yes apparently there is an issue with Newtonsoft.Json and unity that requires you to build it using a specific version. I don't have the environment to test and reproduce.

**Comment by jchristn** [comment]
Do any of these help?  
https://github.com/jchristn/WatsonTcp/issues/148
https://github.com/jchristn/WatsonTcp/issues/107

**Comment by deathbull** [comment]
> Do any of these help?
> #148
> #107

I tested il2cpp and mono option but there is no difference between them and client does not disconnect by itself

**Comment by deathbull** [comment]
Also i upgraded newtonsoft.json to 12.0.301 but there is no difference aswell

**Comment by jchristn** [comment]
Got it.  I assume you're using WatsonTcp on both the client and server side?  Could you try setting (on both client and server):
```
client.Settings.Logger
client.Events.ExceptionEncountered
```
And capture their output, and paste here?  Cheers

**Comment by jchristn** [comment]
Hi @deathbull have you seen this? https://forum.unity.com/threads/newtonsoft-json-package.843220/

**Comment by deathbull** [comment]
![image](https://user-images.githubusercontent.com/48456995/131706054-e977f703-2695-45f7-b22a-ae8dc4a489a7.png)

**Comment by jchristn** [comment]
Yeah, I think you need the Newtonsoft.Json built specifically for Unity.

**Comment by deathbull** [comment]
> Hi @deathbull have you seen this? https://forum.unity.com/threads/newtonsoft-json-package.843220/

actually i can not use any other netwonsoft.json except unity package manager because it required his own package, when i uninstall newtonsoft.json from package manager it uninstall the other packages for build the game

**Comment by deathbull** [comment]
> Yeah, I think you need the Newtonsoft.Json built specifically for Unity. What are you trying to send in terms of data?

some bigendian data as byte

**Comment by jchristn** [comment]
> actually i can not use any other netwonsoft.json except unity package manager because it required his own package, when i uninstall newtonsoft.json from package manager it uninstall the other packages for build the game

What I'm recommending is cloning the WatsonTcp source, removing the Newtonsoft.Json reference, and then adding a reference to the package that Unity expects.  Then, add the reference to WatsonTcp that was built on your machine using the Newtonsoft.Json that Unity expects.  Have you tried that?

**Comment by deathbull** [comment]
Ok let me try

**Comment by deathbull** [comment]
Tried and same result 
![image](https://user-images.githubusercontent.com/48456995/131713047-e750158a-42ea-4f87-90e4-b0068bd9edb5.png)

**Comment by deathbull** [comment]
i can not because it doesn't let me to have another dll it says duplicated and you can not build or run the game

**Comment by deathbull** [comment]
tbh i really liked this library, i never get an error in editor, everything worked perfect. i think i have to try some other libraries could you help me with that ?

**Comment by jchristn** [comment]
Sorry I can't help with Unity. Good luck with your search.

**Comment by deathbull** [comment]
Thank you

**Comment by deathbull** [comment]
Your another library SimpleTcp requires Newtonsoft.Json ?

**Comment by deathbull** [comment]
Or CavemanTcp ?

**Comment by deathbull** [comment]
Ok i saw SimpleTcp doesn't require

**Comment by jchristn** [comment]
Neither of those require Newtonsoft.Json, however, neither of them provide framing.

**Comment by deathbull** [comment]
> Neither of those require Newtonsoft.Json, however, neither of them provide framing.

i actually tried watsonwebsocket and i had no problem also doesn't require any other library

**Comment by jchristn** [comment]
Perfect!  The underlying websocket implementation provides framing by design. Not so with TCP itself. Cheers

**Comment by deathbull** [comment]
Thank you so much

**Comment by jchristn** [comment]
@deathbull if you can help me recreate a simple environment, I can work on a fork that will support Unity.  Let me know.  I don't have any experience with Unity.

**Comment by deathbull** [comment]
> @deathbull if you can help me recreate a simple environment, I can work on a fork that will support Unity. Let me know. I don't have any experience with Unity.

Sure but do not forget websocket works pretty well, but if you want then i can help you

**Comment by deathbull** [comment]
@jchristn maybe you should check pull request.
