### ISSUE TITLE
Include XML documentation in the NuGet package

### ISSUE THREAD

**Issue by markonius** [jchristn/WatsonTcp#164]
After adding the package via `dotnet add package WatsonTcp`, documentation doesn't appear on mouse over in VSCode, only the member signature.

This is usually trivially solved by adding
```
<GenerateDocumentationFile>true</GenerateDocumentationFile>
```
to the .csproj.

**Comment by jchristn** [comment]
Hi @markonius thanks for letting me know!  Could you check v4.8.14.4 and let me know if it is resolved?
NuGet: https://www.nuget.org/packages/WatsonTcp/4.8.14.4
Commit: https://github.com/jchristn/WatsonTcp/commit/f02ea38bfa388c9e391dfce92b2075138634e5d5

**Comment by markonius** [comment]
Yup, documentation is shown as expected now. Thanks!
Also, thanks for the mention in the readme!
