### ISSUE TITLE
SSL Test.Client throwing an exception 

### ISSUE THREAD

**Issue by Ahmed310** [jchristn/WatsonTcp#165]
While trying to run the Test.Client project that comes with demo, it is throwing the following exception.

`Server IP: [localhost] localhost
Server port: [9000] 9000
Use SSL: [y/N]? y
Supply SSL certificate: [y/N]? y
Certificate file: [test.pfx] test.pfx
Certificate password: [password] password
Accept invalid certs: [Y/n]? y
Mutually authenticate: [y/N]? y
Unhandled exception. Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: The system cannot find the file specified.
   at Internal.Cryptography.Pal.CertificatePal.FromBlobOrFile(ReadOnlySpan`1 rawData, String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(String fileName, String password)
   at WatsonTcp.WatsonTcpClient..ctor(String serverIp, Int32 serverPort, String pfxCertFile, String pfxCertPass, TlsVersion tlsVersion) in C:\Users\mahme\Downloads\WatsonTcp-master\WatsonTcp-master\WatsonTcp\WatsonTcpClient.cs:line 218
   at TestClient.TestClient.ConnectClient() in C:\Users\mahme\Downloads\WatsonTcp-master\WatsonTcp-master\Test.Client\Program.cs:line 202
   at TestClient.TestClient.InitializeClient() in C:\Users\mahme\Downloads\WatsonTcp-master\WatsonTcp-master\Test.Client\Program.cs:line 189
   at TestClient.TestClient.Main(String[] args) in C:\Users\mahme\Downloads\WatsonTcp-master\WatsonTcp-master\Test.Client\Program.cs:line 24`

**Comment by jchristn** [comment]
Is the test.pfx file present in the working directory?

**Comment by Ahmed310** [comment]
> 

yes it is

**Comment by jchristn** [comment]
Thanks. Which OS and runtime are you using?

**Comment by Ahmed310** [comment]
> Thanks. Which OS and runtime are you using?

Windows 10 and here is project settings

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
	  <TargetFrameworks>netcoreapp3.1;net461;net472;net5.0;net6.0</TargetFrameworks>
	  <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="test-certificate.txt" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="test-certificate.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WatsonTcp\WatsonTcp.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="test.pfx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>

**Comment by Ahmed310** [comment]
Windows 10 and here is project settings

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
	  <TargetFrameworks>netcoreapp3.1;net461;net472;net5.0;net6.0</TargetFrameworks>
	  <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="test-certificate.txt" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="test-certificate.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WatsonTcp\WatsonTcp.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="test.pfx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>

**Comment by jchristn** [comment]
That's strange, I don't have that issue using the ```Test.Client``` and ```Test.Server``` project.

Sounds like there are two issues.

1) It's failing because it can't find ```test.pfx```.  Do you see the file in the directory using ```dir```?

2) When not using SSL, it's not accepting connections.  Did you use ```Start()``` on the server to make sure it's running?

Here's what I see:

1) Connecting with SSL:
![image](https://user-images.githubusercontent.com/1421081/142774019-c2a0358e-4504-4e1c-9a9a-97827b655c68.png)

2) Connection without SSL:
![image](https://user-images.githubusercontent.com/1421081/142774044-270f2cb5-9245-4f04-b83d-4745df874e49.png)

**Comment by Ahmed310** [comment]
Alright, that's really weird why on my machine it not picking cert, I will debug it in detail later or I will try to setup a new project.
you can close this issue or move it to discussion.

Thanks for Quick & detailed responses.

**Comment by jchristn** [comment]
Perhaps try pressing ```ENTER``` instead of typing ```localhost``` and same for the port number?  I see some weirdness in your exception message: ```No connection could be made because the target machine actively refused it. [::ffff:127.0.0.1]:9000```, not sure why it's ```[::ffff:127.0.0.1]:9000```.

When you are executing, which runtime are you running with?  Did you try on a variety of runtimes like net461, netcoreapp3.1, net5.0, net6.0?  We can keep this open, it's totally fine

**Comment by Ahmed310** [comment]
I tried multiple .net5 & net472
![image](https://user-images.githubusercontent.com/8081578/142875032-23198e88-8f28-492b-9ea9-408925f1b18a.png)

**Comment by jchristn** [comment]
I see what's happening. You're running Test.Server from a different directory. Try changing to the directory it's in and then running it, or, provide an explicit path to test.pfx when prompted.

**Comment by jchristn** [comment]
i.e. either:

```
$ cd \users\mahme\downloads\watsontcp-master\watsontcp-master\test.server\bin\debug\net472
$ test.server.exe
```
or
```
$ c:\users\mahme\downloads\watsontcp-master\watsontcp-master\test.server\bin\debug\net472\test.server.exe
Server IP: [localhost]
Server port: [9000]
Use SSL: [y/N]? y
Certificate file: [test.pfx] c:\users\mahme\downloads\watsontcp-master\watsontcp-master\test.server\bin\debug\net472\test.pfx
```

**Comment by Ahmed310** [comment]
Yes that was the issue, on launching executable from same folder it worked.

One question though. what if I provider complete path of certificate including name (e.g. c:/folder/test.pfx) will it work? or still I need to place it besides .exe .

if former is the case then It will become difficult when you are using Watson in unity e.g. for Android

**Comment by jchristn** [comment]
It uses File.Read* so you should be able to use relative or explicit paths.

**Comment by Ahmed310** [comment]
perfect!
