### ISSUE TITLE
System.ObjectDisposedException on WatsonTCPClient.Connect()

### ISSUE THREAD

**Issue by ahubertus44** [jchristn/WatsonTcp#177]
Hi,

I'm think I found a bug on the WatsonTCPClient.
Right now I'm using the WatsonTcpClient like this:
I do not keep a connection alive, I connect only when I send some data from the client then disconnect.
If I send data multiple times in a row like this I get the following error:

`System.ObjectDisposedException: "Safe handle has been closed.
ObjectDisposed_ObjectName_Name"`

Debug Log:
`[WatsonTcpClient] connecting to 127.0.0.1:25000
[WatsonTcpClient] exception encountered:
{
  "ClassName": "System.ObjectDisposedException",
  "Message": "Safe handle has been closed.",
  "Data": null,
  "InnerException": null,
  "HelpURL": null,
  "StackTraceString": "   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)\r\n   at System.Threading.WaitHandle.WaitOneNoCheck(Int32 millisecondsTimeout)\r\n   at System.Threading.WaitHandle.WaitOne(TimeSpan timeout, Boolean exitContext)\r\n   at WatsonTcp.WatsonTcpClient.Connect()",
  "RemoteStackTraceString": null,
  "RemoteStackIndex": 0,
  "ExceptionMethod": null,
  "HResult": -2146232798,
  "Source": "System.Private.CoreLib",
  "WatsonBuckets": null,
  "ObjectName": "SafeHandle"
}`

Code to reproduce this error:
`
// See https://aka.ms/new-console-template for more information

using WatsonTcp;

var s = new WatsonTcpServer(null, 25000);
s.Events.MessageReceived += (sender, received_args) => { global::System.Console.WriteLine("Message Received"); };
s.Callbacks.SyncRequestReceived = (request) => { global::System.Console.WriteLine("SyncRequestReceived"); return new SyncResponse(request, DateTime.Now.ToString()); };

s.Start();

while (true)
{
    var c = new WatsonTcpClient("127.0.0.1", 25000);
    c.Events.MessageReceived += (s, received_args) => { global::System.Console.WriteLine("Message received"); };
    c.Settings.DebugMessages = true;
    c.Settings.Logger += (s, m) => { global::System.Console.WriteLine(m); };
    c.Connect();
    var response = c.SendAndWait(5000, new byte[] { 1, 2, 3 });
    Console.ReadLine();
}
`

I'm using .Net 6 and the latest WastonTcp version via NuGet 4.8.14.6

Regards

**Comment by jchristn** [comment]
Hi @ahubertus44 I can't seem to reproduce this using your code (see https://gist.github.com/jchristn/8ebd9b8c3449890a07320362e56ebf4f)

I'm getting the expected output after each press of the ENTER key.

```
C:\Code\Watson\WatsonTcpTest\WatsonTcpTest\bin\Debug\net6.0>watsontcptest
[WatsonTcpClient] connecting to 127.0.0.1:25000
[WatsonTcpClient] connected to 127.0.0.1:25000
SyncRequestReceived
[WatsonMessage] found header demarcation
[WatsonMessage] header processing complete
{"s":"Normal","sresp":true,"exp":"2022-01-06T12:30:49.6672638-08:00","guid":"5ee8fb4b-e207-439a-8f84-5874b07df49b","len":20,"md":{}}

[WatsonTcpClient] connecting to 127.0.0.1:25000
[WatsonTcpClient] connected to 127.0.0.1:25000
SyncRequestReceived
[WatsonMessage] found header demarcation
[WatsonMessage] header processing complete
{"s":"Normal","sresp":true,"exp":"2022-01-06T12:31:05.3254699-08:00","guid":"0939ad62-3969-43ba-b086-10e1844d1c43","len":20,"md":{}}

[WatsonTcpClient] connecting to 127.0.0.1:25000
[WatsonTcpClient] connected to 127.0.0.1:25000
SyncRequestReceived
[WatsonMessage] found header demarcation
[WatsonMessage] header processing complete
{"s":"Normal","sresp":true,"exp":"2022-01-06T12:31:05.8999038-08:00","guid":"c05d6783-8df9-4ee3-91b7-82ae49a82bde","len":20,"md":{}}
```

What operating system are you using?  I tested on Windows 11 w/ .NET 6.0 and WatsonTcp 4.8.14.6.

![image](https://user-images.githubusercontent.com/1421081/148447857-dea78e6c-873c-47c0-bc90-8f4bcee54d89.png)

**Comment by ahubertus44** [comment]
Hi @jchristn, thank you for your fast response.

Weird maybe it's a Windows Bug. I'm using Windows 10 here and the exact same version as stated above in your post.
I removed the Console.ReadLine() from the while loop and it seem to trigger the issue on my end.

Here is a small gif recording. https://i.imgur.com/N0jBk5R.gif

I don't have access to Windows 11 so I cant test it with that operating system.

**Comment by jchristn** [comment]
Interesting indeed.  I just tested without ```Console.ReadLine``` and it didn't produce the issue.  I have a Windows 10 VM, I'll give it a try.
```
C:\Code\Watson\WatsonTcpTest\WatsonTcpTest\bin\Debug\net6.0>watsontcptest
[WatsonTcpClient] connecting to 127.0.0.1:25000
[WatsonTcpClient] connected to 127.0.0.1:25000
SyncRequestReceived
[WatsonMessage] found header demarcation
[WatsonMessage] header processing complete
{"s":"Normal","sresp":true,"exp":"2022-01-06T14:19:25.151393-08:00","guid":"275f4953-c572-4a5f-b37b-f3adf06d102a","len":19,"md":{}}
[WatsonTcpClient] connecting to 127.0.0.1:25000
[WatsonTcpClient] connected to 127.0.0.1:25000
SyncRequestReceived
[WatsonMessage] found header demarcation
[WatsonMessage] header processing complete
{"s":"Normal","sresp":true,"exp":"2022-01-06T14:19:25.3031907-08:00","guid":"00383fbc-9720-4edf-bd9f-ed988d1cc335","len":19,"md":{}}
[WatsonTcpClient] connecting to 127.0.0.1:25000
[WatsonTcpClient] connected to 127.0.0.1:25000
SyncRequestReceived
[WatsonMessage] found header demarcation
[WatsonMessage] header processing complete
{"s":"Normal","sresp":true,"exp":"2022-01-06T14:19:25.364726-08:00","guid":"00dc8d39-f35a-4281-95e1-5f718a157bda","len":19,"md":{}}
[WatsonTcpClient] connecting to 127.0.0.1:25000
[WatsonTcpClient] connected to 127.0.0.1:25000
SyncRequestReceived
```

**Comment by ahubertus44** [comment]
Alright, let me know the results.
I'm updating VS2022 aswell as Net 6 SDK/Runtime right now and will retest it didn't update it for quite a while.

**Comment by jchristn** [comment]
I was able to reproduce in Windows 10.
```
Z:\Code\WatsonTcpTest\WatsonTcpTest\bin\Debug\net6.0>watsontcptest
[WatsonTcpClient] connecting to 127.0.0.1:25000
[WatsonTcpClient] connected to 127.0.0.1:25000
SyncRequestReceived
[WatsonMessage] found header demarcation
[WatsonMessage] header processing complete
{"s":"Normal","sresp":true,"exp":"2022-01-06T14:28:41.881101-08:00","guid":"f61200e7-3d31-4711-b123-dd1ea964bf61","len":19,"md":{}}
[WatsonTcpClient] connecting to 127.0.0.1:25000
[WatsonTcpClient] connected to 127.0.0.1:25000
SyncRequestReceived
[WatsonMessage] found header demarcation
[WatsonMessage] header processing complete
{"s":"Normal","sresp":true,"exp":"2022-01-06T14:28:43.4520292-08:00","guid":"2f2ba3e6-d94a-448a-becd-ba9c4cba14e3","len":19,"md":{}}
[WatsonTcpClient] connecting to 127.0.0.1:25000
[WatsonTcpClient] connected to 127.0.0.1:25000
SyncRequestReceived
[WatsonMessage] found header demarcation
[WatsonMessage] header processing complete
{"s":"Normal","sresp":true,"exp":"2022-01-06T14:28:43.5137867-08:00","guid":"56b39a77-b974-4ec9-86fb-7104a34dce19","len":19,"md":{}}
[WatsonTcpClient] connecting to 127.0.0.1:25000
[WatsonTcpClient] exception encountered:
{
  "ClassName": "System.ObjectDisposedException",
  "Message": "Safe handle has been closed.",
  "Data": null,
  "InnerException": null,
  "HelpURL": null,
  "StackTraceString": "   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)\r\n   at System.Threading.WaitHandle.WaitOneNoCheck(Int32 millisecondsTimeout)\r\n   at System.Threading.WaitHandle.WaitOne(TimeSpan timeout, Boolean exitContext)\r\n   at WatsonTcp.WatsonTcpClient.Connect()",
  "RemoteStackTraceString": null,
  "RemoteStackIndex": 0,
  "ExceptionMethod": null,
  "HResult": -2146232798,
  "Source": "System.Private.CoreLib",
  "WatsonBuckets": null,
  "ObjectName": "SafeHandle"
}
System.ObjectDisposedException: Safe handle has been closed.
Object name: 'SafeHandle'.
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at System.Threading.WaitHandle.WaitOneNoCheck(Int32 millisecondsTimeout)
   at System.Threading.WaitHandle.WaitOne(TimeSpan timeout, Boolean exitContext)
   at WatsonTcp.WatsonTcpClient.Connect()
   at WatsonTcpTest.Program.Main(String[] args) in Z:\code\WatsonTcpTest\WatsonTcpTest\Program.cs:line 44
```

I'm not sure exactly where in ```Connect()``` this is happening.  I will do my best to investigate.  I've been bitten a few times by these subtle platform-dependent differences between .NET 5 and .NET 6.

**Comment by ahubertus44** [comment]
Ok perfect. Seem to be a Windows 10 Issue then. Atleast you were able to reproduce the bug.
I'm certain that the WaitHandle.WaitOne is causing this issue, but that's beyond my point of knowledge. Sorry.

**Comment by jchristn** [comment]
Agreed, it's just not within a using block so I don't know how it would be getting disposed.  Originally I thought it had something to do with hiding variable ```s``` in your ```c.Events``` and ```c.Settings``` since you used it for the server, but that shouldn't be doing it.

**Comment by jchristn** [comment]
I have a fix thanks to a comment by the wizard @StephenCleary: https://social.msdn.microsoft.com/Forums/en-US/313cf28c-2a6d-498e-8188-7a0639dbd552/tcpclientbeginconnect-issue?forum=netfxnetcom

I will have an update in NuGet in moments.

**Comment by jchristn** [comment]
@ahubertus44 please let me know if this fixes the issue.  It fixed it for me on Windows 10, .NET 6.

NuGet: https://www.nuget.org/packages/WatsonTcp/4.8.14.7
Commit: https://github.com/jchristn/WatsonTcp/commit/20324a8b77ebe3279a2414020fc257c94025d054

**Comment by ahubertus44** [comment]
The issue has been resolved with the latest nuget update. 
I appreciate your fast and hard work on that project :)
Do you accept Crypto (Prefered BTC) as a donation? If yes just drop your wallet.

**Comment by jchristn** [comment]
Wow, thank you @ahubertus44!  My receive address is: 3HRgnvEWQBDdWDp75CFDsz3PirCYmftDwU
Much appreciated!

**Comment by jchristn** [comment]
@ahubertus44 dude - *thank you*.  Very generous, I really appreciate it!
