### ISSUE TITLE
Unable to disconnect while stream is pending

### ISSUE THREAD

**Issue by Niproblema** [jchristn/WatsonTcp#188]
SendAsync runs until other peer reads the whole stream. This tends to be problematic, since, what if the other peer does not care about the whole stream? What to do then? Is there anyway to close stream, so that the sender receives `true` from `SendAsync()` ?

Also calling disconnect from client, while SendAsync stream is pending, does not work. It's just stuck there. In case server peer does not fully read the stream, that means deadlock for the client.

**Comment by jchristn** [comment]
Hi @Niproblema the reason it blocks is because it queues a message to send to the server indicating that the socket is being shut down.  I'll amend this to provide a means of non-gracefully disconnecting by bypassing sending this message.

**Comment by jchristn** [comment]
Please let me know if this resolves the issue.  On the client side you can call ```Disconnect(false)``` and it will bypass queuing the disconnect message.  

NuGet: https://www.nuget.org/packages/WatsonTcp/4.8.14.9
Commit: https://github.com/jchristn/WatsonTcp/commit/f06e05142234a1b9bb27416997e525e1aee3d68b

**Comment by Niproblema** [comment]
Hi @jchristn I checked your solution and while client side it works, server side receives no notification that client has disconnected.   I understand why this is the case, but it also makes it impossible for server to track how many clients there really are connected..

By the way, do you have a suggestion for 

> SendAsync runs until other peer reads the whole stream. This tends to be problematic, since, what if the other peer does not care about the whole stream? What to do then? Is there anyway to close stream, so that the sender receives true from SendAsync()

**Comment by jchristn** [comment]
Hi @Niproblema sorry for the delay.  To make sure I understand the problem, are you implying that you want to:

1) Client sends a message with a very large stream
2) Server starts receiving
3) During the receive, a disconnect operation is performed against the client

Please let me know if I have it right.

**Comment by jchristn** [comment]
Closing as abandoned.
