### ISSUE TITLE
TcpClient throws an exception on Windows Server 2016

### ISSUE THREAD

**Issue by MojoDK** [jchristn/WatsonTcp#192]
In WatsonTcpClient.cs under "#if NETCOREAPP || NET5_0", this line throws an exception on Windows Server 2016:

 _Client.Client.SetSocketOption(SocketOptionLevel.Tcp, SocketOptionName.TcpKeepAliveRetryCount, _Keepalive.TcpKeepAliveRetryCount);

Exception:
"An unknown, invalid, or unsupported option or level was specified in a getsockopt or setsockopt call."

It doesn't seam that "SocketOptionName.TcpKeepAliveRetryCount" is supported on Windows Server 2016.

**Comment by jchristn** [comment]
Thanks @MojoDK - certain platforms do and certain platforms don't support keepalives.  It's really, really inconsistent, and something that happens under the library.  The best advice I can give is to disable them when you encounter this issue.  In my experience they are often more of a headache than a value-add in most cases.
