### ISSUE TITLE
Can't we use WatsonTcp to communicate with normal tcp servers? 

### ISSUE THREAD

**Issue by pendingtask** [jchristn/WatsonTcp#196]
Every time I  use `myWatsonTcpClientInstance.SendAndWait` send any data( byte[] ) to a normal tcp server ( a native C# tcp server `Socket` or any tcp debug software), whenever the server replies, the `myWatsonTcpClientInstance.Events.ServerDisconnected` will be triggered before i get any response (actually i wont get anything cause the connection was closed and an exception will be throwed). 
But if the server side was an implementation of `WatsonTcpServer` and `WatsonTcpServer.SyncRequestReceived` was settled to reply the client side request, every thing works fine...
So, can't we use WatsonTcp to communicate with normal tcp servers? 
thank you for your reply

**Comment by jchristn** [comment]
You cannot.  Please refer to the README:
![image](https://user-images.githubusercontent.com/1421081/170263834-d0ca3bbd-e2da-4d36-98e6-b94548fd8635.png)

I do have two other libraries that you can use, which don't provide framing.  [SuperSimpleTcp](https://github.com/jchristn/supersimpletcp) has a similar implementation to WatsonTcp.  [CavemanTcp](https://github.com/jchristn/cavemantcp) has a different implementation with more granular control.

Cheers, Joel

**Comment by pendingtask** [comment]
thank you for your reply and sorry for that
