### ISSUE TITLE
PermittedIPs wrong query

### ISSUE THREAD

**Issue by Jyck** [jchristn/WatsonTcp#197]
WatsonTcpServer.cs Line 770
[link](https://github.com/jchristn/WatsonTcp/blob/1b9c2309db4d8d40d5492d8b85266f1316dc80d4/WatsonTcp/WatsonTcpServer.cs#:~:text=%3E%200%20%26%26-,!,-_Settings.PermittedIPs)

` if (_Settings.PermittedIPs.Count > 0 && !_Settings.PermittedIPs.Contains(clientIp))`
to
` if (_Settings.PermittedIPs.Count > 0 && _Settings.PermittedIPs.Contains(clientIp))`

**Comment by jchristn** [comment]
Hi @Jyck 

The intent is to only permit IP addresses contained in ```PermittedIPs```.

Removing the ```!``` would then close the connection on anything permitted via inclusion in ```PermittedIPs```.

Am I missing something?

Cheers
Joel
```
                    if (_Settings.PermittedIPs.Count > 0 && !_Settings.PermittedIPs.Contains(clientIp))
                    {
                        _Settings.Logger?.Invoke(Severity.Info, _Header + "rejecting connection from " + clientIp + " (not permitted)");
                        tcpClient.Close();
                        continue;
                    }
```

**Comment by Jyck** [comment]
Oh it seems i had a translation error. I expected PermittedIps as blocked
ips.

Joel Christner ***@***.***> schrieb am Fr., 27. Mai 2022,
20:55:
