### ISSUE TITLE
Busy wait loop uses excessive CPU when sending / receiving bytes.

### ISSUE THREAD

**Issue by brudo** [jchristn/WatsonTcp#2]
I tried to implement WatsonCluster in one of our applications. It worked fine to detect whether the cluster was healthy or not, indicating the firewall is configured properly. However, a message sent from one instance did not arrive on the partner instance, and I noticed the CPU got pegged at 100% on the partner machine. I believe this may be due to a busy wait loop using Sleep() in WatsonTcp, in DataReceiver / MessageRead, which may be causing threads to block and eventually exhausting the thread pool.

Can this be changed to use Task.Delay rather than Thread.Sleep to prevent blocking threads, or better yet read the message and/or wait for data availability asynchronously?

**Comment by jchristn** [comment]
Hi @brudo - thanks for submitting this.  I'll take a look in the next day.  Please also feel free to submit a pull request that I can merge if it's something you've changed already.  Else I'll let you know ASAP.  Thanks again!

**Comment by jchristn** [comment]
@brudo looks like Task.Delay was simple enough, I'll commit a fix right now for WatsonTcp and update WatsonCluster for it.  Should be ready on both Github and NuGet in about 15 minutes.  Please re-open if the issue isn't resolved!

**Comment by jchristn** [comment]
I updated WatsonTcp and via the testclient/testserver verified that the CPU utilization is reduced by use of Task.Delay (thank you for that suggestion!).  I updated NuGet, and updated the NuGet reference in WatsonCluster and it seems that it still has a CPU utilization issue.  I'll have to see if I can find someone with a license of ANTS to track this one down (mine expired) or just get a license myself, unless you happen to have one?

**Comment by brudo** [comment]
I do not have ANTS. Happy to help troubleshoot this issue in WatsonTcp and continue using it if we get it resolved.

**Comment by jchristn** [comment]
Hi @brudo I just purchased a license and will get it tested and report back soon.

**Comment by brudo** [comment]
OK thank you. Meanwhile I reviewed the change in GitHub. If you do use use Task.Delay you need to await the result. The difference between this and sleep is it does not tie up the thread. But to use await, you need to make the method async, which changes the signature.

**Comment by jchristn** [comment]
Thanks - I updated to use .Wait() and also tried with new System.Threading.ManualResetEvent(false).WaitOne(n);.  It seems the CPU issue is actually with the continual call to .IsConnected() which simply returns a bool (per ANTSPP).  I'll be checking back into this after I get back from a dinner event this evening.

**Comment by jchristn** [comment]
Hi @brudo I just pushed a new version to github and to NuGet for WatsonCluster, could you please let me know if this addresses the issue for you?  Thanks!

**Comment by brudo** [comment]
Hi @jchristn thanks for the quick response on this. Was there a commit intended for WatsonTcp as well (to use Wait?) Since the issue causing the high CPU usage was in WatsonCluster, I think it would actually be good to revert WatsonTcp to the prior version 1.0.4 that used Sleep().

From reviewing the code, broader changes would be required in both the client and the server to make this library completely async / await friendly, and only then would Task.Delay bring a significant benefit over repeated short-interval Thread.Sleep, considering this was not the source of the CPU issue after all.

**Comment by jchristn** [comment]
Hi @brudo yes there was a commit to WatsonTcp (https://github.com/jchristn/WatsonTcp/commit/22cc02f375508246897d290ff6628f0b65677698) as well, and a NuGet update (https://www.nuget.org/packages/WatsonTcp/).  Agree that a broader change is needed.  I tested functionality and measured CPU using Task Manager and ANTSPP and it seems to be working well now.  I'll keep the Task.Delay Wait in place for now since it is working and plan a broader set of changes for the future.  Thanks for bringing this issue up!
