### ISSUE TITLE
Cant connect to it if not using localhost

### ISSUE THREAD

**Issue by devingDev** [jchristn/WatsonTcp#213]
Hi if I try connecting via 127.0.0.1 (and listening on it) it works
but if i try for example the local ip (192.....) it just doesnt work and say refused connection

Any idea what i can do? I'm not even testing it over the internet just locally

**Comment by jchristn** [comment]
Hi did you go through the steps in the README?

**Comment by jchristn** [comment]
Please re-open if amending the firewall doesn't address the issue.  Screenshot from the README.

![image](https://user-images.githubusercontent.com/1421081/187750802-faf1a686-1d92-464a-9609-fc2d9bd7036c.png)
