### ISSUE TITLE
Connect timeout limit

### ISSUE THREAD

**Issue by 0x100001** [jchristn/WatsonTcp#215]
Hey there,

I got a question. In rare situations it takes up to ten seconds to connect to a server socket and because of that it results in a timeout exception. Is there a way to increase the timeout limit?

Error: Timeout connecting to WIN-Q6JGERFITLF:7000
(tested the socket using a portscan. It just takes a while to connect to the system itself in rare cases)

Thank you!

**Comment by jchristn** [comment]
Hi @0x100001 I'm assuming (hoping) you found the ```Settings.ConnectTimeoutSeconds``` property on the client :)  Cheers!

**Comment by 0x100001** [comment]
Hey @jchristn yes I found out. Somehow I didn't see it on first look. 👀

Thank you!
