### ISSUE TITLE
Incorrect WatsonTcpServer.ListClients summary after v5 update

### ISSUE THREAD

**Issue by Laiteux** [jchristn/WatsonTcp#219]
It's nothing much, but it's still something I noticed.

![c7OMemLd5g](https://user-images.githubusercontent.com/33204743/203443154-0a2140a9-6003-4b4c-a583-18997fc873e2.png)

This method does not return IP:ports anymore, hence why the incorrect summary.

**Comment by jchristn** [comment]
Excellent catch, fixing now, thank you!

**Comment by jchristn** [comment]
NuGet v5.0.2: https://www.nuget.org/packages/WatsonTcp/5.0.2
Commit: https://github.com/jchristn/WatsonTcp/commit/2b8893e049ccb5e52473b5a597aebf6e8e130ab7

Please keep them coming!  And have a nice Thanksgiving.  Cheers
