### ISSUE TITLE
SendAndWait does not work anymore after v5 update

### ISSUE THREAD

**Issue by Laiteux** [jchristn/WatsonTcp#221]
Oops.. Were all tests ran before publishing the update? 😝 

Title says it all: `SendAndWait` does not work anymore after v5 update.

The exact same code below will work just fine on the latest v4, but will crash starting from v5 (`System.TimeoutException: A response to a synchronous request was not received within the timeout window.`)

In fact, `SyncRequestReceived` is never fired.

```cs
using System.Text;
using WatsonTcp;

using var server = new WatsonTcpServer("0.0.0.0", 1337);
using var client = new WatsonTcpClient("127.0.0.1", 1337);

server.Callbacks.SyncRequestReceived += request =>
{
    Console.WriteLine("server received request: " + Encoding.UTF8.GetString(request.Data));
    
    return new SyncResponse(request, "hello back!");
};

server.Events.MessageReceived += (_, _) => { };
client.Events.MessageReceived += (_, _) => { };

server.Start();
client.Connect();

var response = client.SendAndWait(1000, "hello!");

Console.WriteLine("client received response: " + Encoding.UTF8.GetString(response.Data));
Console.ReadKey(true);
```

**Comment by jchristn** [comment]
Thanks @Laiteux I did indeed explicitly test SendAndWait but will revisit again when I get back to a computer. Thanks for finding these!

**Comment by Laiteux** [comment]
![rider64_G5dhx5soH5](https://user-images.githubusercontent.com/33204743/203459765-36d12b7d-49bd-4ae6-b68b-78bb02cf1441.gif)

**Comment by jchristn** [comment]
This is really strange, I literally can't reproduce it.  

![image](https://user-images.githubusercontent.com/1421081/203474212-76c0dc01-84ad-41d0-8726-bba557dbeede.png)

Only thing I notice is you are listening on ```0.0.0.0``` which might require administrator privileges, but based on the video you uploaded, that doesn't appear to be an issue at all.

I added some minor formatting to your code, and changed to ```127.0.0.1```, and it worked with v5.0.2.

```csharp
using System;
using System.Text;
using WatsonTcp;

namespace WatsonTcpTest
{
    class Program
    {
        static void Main(string[] args)
        {
            using (var server = new WatsonTcpServer("127.0.0.1", 1337))
            {
                using (var client = new WatsonTcpClient("127.0.0.1", 1337))
                {
                    server.Callbacks.SyncRequestReceived += request =>
                    {
                        Console.WriteLine("server received request: " + Encoding.UTF8.GetString(request.Data));

                        return new SyncResponse(request, "hello back!");
                    };

                    server.Events.MessageReceived += (_, _) => { };
                    client.Events.MessageReceived += (_, _) => { };

                    server.Start();
                    client.Connect();

                    var response = client.SendAndWait(1000, "hello!");

                    Console.WriteLine("client received response: " + Encoding.UTF8.GetString(response.Data));
                    Console.ReadKey(true);
                }
            }
        } 
    }
}
```

**Comment by jchristn** [comment]
And I just tested on .NET 5.0 and .NET 6.0, no issues :(

**Comment by Laiteux** [comment]
Thanks for getting back to me!

Just ran some tests, and it still won't work even with `127.0.0.1` as the server IP.

No luck with .NET 5.0 or 6.0 either, so it doesn't specifically seem to be a .NET 7 issue.

Copy pasted your code (even though it's basically the same) and that... didn't work either 😕 

Very confused considering it seems to work for you. Once again though, I can confirm everything works just fine when I switch back to latest v4.

**Comment by Laiteux** [comment]
Just sent a compiled executable to a few of my friends, and they all got the exact same issue. I made sure to set the callback timeout to 3000 ms in order to eliminate any doubt regarding it. 🤔

![Telegram_vxfLOuOEBG](https://user-images.githubusercontent.com/33204743/203569451-c093c7da-ba3a-42d1-87b0-49d65e33bf66.png)

![Telegram_zM30CR2WMb](https://user-images.githubusercontent.com/33204743/203570522-cb793407-dc1d-47d6-a1f9-d9bbe374fd6d.png)

**Comment by jchristn** [comment]
Could you set ```Settings.Logger``` to ```Console.WriteLine``` on both client and server, and try again?

The reason for this is to see the ```ConversationGuid``` values in the exchange, like this (in this example the client initiated the ```SendAndWait```):

Server:
```
[Debug    ] [WatsonTcpServer] [947fe83a-22b1-4b82-bcf0-6c83f1e4eb96|127.0.0.1:51564] synchronous request received: 0fb9e3a8-04b4-40d3-9f01-35fef2f43460
Synchronous request received from [947fe83a-22b1-4b82-bcf0-6c83f1e4eb96|127.0.0.1:51564]: hello
```

Client:
```
[Debug    ] [WatsonTcpClient] synchronous response received: 0fb9e3a8-04b4-40d3-9f01-35fef2f43460
```

**Comment by Laiteux** [comment]
Absolutely.

Here is what comes out:

```
[19:27:22.8345761] [WatsonTcpServer] starting on 0.0.0.0:1337
[19:27:22.8397292] [WatsonTcpClient] connecting to 127.0.0.1:1337
[19:27:22.8421142] [WatsonTcpClient] connected to 127.0.0.1:1337
[19:27:22.8441539] [WatsonTcpServer] accepted connection from [c56364f1-8fca-434b-9138-f7ff4fbaba06|127.0.0.1:61302]
[19:27:22.8457543] [WatsonTcpServer] starting data receiver for [c56364f1-8fca-434b-9138-f7ff4fbaba06|127.0.0.1:61302]
[19:27:22.8843577] [WatsonTcpServer] [c56364f1-8fca-434b-9138-f7ff4fbaba06|127.0.0.1:61302] synchronous request received: 704d528b-cd08-4f7b-bd28-7c730b3b897a
[19:27:22.8856877] [WatsonTcpServer] expired synchronous request received and discarded from [c56364f1-8fca-434b-9138-f7ff4fbaba06|127.0.0.1:61302]
[19:27:23.8905162] [WatsonTcpClient] synchronous response not received within the timeout window
```

It seems like the SyncRequest is being discarded right away. 😮

**Comment by jchristn** [comment]
Thanks, I appreciate it.  Good news is the conversation GUIDs are what are expected.  It seems the issue is with UTC.  I just published v5.0.3 where everything is forced to ```DateTime.UtcNow``` or ```.ToUniversalTime()```.  Could you give it a try with that version?

**Comment by Laiteux** [comment]
And it works! Thanks a bunch (:

**Comment by jchristn** [comment]
Excellent!  Great to hear!  Thanks for all of your help identifying these issues and remediating them.  Let's move back to the state machine discussion.
