### ISSUE TITLE
Support for .NET Core, .NET Standard and other

### ISSUE THREAD

**Issue by TheAifam5** [jchristn/WatsonTcp#23]
Hey,
I tested your library - is perfect and I love it (on .NET Core)
Because I am on work PC, i can't make a pull request for you :(

Would be nice to add other framework support.

Regards,
TheAifam5

**Comment by jchristn** [comment]
Hi @TheAifam5 not sure why I didn't get a notification on this, but thank you for your comments!  Which other frameworks would you like it to support?
