### ISSUE TITLE
How to stop the server?

### ISSUE THREAD

**Issue by diskshared** [jchristn/WatsonTcp#24]
hey. In my opinion, the Dispose method should
1) Disconnect all clients
2) Close the TcpListener

but it's not like that

**Comment by jchristn** [comment]
Hi @diskshared I amended the Dispose method on the server to call Dispose on each of the connected clients.  I'll update NuGet as well.  On the earlier question, are you submitting data via telnet using the appropriate framing, i.e. instead of sending "Hello" are yo sending "5:Hello"?

**Comment by jchristn** [comment]
https://github.com/jchristn/WatsonTcp/commit/52de1d4641ec03ab90c80075165979650afd68b7

**Comment by diskshared** [comment]
Thanks for the quick response)
All customers are disconnected, it's good.
What about TcpListener?

You bind the address 
`_Listener = new TcpListener (_ListenerIpAddress, _ListenerPort);`

After the end of the server, it must be freed
`_Listener.Close ();`


About telnet, I realized what was my mistake when I looked at the server code more carefully)

**Comment by jchristn** [comment]
Good call, fixed!  https://github.com/jchristn/WatsonTcp/commit/9a6e87c97fc7569f73cd561268a2d024d37eeeee
