### ISSUE TITLE
Precious exceptions, silently ignored :-(

### ISSUE THREAD

**Issue by YorVeX** [jchristn/WatsonTcp#241]
I am currently trying to use WatsonTcp in .NET 7.0 with NativeAOT. Using the sample code the connection between client and server can be established just fine and is logged on both sides, but as soon as either the client or the server try to send a message they get disconnected.

I was already afraid this might not work right out of the box, but my bigger issue was that I was left with no leads to follow. DebugMessages = true, a logger method in place as well as an ExceptionEncountered event handler but all I get in the log as soon as the client tries to send the message is: "We got disconnected."

Instead of using the NuGet binary I threw the WatsonTcp source files into my folder, spammed all of them with "#nullable disable" (didn't want to disable it globally in my project) and saw pretty quickly why I am not getting any information from anywhere:

![image](https://user-images.githubusercontent.com/528974/223516424-323ff8e4-2cc0-44b8-b9e9-31954bfb7e47.png)

Wait, what? We have a very nice try..catch block, a well-thought-out exception handling, logging and debugging concept, a "finally" handler...all this to then just silently ignore half of the exceptions 😆 

If exceptions are really supposed to be suppressed, there should at least be a comment explaining exactly why it is a good idea (my experience: it very very rarely is, and forcing myself to explain exception suppressions usually makes this obvious). Otherwise why not just use the wonderful exception handling mechanics that this project has?

**Comment by YorVeX** [comment]
This issue is really only about the exception handling, but in case you're curious:

After commenting the exception suppression code I got this from the client:
`System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..`

This way I knew it's the server disconnecting my client.

Next after I commented the same blocks on the server now I get:
`Error: [WatsonTcpServer] data receiver exception for [1fa97f64-2cfd-4e7f-ae49-78f543461fad|127.0.0.1:54481]: Null header data indicates peer disconnected.
`

Don't know yet what to make of this but at least I got a lead to follow now.

**Comment by jchristn** [comment]
Hi @YorVeX the intent is to catch any variant of exception that indicates that a client disconnected, and exit the data receiver loop (which frees resources).  The general exception case is for identifying exceptions of an unknown type that may also indicate a disconnection or other event that should be handled.

Please help me understand the gap here on what the library should vs should not do related to disconnection/exception handling.  Looking forward to your input, and I'm 100% happy to amend the library accordingly.

**Comment by jchristn** [comment]
Oops, didn't mean to close, my bad!

**Comment by YorVeX** [comment]
> Hi @YorVeX the intent is to catch any variant of exception that indicates that a client disconnected, and exit the data receiver loop (which frees resources).

That intent would be totally satisfied by the exception handling block that you already have and that invokes the ExceptionEncountered event and produces a log message:
![image](https://user-images.githubusercontent.com/528974/223570436-759a67b4-bfed-460b-8a42-85ad3ee82913.png)

The question remains why certain exceptions [are not even logged, especially since the code comments on this are as silent as the exceptions when they occur](https://colinmackay.scot/2009/03/05/the-trycatchignore-antipattern-again/).

**I'd say at least have these other catch blocks produce a log message of Debug severity and add a comment why you suppress them.**

This one is a classic: you run into an Exception of a specific type like IOException but the case you have at hand at that moment is actually a quite normal case where you figure it doesn't need further actions in the code (except maybe just exiting the current loop/function/thread/whatever scope) and you suppress any IOException.

Months later when you forgot about this (especially if you didn't put any comments in what situation you think you're suppressing there) and have a situation that produces an IOException for a very different reason that is indeed exceptional and should be treated with extra code.

Until you find this out in worst case you unnecessarily lost lots of time. Now you revert this, but since you didn't comment and don't remember why you originally suppressed it you don't even know what the other case was so that you could tell this case apart from the more relevant one.

When you suppress an Exception type it's basically a statement like "I am sure that nobody will ever need to know about any IOExceptions at all in this scenario, just disconnecting is enough". The problem with this is, that you almost never can be sure if you're being honest, there is just too many potential combinations, configurations and situations out there that are impossible to foresee.

This applies even to cases that seem quite obvious like TaskCanceledException. Sure, maybe it just means a normal cancellation (though [hopefully not](https://enterprisecraftsmanship.com/posts/exceptions-for-flow-control/)), but how do you debug cases (or even find out about this in the first place) where a task is cancelled because of a bug when it shouldn't be?

Or in my case, how exactly was I supposed to find out what's going on in my situation based on the mechanics that are in WatsonTcp meant for debugging (debug log messages and exception events)? Actually then this kind of exception event and logging is even making matters worse, because its existence makes me assume this way I would get all relevant information when in fact I don't.

I hope I could make a bit more clear now what the issue is I see with this.

**Comment by YorVeX** [comment]
I thought it would be fun to ask an AI (GitHub CoPilot) how it would comment on this, but when I started a comment it had no idea at all (which is quite rare already). When I helped it a little by starting with "bad" I got:
![image](https://user-images.githubusercontent.com/528974/223572520-946cd1d8-d642-4731-af67-d29b0cafe7d9.png)

But hey, that's biased, so I tried with "good":
![image](https://user-images.githubusercontent.com/528974/223572730-3c8c9447-8531-4aee-b825-d3ecc497f7e3.png)

😆

**Comment by YorVeX** [comment]
As a side note, the problem is indeed the JSON serialization as I already suspected. Because of trimming in NativeAOT the SerializationHelper.SerializeJson() method returns an empty JSON (so just the "{}") for a serialized WatsonMessage and that eventually leads to "Null header data" being detected, which WatsonTcp misinterprets as a disconnected client instead of a client that just sent an empty message.

To make this work with NativeAOT [a JSON source generator](https://devblogs.microsoft.com/dotnet/try-the-new-system-text-json-source-generator/) would probably have to be used but all of this is new to me too. For myself I rather think I will either build something myself or look into your other project CavemanTcp now, since I mostly need to send lots of raw byte data (video data) anyway. I think it's very nice that you got this full suite of TCP handlers for all sorts of use cases, thanks for your work!

**Comment by jchristn** [comment]
Thanks for all of the feedback, I've added debug statements into the ```DataReceiver``` methods on both client and server, and these will be integrated on the next version submitted to NuGet.  Cheers
