### ISSUE TITLE
Client Disconnection

### ISSUE THREAD

**Issue by zellkennedy** [jchristn/WatsonTcp#25]
Hey! Excellent project. I just want to get a question. Should I create a task to check if a client is still logged in? Given that if I force the client to shut down the server does not detect the disconnect.

**Comment by jchristn** [comment]
Hi @zellkennedy the library should be detecting disconnection almost immediately.  How are you disconnecting the client?  Any info on how to reproduce would be helpful; I've used the manual disconnection method in the test project as well as simple ctrl-c to kill an endpoint.  Thanks

**Comment by zellkennedy** [comment]
A thousand excuses, it was a mistake on my part. As you said actually this check is already being done.

**Comment by jchristn** [comment]
No sweat my friend, thanks for using the library :)
