### ISSUE TITLE
Compatibility with Net Framework 4.6.1 

### ISSUE THREAD

**Issue by Cyberneticocst** [jchristn/WatsonTcp#251]
Compatibility with Net Framework 4.6.1 please for those who have windows 10 2015 that gives them problem

**Comment by jchristn** [comment]
Ask and you shall receive.

NuGet v5.1.2: https://www.nuget.org/packages/WatsonTcp/5.1.2
Commit: https://github.com/jchristn/WatsonTcp/commit/adc499b9e8991c80d43fb3709549ceb695f5102a

**Comment by Cyberneticocst** [comment]
Thank you
