### ISSUE TITLE
KeepAlive not available if SSL is used?

### ISSUE THREAD

**Issue by tovich37** [jchristn/WatsonTcp#259]
Just a question, why aren't the KeepAlive options available when an SSL certificate is used (client)?

Thanks

**Comment by jchristn** [comment]
Why wouldn't they be?  I don't see a reason why that would be the case in the code.  Do you have a snippet that helps reproduce this?  Cheers

**Comment by tovich37** [comment]
Because the method `EnableKeepalives()` is called only when `_Mode == Mode.Tcp` and not when `_Mode == Mode.Ssl` ([line 355](https://github.com/jchristn/WatsonTcp/blob/336623c793c570d56435b231f204f8956c8040c4/src/WatsonTcp/WatsonTcpClient.cs#L355) of WatsonTcpClient.cs ).
With a `X509Certificate2` object, the constructor set the `_Mode` field to `Mode.Ssl` ([line 271](https://github.com/jchristn/WatsonTcp/blob/336623c793c570d56435b231f204f8956c8040c4/src/WatsonTcp/WatsonTcpClient.cs#L271) of WatsonTcpClient.cs)
I do a sample tomorrow with a Wireshark screenshot.
Thanks Joel.

**Comment by jchristn** [comment]
I see it now!  Thanks for letting me know.  I'll get this patched right now!

**Comment by jchristn** [comment]
Fixed, please re-open if any issues.  Again I really appreciate you letting me know!

NuGet: https://www.nuget.org/packages/WatsonTcp/5.1.3
Commit: https://github.com/jchristn/WatsonTcp/commit/dda310124c721ae2afbae5d496477ac583df5de3
