### ISSUE TITLE
How do disconnect from client?

### ISSUE THREAD

**Issue by pmeloy** [jchristn/WatsonTcp#26]
The examples simply quit and looking through the source I couldn't find a disconnect method. How should a client disconnect? I've used client.dispose() which does the job apparently but it doesn't really seem elegant.

**Comment by jchristn** [comment]
Hi @pmeloy - the Dispose method will close the stream (if open), close the socket, and then destroy any background tasks.  Was there another teardown type function that you would want Dispose to do?  Cheers

**Comment by pmeloy** [comment]
Well if dispose() is the official way then I guess that's the way.

**Comment by jchristn** [comment]
Yes - best to encapsulate the client into a using statement or manually call dispose when done. Cheers
