### ISSUE TITLE
Deadlock when sending data from server in MessageReceived handler

### ISSUE THREAD

**Issue by sancheolz** [jchristn/WatsonTcp#263]
I run this code on net 6 on ubuntu 22.04
```cs
using WatsonTcp;

namespace WatsonDeadlock; // Note: actual namespace depends on the project name.
internal class Program
{
    private static byte[] _serverData;
    private static WatsonTcpServer _tcpServer;
    private static bool _all;
    private static int _countReceivedMessages;
    private static Guid _clientGuid;

    static void Main(string[] args)
    {
        var clientData = File.ReadAllBytes("/home/sancheolz/client2834.txt");
        _serverData = File.ReadAllBytes("/home/sancheolz/server3304.txt");
        _tcpServer = new WatsonTcpServer(null, 9956);
        _tcpServer.Events.ClientConnected += OnClientConnected;
        _tcpServer.Events.MessageReceived += OnTcpMessageReceived;
        _tcpServer.Start();

        var _tcpClient = new WatsonTcpClient("localhost", 9956);
        _tcpClient.Events.MessageReceived += OnMessage;
        _tcpClient.Connect();

        Task.Run(() =>
        {
            int i = 0;
            while (i < 1000)
            {
                _tcpClient.Send(clientData);
                i++;
            }
        });

        while (true)
        {
            if (_all)
                break;
            Thread.Sleep(100);
        }

        Console.WriteLine($"_countReceivedMessages {_countReceivedMessages}");
    }

    private static void OnMessage(object sender, MessageReceivedEventArgs e)
    {
        if (Interlocked.Add(ref _countReceivedMessages, 1) > 999) _all = true;
    }

    private static void OnTcpMessageReceived(object sender, MessageReceivedEventArgs e)
    {
        _tcpServer.Send(_clientGuid, _serverData);
    }

    private static void OnClientConnected(object sender, ConnectionEventArgs e)
    {
        _clientGuid = e.Client.Guid;
    }
}
```
[server3304.txt](https://github.com/jchristn/WatsonTcp/files/12123636/server3304.txt)
[client2834.txt](https://github.com/jchristn/WatsonTcp/files/12123637/client2834.txt)

Sometimes this code works to the end, and sometimes it freezes. If you stop the debugger at the moment of hanging, then the _countReceivedMessages variable is equal to the value 854, and if you continue execution, the value does not change.
Perhaps this issue affects this https://github.com/theRainbird/CoreRemoting/issues/44
version of WatsonTCP is 5.1.0

**Comment by sancheolz** [comment]
In test attached at https://github.com/theRainbird/CoreRemoting/issues/44 most of the time is spent on
`msgData = await WatsonCommon.ReadFromStreamAsync(msg.DataStream, msg.ContentLength, bufferLen);`
On my machine, the whole test takes about 120 seconds. And this method takes about 80 seconds.
It looks like a problem with the slow operation of the ReadAsync method of the NetworkStream class on Linux.

**Comment by sancheolz** [comment]
Deadlock is gone when I set `_tcpServer.Settings.NoDelay = true;` and `_tcpClient.Settings.NoDelay = true;`

**Comment by jchristn** [comment]
Hi @sancheolz I'm sorry I haven't had a chance to respond to this.  Thank you for letting me know.  I need to go back and re-evaluate whether or not ```Settings.NoDelay``` should be ```true``` by default.  Since WatsonTcp is framing, I can't think of a good reason why ```NoDelay``` shouldn't be ```true``` by default.  Out of curiosity, how long does the test take after the change?  The issue you mentioned said it was taking 800 seconds.  How is it now?

**Comment by sancheolz** [comment]
```
ubuntu websocket net6 run				Elapsed ms   4 217
ubuntu watsontcp default net6 run			Elapsed ms 887 276
ubuntu watsontcp nodelay = true net6 run		Elapsed ms  12 608

windows websocket net6 run				Elapsed ms   3 715
windows watsontcp default net6 run			Elapsed ms   6 900
windows watsontcp nodelay = true net6 run		Elapsed ms   7 309
```

**Comment by sancheolz** [comment]
Hi @jchristn If you interesting, I've posted issue at dotnet about this https://github.com/dotnet/runtime/issues/90664

**Comment by jchristn** [comment]
Thank you @sancheolz i will update the library tomorrow to change the default behavior!

**Comment by jchristn** [comment]
Here it is.  Thanks again @sancheolz 
NuGet: https://www.nuget.org/packages/WatsonTcp/5.1.7
Commit: https://github.com/jchristn/WatsonTcp/commit/d433347249a17ff0863f423825b23855a4960666
