### ISSUE TITLE
Send metadata with a Non-WatsonTcp Endpoint

### ISSUE THREAD

**Issue by teoAlivanoglou** [jchristn/WatsonTcp#265]
I read through [FRAMING.MD](https://github.com/jchristn/WatsonTcp/blob/master/FRAMING.md) and I can't figure out how to include metadata from my non-WatsonTcp client. 

So far I've tried these two json headers:

`"{"len":1337,"status":"Normal","metadata":{"fileName":"Foobar"}}"`

`"{"len":1337,"status":"Normal","fileName":"Foobar"}"`

In both cases, args.Metadata is not set. Is it even possible?

**Comment by jchristn** [comment]
Hi @teoAlivanoglou please try setting it to ```"md":{...}```.  Looks like it may be a documentation error.

```
        /// <summary>
        /// Metadata dictionary; contains user-supplied metadata.
        /// </summary>
        [JsonPropertyName("md")]  <----
        public Dictionary<string, object> Metadata { get; set; } = null;
```

**Comment by jchristn** [comment]
Just added some more detail to ```FRAMING.md``` - thanks for bringing to my attention! Also please re-open if any issues.

**Comment by teoAlivanoglou** [comment]
Thank you very much!
