### ISSUE TITLE
How to get the ipPort of client 

### ISSUE THREAD

**Issue by BadNiiw** [jchristn/WatsonTcp#28]
Hi,

thanks for this project. It works well.
Only one thing is how can I get the ipPort value of client which send me the message ?
In message received event I only have the data and I dont want to transfer this ipPort in the data[]

**Comment by jchristn** [comment]
Hi @BadNiiw , thank you for your feedback.  In the ```WatsonTcpClient```, the callback ```public Func<byte[], bool> MessageReceived = null;``` always comes from the server.  In the ```WatsonTcpServer```, the callback ```public Func<string, byte[], bool> MessageReceived = null;``` always includes the client's IP:port.  The string value in that method should never be sent to your application as null.

**Comment by jchristn** [comment]
BTW - @BadNiiw - are you looking to have multiple clients connected to the server, and then relay the incoming messages on the server to other clients (like a chat app)?  If so you'd need to encapsulate the sender/recipient information into the data sent to the server anyway.  Cheers

**Comment by jchristn** [comment]
Please reopen if this doesn't address the concern.  Thanks

**Comment by BadNiiw** [comment]
@jchristn Hey, thank you for you replies. What do you think is the best way of encapsulating ? Serialize and Deserialize ?

**Comment by jchristn** [comment]
Hi @BadNiiw - yes I think that's the best approach.  Off the top of my head it would involve:
- a new Message class, containing sender/recipient/data
- encapsulating the client Send methods to create a Message object, serialize, and send
- encapsulating the client MessageReceived methods to deserialize into a Message object
- modifying the server code to automatically send messages to the recipient

If you're building a chat or chat-like app I'd also encourage you to check out [BigQ](https://github.com/bigqio/bigq).  It's MIT licensed, open source, and written in C#.  Cheers

**Comment by BadNiiw** [comment]
@jchristn I'm writing a 2D app which can handle multiple players in real time (for e.g: agar.io) but I'm not sure pub/sub is the best for this. What do you think?

**Comment by jchristn** [comment]
Great question.  It gets hard/unruly if you try to do direct/mesh connections with too many clients.  Pub/sub may be the easiest.  You can also try watsonmesh (which uses watsontcp).  Watsonmesh has a broadcast function which goes to the entire mesh network.  The only issue I think you'll face there is that each client is also a server.  If you're trying to avoid running a server instance on each client, I'd either roll your own broadcast mechanism or use pub/sub (just my $0.02!).  Cheers
