### ISSUE TITLE
Different TargetFrameworks

### ISSUE THREAD

**Issue by MrMikeJJ** [jchristn/WatsonTcp#29]
Hi,
I was looking at this project again, came across an inconsistancy, just wanted to make you aware of it.

All the original projects target
netstandard2.0 and net452

The new test projects - TestServerStream and TestClientStream target
netcoreapp2.2

On a separate note, i have applied a some of the Roslyn, FxCopAnalyzers and StyleCop.Analyzers to my branch of this and a few other things. Can send a pull request if you would like the changes. Have a flick through, lot of commits, all are pretty small.
https://github.com/MrMikeJJ/WatsonTcp/commits/master

8th July did the analysers stuff, 9th July, bits of refactoring. 

thanks
Mike

**Comment by jchristn** [comment]
Thank you @MrMikeJJ - sorry for the delay in getting back to you, I was out of the country.  I will add this to the list and really appreciate your help!  Cheers, Joel

**Comment by jchristn** [comment]
Haven't forgotten about this @MrMikeJJ - just buried on another project that I'm adding some features on, hope to get to these this week.  Cheers

**Comment by MrMikeJJ** [comment]
No worries, hope you had a nice time while you were out of the country. :)
Got a few more changes coming soon as well hopefully :)

**Comment by jchristn** [comment]
Hi @MrMikeJJ I noticed in your PR after I merged into master that in WatsonTcpClient.cs, ```private ClientMetadata _Server``` is never initialized.  Do you see this on your end?

**Comment by jchristn** [comment]
WatsonTcpClient.cs
From your PR: https://github.com/jchristn/WatsonTcp/blob/947eb966e7f78faca41d1edbf2804316c22f45df/WatsonTcp/WatsonTcpClient.cs

From before:
https://github.com/jchristn/WatsonTcp/blob/1b7153fb135ebcaaaea58db85844050e77289be3/WatsonTcp/WatsonTcpClient.cs

It looks like the streams etc were collapsed into ClientMetadata, but ClientMetadata was never initialized.

Out of curiosity did you pull from master (1.3.12) before making these changes or were they made to a previous version?

**Comment by jchristn** [comment]
Sorry for blowing up your email, it looks like this one may not have been included in the PR, because you clearly did initialize it: https://github.com/jchristn/WatsonTcp/commit/eba86a1b90ecdc9a1e997b194dcbadee08dff200

**Comment by MrMikeJJ** [comment]
No worries, sorry for not replying, it nearly midnight and I am drunk from works summer party (with a free bar!). A bit weird how it didn't pull that one in.

Got a few more chages to send through, probably Saturday. While I was looking through, I was thinking I can chuck all the send messages functions into the clientmetadata class, so they aren't duplicated (and virtually identical) between the server and client classes. Did have a few questions on the differences between them, where I not quite sure, and don't want to break anything. Hope you have a good evening 🙂

**Comment by jchristn** [comment]
Haha nice!  Hope you enjoyed the party.  Will wait for the next PR :)  Cheers

**Comment by MrMikeJJ** [comment]
I see my fail now i am sober, line 250 shouldn't have had ClientMetadata at the front of it. (facepalm)

**Comment by jchristn** [comment]
LOL love it.  Would you be willing to send a PR with all of the changes integrated?  Everything looks pretty good, I was going to go through them one by one until I found the missed commit, but there were quite a few small ones and it would have taken forever.  Hope you're having a great weekend!

**Comment by MrMikeJJ** [comment]
Sure, will do. I had an idea I wanted to run past you, just feels strange putting it in a bug report...

So the Server class makes a Watson message, then passes that through all the send functions. The data[] sender converts the data into a memory stream. So I was thinking about making Watson message do that conversion & storing the memory steam. And then read content length and  steam out of the message class so won't need to pass the content length and steam into the final SendMessgage functions, just the client and the message. If that makes sense?

My weekend has been alright thank you, very lazy so far :) Hope you are having a good one too.

**Comment by jchristn** [comment]
Hi @MrMikeJJ any update on this one?  Cheers
