### ISSUE TITLE
Start() is fire and forget?

### ISSUE THREAD

**Issue by pha3z** [jchristn/WatsonTcp#32]
client.Start() is void Fire-and-Forget synchronous style.

What happens if the client throws an exception?  It looks like the exception will not reach the main execution thread.

**Comment by jchristn** [comment]
Hi @pha3z, if there is an exception during ```Start()``` it is caught and thrown (which would make it to the caller).  Is there a different pattern you would recommend? 

```
                try
                {
                    connectSuccess = waitHandle.WaitOne(...)
                    ...
                }
                catch (Exception)
                {
                    throw;
                }
                finally
                {
                    waitHandle.Close();
                }
```

**Comment by pha3z** [comment]
It's hard to say without knowing the internals of the system.  After start is called, what happens? Does it fire a background worker or something?

Can you update your example code to show Start() wrapped in an exception? Right now there isn't any way to know Start() will throw exceptions or what may cause them.

I do *not* consider myself anywhere close to expert on async/await and especially on exception-handling in async systems.  So take what I say with a grain of salt.

I just know that async libraries typically provide async methods for all long-running invocations. One of the advantages is the ability to use cancellation tokens. Another advantage is the ability to surround the method invocation with follow-up logic for what to do after method completion. 

 Something like this:

```
public async Task MyConsumerMethod(CancellationToken token)
{
    await _watsonClient.RunAsync(token)

    //After client stops (either from cancellation request, or server disconnect, or error)
    //Code resumes here.
    //A loop for automatic reconnect can be implemented here or whatever special behavior
    //consumer wants.
}
```

As far as exception handling on async methods....that's not something I have enough experience with.  Here's an article on async exceptions:
https://blogs.msdn.microsoft.com/ptorr/2014/12/10/async-exceptions-in-c/

**Comment by pha3z** [comment]
For what it's worth... I wrap most libraries I use in custom interfaces to abstract them.  This provides a good exercise in comparing the "handlebars" on different libraries.  Here is how I currently implemented the Watson Start method:

`/// <summary>
/// Connects to remote host and begins listening for events
/// </summary>
public async Task ConnectAndRunAsync(CancellationToken ct)
{
    if (_client != null) _client.Dispose();

    _client = new WatsonTcpClient(RemoteIP, RemotePort)
    {
        ServerConnected = ServerConnected,
        ServerDisconnected = ServerDisconnected,
        StreamReceived = StreamReceived,
        Debug = false
    };

    //Author has informed me Start() may throw exceptions.  Need to handle these.
    _logger.Warning("[TCP_CLIENT] Connecting...");
    _client.Start();
    IsRunning = true;
    
    while (!ct.IsCancellationRequested)
    {
        if(!IsRunning)
        {
            if (_autoReconnect)
            {
                _logger.Warning("[TCP_CLIENT] Auto-reconnecting...");
                _client.Start();
                IsRunning = true;
            }
            else
            {
                _client.Dispose();
                _logger.Warning("[TCP_CLIENT] Client stopped running. Client disposed.");
                return;
            }
        }

        await Task.Delay(5000);
    }

    _client.Dispose();
    _logger.Information("[TCP_CLIENT] Cancellation request received. Client stopped and disposed.");

    return;
}`

**Comment by jchristn** [comment]
Hi @pha3z thanks for all of this information.  

On the exceptions side, I allow the underlying TcpClient exceptions to propagate back to the caller.  WatsonTcp doesn't have its own exceptions or anything of that sort.  Typically this results in a SocketException.  In general you shouldn't encounter an ObjectDisposedException, ArgumentNullException, etc, since the constructor and Start method sets up the environment for you (https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.tcpclient.beginconnect?view=netframework-4.8 for the exception list)

Internally WatsonTcp does make use of a cancellation token.  Dispose (or encapsulation within a using block) will use the cancellation token to tear down background tasks (such as the DataReceiver Task).

Would you see value in exposing a constructor that allows you to specify your own cancellation token?  That's definitely doable.  My only concern would be a graceful teardown of everything else (closing the streams, closing the clients) which are handled by Dispose.

Thanks and please let me know if I'm misunderstanding.  Cheers, Joel

**Comment by pha3z** [comment]
I'll contemplate this more when I get a moment. My immediate question is what happens after Start()? It's apparently launching a background worker or something of that sort.

I'm trying to understand the exception implications of this pattern. What happens if an exception occurs after start returns? Is it just swallowed up and lost?

**Comment by jchristn** [comment]
After a successful Start(), exceptions would occur generally only in DataReceiver.  Should an exception be encountered there, the ```ServerDisconnected``` callback would be invoked, and the client would be disposed.  The callback is there to notify the consuming application that the client needs to be reinstantiated and restarted.

**Comment by pha3z** [comment]
Ok, so ServerDisconnected should always be invoked if an exception occurs during execution on an established connection.  That is a very important note.  Would be good to put that in the XML Comment for the library and mention that in the example code.

The expectations of my implementation already match well with the described behavior. Presently, I'm setting an IsRunning flag to false in the ServerDisconnected event.  That acts as a signal in my main loop to handle premature disconnects.

All that being said.... you had asked the following:

> Would you see value in exposing a constructor that allows you to specify your own cancellation token? That's definitely doable.

I think the short answer is yes.  At least for me, Watson's lack of a RunAsync() (or similar name) leaves questions about what proper consumer implementation looks like. This is evidenced by the fact that the current implementation *requires* the consumer to know that long-running exceptions will result in an invocation to ServerDisconnected.

At present, ServerDisconnected is the only way to handle premature disconnects and signal a reaction mechanism. I wouldn't say there is anything wrong with this, but having a RunAsync() method that can be awaited until a disconnect occurs seems more natural in the modern async paradigm.

It would be awesome if we could get someone else's opinion on this though. My opinion is a pretty humble one -- do not consider myself the expert of async. :)  All of this may be a matter of personal taste, really.

-------------------
As a side note, maybe something is wrong with my Nuget installation... but Intellisense doesn't show any comments at all for any of the Watson methods.  Are comments implemented?

**Comment by pha3z** [comment]
Now that I take all this into consideration and re-examine my code, I see there are bugs in the code I posted. 

I made the assumption that I could call Start() on a disconnected client.  That won't always work because the client may have been disposed.  I need to recreate the client to reconnect.

**Comment by pha3z** [comment]
FYI, here is my updated code:

```
public async Task ConnectAndRunAsync(CancellationToken ct)
{
    if (_client != null) _client.Dispose();

    _logger.Information("[TCP_CLIENT] Connecting...");
    _client = GetNewClient();
    _client.Start();

    IsRunning = true;
    
    while (!ct.IsCancellationRequested)
    {
        if(!IsRunning)
        {
            _client.Dispose(); //This call should not be necessary. Doing it for safety.

            _logger.Warning("[TCP_CLIENT] Client stopped running prematurely. Possibly due to a server disconnect.");

            if (_autoReconnect)
            {
                _logger.Information("[TCP_CLIENT] Auto-reconnecting...");
                _client = GetNewClient();
                _client.Start();
                IsRunning = true;
            }
            else
                return;
        }

        await Task.Delay(5000);
    }

    _client.Dispose();
    _logger.Information("[TCP_CLIENT] Cancellation request received. Client stopped and disposed.");

    return;
}
```

**Comment by pha3z** [comment]
After extensive investigation, I think I actually like the Fire-and-Forget style *better* than an Async() approach.  Even though some people argue that Fire-and-Forget is an anti-pattern, using Async for long-running background tasks creates it own problem.

There's a relevant SO discussion on it here:
https://stackoverflow.com/questions/15522900/how-to-safely-call-an-async-method-in-c-sharp-without-await

I never had any intention of wanting to call an async method without await.  But now I understand design problem that arises from async on long-running methods.  Basically since the method would never return, you can't do something useful like launch into a program loop unless you use ugly work-arounds to run Async method in a way that continues immediately (as if you had used await).

I don't see an Async approach being better than the current approach.

**Comment by jchristn** [comment]
Hi @pha3z thank you for all the feedback and comments.

I do have XML comments for the public methods and members, are they not showing up for you?  If not, I need to do something about that straight away (and for the other libraries too!)  When I upload these, I upload NuGet packages containing release builds (not sure if that makes a difference?)

![image](https://user-images.githubusercontent.com/1421081/65081882-7765fc80-d959-11e9-8f1d-0b7a1b7508bb.png)

Thank you for the SO link, I was not aware of it.  I wasn't aware that it was an anti-pattern and had just assumed that I'd be needing to handle the failure cases inside the library with the appropriate callbacks to inform the consuming application of state changes.

I'll keep the idea of providing an interface by which a consuming application can specify their own cancellation token on the backlog as well.

I'll also revisit the documentation to see how I can better clarify what must be considered when integrating WatsonTcp.  Really thankful for your feedback on that.

Please let me know about whether or not the code documentation is showing up on your end.

Cheers, Joel

**Comment by pha3z** [comment]
Quoting Joel:
> I wasn't aware that it was an anti-pattern and had just assumed that I'd be needing to handle the failure cases inside the library with the appropriate callbacks to inform the consuming application of state changes.

Yeah... _some_ people argue its an anti-pattern.  Rather than calling it an anti-pattern outright, it's better to understand _why_ it may be frowned upon:

To quote Stephen Cleary:
> It's very rare to want to execute some code and not care whether it completes and not care whether it completes successfully.

Calling Start() in the current manner *gives the appearance* that it just happens magically and you don't need to care what happens afterward.

For the sake of your library, we do in fact care and we are in-fact handling the failure case, because there are Events to manage those issues -- such as ServerDisconnected() event that will fire on an internal exception.  So you see, the pattern you've created isn't _truly_ fire-and-forget; it only has that appearance depending on how you look at it. :)

Now that I understand the pattern you've created, I actually like it.  It's just imperative that the consumer recognize ServerDisconnected() will fire when internal exceptions happen.

**Comment by pha3z** [comment]
Final thought:  I wouldn't worry too much about changing the way it works.  If nobody is reporting problems and its working, don't fix what ain't broke. :)  Just clarify in the docs how to deal with exceptions/failures. :)

**Comment by jchristn** [comment]
Thanks @pha3z - definitely have this on my list.  Closing this issue.  Please let me know if you find anything that doesn't work to your satisfaction!  Cheers Joel

**Comment by pha3z** [comment]
No problem.  I really appreciate the library. :)  Great work on it!
