### ISSUE TITLE
Bit unclear how to connect from another PC

### ISSUE THREAD

**Issue by mikkleini** [jchristn/WatsonTcp#35]
Hi @jchristn . I have one documentation suggestion. It's not very clear how to setup WatsonTcpServer so it can be connected by external clients (not just localhost clients). For that a null or string.Empty has to be used as listenerIp argument in constructor.
But maybe write it in the examples and add it to the constructor comment?

At least on Linux (RPi) if i use "127.0.0.1" then i can't connect from Windows client.

**Comment by jchristn** [comment]
Hi @mikkleini great suggestion!  How about this for the documentation?
```
        /// <summary>
        /// Initialize the Watson TCP server without SSL.
        /// Supply a specific IP address on which to listen.  Otherwise, use 'null' for the IP address to listen on any IP address.
        /// If you do not specify an IP address, you may have to run WatsonTcp with administrative privileges.  
        /// Call Start() afterward to start the server.
        /// </summary>
        /// <param name="listenerIp">The IP address on which the server should listen.  If null, listen on any IP address (may require administrative privileges).</param>
        /// <param name="listenerPort">The TCP port on which the server should listen.</param>
```

Yes - if you listen on localhost it will only bind to the localhost adapter, and not any other interface (such as Ethernet).  You can also try '0.0.0.0' or '+' or '*' - for Linux, one of those should represent 'any address'.

**Comment by jchristn** [comment]
Also updated the README with this section:
```
### Local vs External Connections

**IMPORTANT**
* If you specify ```127.0.0.1``` as the listener IP address in WatsonTcpServer, it will only be able to accept connections from within the local host.  
* To accept connections from other machines, specify a specific IP address, or, use ```null``` for the listener IP address.
* If you use ```null``` for the IP address, or any variant representing any IP address such as ```0.0.0.0```, ```+```, or ```*```, you may have to run WatsonTcpServer with administrative privileges (this is required by the operating system).
```

NuGet v2.0.7 is processing with the aforementioned constructor documentation change!

**Comment by mikkleini** [comment]
Perfect!
