### ISSUE TITLE
Can you add StartAsync() method 

### ISSUE THREAD

**Issue by csalat** [jchristn/WatsonTcp#36]
Hello Joel!

Can you add StartAsync() method as I would like to use watson from an async environment.
Nowadays, I need to use await Task.Run(()-> WatsonTcp()) ...

for example:
public Task StartAsync()
        {
            if (_Mode == Mode.Tcp)
            {
                Log("Watson TCP server starting on " + _ListenerIp + ":" + _ListenerPort);
            }
            else if (_Mode == Mode.Ssl)
            {
                Log("Watson TCP SSL server starting on " + _ListenerIp + ":" + _ListenerPort);
            }
            else
            {
                throw new ArgumentException("Unknown mode: " + _Mode.ToString());
            }

            return AcceptConnections();
        }

Thanks,
Csaba

**Comment by jchristn** [comment]
Will do @csalat :) stay tuned.

**Comment by jchristn** [comment]
Hi @csalat just pushed v2.0.8 to NuGet, should only take a few minutes: https://www.nuget.org/packages/WatsonTcp/2.0.8

Please re-open let me know if this is not the intended behavior.

Commit can be found here: https://github.com/jchristn/WatsonTcp/commit/2df41a5a28eb2befca694c9b87a5627c3b7e416a

Cheers, Joel

**Comment by csalat** [comment]
thx, it was quick!
