### ISSUE TITLE
Feature request: Disconnect Idle Clients

### ISSUE THREAD

**Issue by pha3z** [jchristn/WatsonTcp#37]
I think this is a standard base-level feature you'd want in any TCP Server.  I'm implementing this in my own abstraction for Watson.  It'd be nice if it was just built-in.

Suggested implementation:
Consumer configures Watson Server with a ClientMaximumIdle time and if no data is received from a client for that period of time, server disconnects the client.

**Comment by pha3z** [comment]
Further notes:
If you decide to implement this, I would suggest using a dictionary of Stopwatches keyed on ipPort string (or whatever construct you're using internally to key your clients).
All you have to do is reset the correct stopwatch each time data is received from a client.
And every couple of second, you can scan the dictionary for clients with a stopwatch.ElapsedMilliseconds that exceed the MaximumIdle time.

**Comment by jchristn** [comment]
Thanks @pha3z will add this one to my list.  If you'd like to submit a PR I'd be happy to review.  Otherwise I'll get on this as I can.  Cheers!  Joel

**Comment by jchristn** [comment]
Hi @pha3z I had a few minutes and decided to knock this out.  Thanks for the excellent suggestion!  Also added a note of thanks to you in the project README.

NuGet: https://www.nuget.org/packages/WatsonTcp/2.1.1

Commit: https://github.com/jchristn/WatsonTcp/commit/7332681338bca5524bba3c53439b3827f0cdc002

Closing this issue, please let me know if you see an issue with the implementation, and please keep the requests coming!

**Comment by jchristn** [comment]
Yes, ClientDisconnected will still fire.

Sending a message resets the timeout because there could be use cases where the communication is largely one-way, i.e. streaming updates to the client without any kind of acknowledgement.

Tell me more about your use case?  I'm open to changing it to only resetting when receiving messages from the client - I just don't want this to be too restrictive.

**Comment by pha3z** [comment]
> Sending a message resets the timeout because there could be use cases where the communication is largely one-way, i.e. streaming updates to the client without any kind of acknowledgement.

If the server doesn't know whether the client is even listening or getting the messages, then why would it make sense to keep sending messages? You could create a scenario where the server is just sending data over the network to nobody on the other end.  Just wasting bandwidth and system resources.

Ensuring that the client is still present is the job of a KeepAlive pattern. The implementor (consumer of Watson) needs to either implement KeepAlive themselves or KeepAlive needs to be added as an optional feature for Watson client.  KeepAlive feature would be a separate issue, but its related to this discussion.

If someone really DOES want to send data over the wire without acknowledging that the listener is present, it doesn't make sense to be using an IdleDisconnect at all. There's no reason to perform automatic disconnect because server is choosing to make zero assumptions about listener status.

Can you provide specific example to counter my claim?

**Comment by jchristn** [comment]
Your point makes sense about not using an idle disconnect if it's largely one way communication.  It makes sense to remove the timeout reset upon send, and only keep it on receive.

On the issue of keepalives, I built it in such a way that disconnects (intended, catastrophic) are detected immediately, meaning you shouldn't need to do keepalives except as a means of acknowledgement.  

I'll amend this now and get an update posted shortly.  Thanks for the lively discussion and the feedback.

**Comment by jchristn** [comment]
Change implemented @pha3z - thanks for the info.

NuGet: https://www.nuget.org/packages/WatsonTcp/2.1.2

Commit: https://github.com/jchristn/WatsonTcp/commit/03aa51b2d1671c5777aae9d73006c8c49407346d

**Comment by pha3z** [comment]
"On the issue of keepalives, I built it in such a way that disconnects (intended, catastrophic) are detected immediately, meaning you shouldn't need to do over-the-top keepalives except as a means of acknowledgement."

I'm not 100% sure I have the same understanding of a KeepAlive as you.

My concept of the simplest KeepAlive is the client periodically sending something to the server just so the server gets some data and knows the client is still there.  It's nothing more than that.  Hence, in the IdleDisconnect we're discussing, the KeepAlive would be the client's way of telling the server "I'm still here; don't disconnect me!"

I know that there is also the concept of a 2-way Keep-Alive that involves an Acknowledgement. For instance, a server that hasn't heard anything from a client for a while might send a message saying "Hey are you still there?" and the client needs to send back "Yes I'm here." to avoid being disconnected.  But it could also be initiated by the client so that the client can know that the server is still there. Neither way is right or wrong.

What did you have in mind?

**Comment by jchristn** [comment]
We're on the same page.  A keepalive would be the client periodically saying 'hello' (or similar) to notify the server that it is still there.  A heartbeat of sorts.  Not planning to add over-the-top keepalives into Watson directly though, since my design goal is to avoid having to use them.  Cheers

**Comment by pha3z** [comment]
Ok, cool.  Thanks for the great work! :D
