### ISSUE TITLE
Handlebars Request:  Remove "ReadDataStream"

### ISSUE THREAD

**Issue by pha3z** [jchristn/WatsonTcp#38]
It would be very nice to remove ReadDataStream as public property.
Let the consumer just set StreamReceived or MessageReceived events.

In the setter for the events, you can change whatever field is represented by ReadDataStream so the internal operation remains the same.

Also, if you want to only allow StreamReceived and MessageReceived events to be used mutually exclusively, you can handle that in the setter as well.
Have a flag indicating whether either one of the setters has been called.
When a setter gets called, if the flag already says one setter was called, throw an WatsonConfigurationException (Or whatever exception name you're using for watson exceptions) with a message explaining that only one of the events can be set.

Simplifies configuration.  Would have saved me 10 minutes of troubleshooting.  It's a footgun.

**Comment by jchristn** [comment]
I agree, this is an area where the library can be simplified.  Working on these issues now.  Thanks for the feedback.

**Comment by jchristn** [comment]
Fixed in v2.1.0.

NuGet: https://www.nuget.org/packages/WatsonTcp/2.1.0

Commit: https://github.com/jchristn/WatsonTcp/commit/4000e15b3f8383401f11fe819ba5afa005366170
