### ISSUE TITLE
MessageReceived and StreamReceived share the same Comment

### ISSUE THREAD

**Issue by pha3z** [jchristn/WatsonTcp#39]
StreamReceived says "Method to call when a message is received..."
The MessageReceived comment says the same thing.

Need a clear technical difference to know which one to use.

Does streamreceived fire as soon as a single byte is received?
Does it fire when a single packet is fully received?
Does it fire when an entire frame is received?
etc.

And what about Message?

**Comment by jchristn** [comment]
Hi @pha3z thanks for filing these issues.

```MessageReceived``` and ```StreamReceived``` are used based on whether or not you want to interact with the message data using a byte array or using a stream (and content length).  The primary purpose of having a stream variant is that some library users are passing large objects and it would be horribly inefficient to put the entirety of the message payload into memory.

I agree with your point about clarity around which to use and why.  I'll make the README a little more clear on this and also make the XML documentation more clear for ```ReadDataStream```, ```MessageReceived```, and ```StreamReceived```.

**Comment by jchristn** [comment]
Fixed in v2.1.0.

NuGet: https://www.nuget.org/packages/WatsonTcp/2.1.0

Commit: https://github.com/jchristn/WatsonTcp/commit/4000e15b3f8383401f11fe819ba5afa005366170

**Comment by pha3z** [comment]
Thanks, Chris! This piece you added to the doc is also highly appreciated:

`It is important to note that when using StreamReceived, the socket is blocked until you have fully read the stream and control has returned from your consuming application back to WatsonTcp.`

Thanks!
