### ISSUE TITLE
Revert last revision, where Thread.Sleep was removed and the Connected field was exposed, and return to 1.0.4

### ISSUE THREAD

**Issue by brudo** [jchristn/WatsonTcp#4]
I have opened a pull request concerning this, see PR-3. This recommends reverting the last commit and leaving WatsonTcp 1.0.4 as the stable version. There is a parallel issue raised to revert changes in WatsonCluster so that it continues to use IsConnected().

**Comment by jchristn** [comment]
Thank you @brudo
