### ISSUE TITLE
Feature request: Disconnect Reason

### ISSUE THREAD

**Issue by pha3z** [jchristn/WatsonTcp#40]
So the idle disconnect appears to be working. :) :)

Shown here, server running in top window and client in bottom window.  Client is using my own autoReconnect logic.

![image](https://user-images.githubusercontent.com/2966966/66064689-84631e00-e50b-11e9-850e-116b59f4bbac.png)

But, now that I see it in operation, on the server side it's disconcerting to not know WHY a client disconnected. Most applications I've ever worked in say a reason like "Idle Disconnect" or something so you know whether the client intentionally disconnected or timed out.  Even a basic chat app or game would have this expectation of knowing a reason.

I think the cleanest way to address this is to add a a second parameter to the ClientDisconnected event handler.  ClientDisconnected(string ipPort, DisconnectReason reason)

where DisconnectReason is an enum with options:
ClientDisconnected
ClientIdleTimeout

Let me know what you think.

**Comment by jchristn** [comment]
This is an excellent enhancement request and I love the idea.

The challenge is that all of the disconnect logic is inside the DataReceiver task that is kicked off for each client.  It doesn't have any context as to 'why' the client has been disconnected (i.e. kicked, timed out, disconnected, etc), so to integrate this might be a bit of effort.

I'll keep it in mind for the future as I will inevitably have to tear into that part of the code again, but in the meantime if you'd like to submit a PR I'd happily take a look.  Cheers

**Comment by jchristn** [comment]
Hi @pha3z - check it out :)

NuGet: https://www.nuget.org/packages/WatsonTcp/2.1.4
Commit: https://github.com/jchristn/WatsonTcp/commit/8f7d47589dac3a3d1c550a6a6c4a7eaaab74892f

Cheers, Joel

**Comment by pha3z** [comment]
This is exciting!  I haven't gotten a chance to try it out yet. I will let you know as soon as I do. In the meantime, I've got another feature request, I'll post on a new thread. :)
