### ISSUE TITLE
ListClients() exposes a List instead of IReadOnlyCollection or IEnumerable

### ISSUE THREAD

**Issue by pha3z** [jchristn/WatsonTcp#44]
I hadn't implemented usage of this yet, or I would have noticed and commented sooner.

Watson returns a List<string> when ListClients() is accessed.  This is generally not good practice for a library.  You should always return the most abstracted collection you can possibly return.

Returning a List says to the consumer "Hey, you can add items to this."  I don't think that's what you want at all.  If somebody wants to alter the connected clients, they should be doing it via the other library calls.

IReadOnlyCollection<string> would be a much better return type if your goal is to allow Indexing.

Bear in mind, it also only makes sense to return an Indexable collection if you are guaranteeing the same ordering every time you provide it. Otherwise, indexing is pretty much useless to the Consumer.  If same ordering is not guaranteed, switch to an IEnumerable<string>

There are other benefits about this to you as the library maintainer.  For instance, if you return an IReadOnlyCollection or an IEnumerable, you can use any kind of backing collection underneath that supports those types.  So if your clients are stored in a Dictionary, then you can return the Dictionary.Values collection without converting it to a List first.  This will perform much faster than having to write to a List first.

--- Of course, if there's some specific reason you opted to return a List, you can enlighten me. :)

**Comment by jchristn** [comment]
Hi @pha3z I chose list because of simplicity, not because I felt it was the best practice.  I agree that the library should return something more abstracted, though I don't feel there's a concern about someone adding something to the list since it's not a settable property (unless you see somehow that it is?).

I'll "add it to the list" (pun intended) to change to IEnumerable.  Thanks for the suggestion!

**Comment by jchristn** [comment]
Changed!

NuGet: https://www.nuget.org/packages/WatsonTcp/2.1.6
Commit: https://github.com/jchristn/WatsonTcp/commit/c7201924d04e696ffb26a51139e4227d0bbacdfe

Thanks for the suggestion again @pha3z !

**Comment by pha3z** [comment]
Yeah... it's common for developers to return List<> just because its so darn easy to do.  But it really ends up being something you regret later if you want to change the underlying data structure.  Its probably more useful to you as the library maintainer to keep it abstracted than it is to the Consumer.  Always future-proof your code. :)
