### ISSUE TITLE
When server receives data

### ISSUE THREAD

**Issue by ml-ls** [jchristn/WatsonTcp#46]
I'm sure I am just being stupid here, but when handling byte arrays (non stream), and the server receives data, how do we respond to the client? Working off the test code I can't obviously see how server.messagereceived can ping back an "ok all good" type of message to the client.

Thanks.

**Comment by jchristn** [comment]
Hi @ml-ls the short answer is that the library does not provide a facility for you to do this.  WatsonTcp is based on TCP which provides reasonable delivery guarantees, but nothing at the application layer guaranteeing delivery.  Any application-layer acknowledgements would be have to be built outside of WatsonTcp.  Thanks!
