### ISSUE TITLE
Message received not triggered on server or client

### ISSUE THREAD

**Issue by marekpetak** [jchristn/WatsonTcp#47]
WatsonTcpServer never triggers/displays received data from server.

to reproduce:
1. clone project
2. open in VS, set TestServer as StartpuProject
3. run the app
4. connect client - detected by server OK
5. send message to client - WORKS
6. send message to server- does not work

**Comment by marekpetak** [comment]
Same issue with client

**Comment by jchristn** [comment]
Hi @marekpetak - I saw that you closed the issue.  I'm curious if you were using an instance of WatsonTcpClient to connect to the server, or how you resolved this?  I ran a quick test using the TestServer and TestClient projects and everything seems to be working fine.  If there's any way I can help, please let me know.  Or, if there's anything I can document better to make it easier!  

Cheers,
Joel

![image](https://user-images.githubusercontent.com/1421081/69249895-86d51200-0b63-11ea-8940-fd5526f857d2.png)

**Comment by marekpetak** [comment]
Thank you, I thave misunderstod the usage of the library, I guess it is not to be use as classic tcpip client/server.

**Comment by jchristn** [comment]
Hi @marekpetak correct - that’s because of the integrated framing (which most find they have to build). If you want something that behaves like a simple TCP server check out my SimpleTcp repository and NuGet package. Might be exactly what you want.

**Comment by jchristn** [comment]
BTW, here is the project: https://github.com/jchristn/SimpleTcp

And on NuGet: https://www.nuget.org/packages/SuperSimpleTcp/

**Comment by marekpetak** [comment]
Thank you, using it already :)
