### ISSUE TITLE
Sending additional info with stream?

### ISSUE THREAD

**Issue by Crushedice** [jchristn/WatsonTcp#49]
Greetings!
Ive been using WatsonTCP now for a while, and it has served me great so far.
Just started working with the new version, as mine was pretty old.

Now i got some problems, i did setup everything so far that a file transfer 
client->server , works fine. My Problem is , that i have to assign all of the files their proper filename.
I tried it already with merging 2 streams together to append some string containing additional infos, but that only ends up in a mess that most likely will throw exceptions in normal usage of the users.

Is there mabe some overload method or some other way to add something to send within the same message? 

Thanks-

**Comment by jchristn** [comment]
Hi @Crushedice and happy holidays to you!

It sounds like what you need is your own data structure that could be converted to a stream and then sent. , i.e. ```[filename][null][datastream]```.  This is essentially building your own framing/messaging layer and the recipient would need to understand it and parse it.

```
            byte[] data = Encoding.UTF8.GetBytes(filename);
            byte[] dataPadded = new byte[data.Length + 1];
            Buffer.BlockCopy(data, 0, dataPadded, 0, data.Length);
            dataPadded[dataPadded.Length - 1] = 0x00; // set null between filename and data stream

            using (MemoryStream ms = new MemoryStream())
            {
                ms.Write(dataPadded, 0, dataPadded.Length);

                using (FileStream fs = new FileStream(filename, FileMode.Open, FileAccess.Read))
                {
                    fs.CopyTo(ms);
                }

                long length = new FileInfo(filename).Length;
                long totalLength = dataPadded.Length + length;

                ms.Seek(0, SeekOrigin.Begin);

                /*
                 * 
                 * Send the stream, length is now in totalLength
                 * 
                 */
            }
```

The other side will of course need to be able to parse this.

Perhaps what could also be helpful is if I put together an API that allows you to send a data structure containing a Dictionary<object, object>, long (stream length), and data stream?  If that sounds like something you could use (might solve your use case) I could add that to my backlog.

Cheers, Joel

**Comment by Crushedice** [comment]
Thanks for the Code snippet , im gonna definitely try that out later.
As i see , i was somewhat on the right way... but really just made a mess in my code.
So you basically put the both streams together, and set between them " 0x00 ",
Is that reliable ? I didn't worked that much with binary, streams etc before , but would imagine if the receiver would search for a 0x00 split point , he would find multiple..~ 

And yes. Some implementation of that kind would be very helpful.
So far as i worked with watsontcp, i wrote the whole code thats working with it , to deal with the Message received ( ClientMetadata , byte[] ) But did extend the ClientMetadata then to contain 1 custom class for infos . and i put custom split points ,and "header" information ( like     2. RH || ...Filedata... ) where its just easy to split('||'); 


So all in all , a big mess of workaround.
But as, so far , watsontcp was really the easiest and best to use api, i did just sticked with that!


Ps. Just FYI ,- My first program i build with it was an custom anti cheat server ,
On current project, im extending our launcher for use with octodiff, and need to send files back and forth. well thats where im struggling :p 

Thanks! and happy holidays !

**Comment by jchristn** [comment]
Hi @Crushedice just a heads-up, I'm wrapping up an implementation on this now that will allow you to pass in a ```Dictionary<object, object>``` into your ```Send``` and ```SendAsync``` methods.  It will fire a different callback though, i.e. ```MessageReceivedWithMetadata``` or ```StreamReceivedWithMetadata```.  I just tested the message-based implementation (it works) and am testing the stream-based implementation now.  Hope to have a release shortly.  This might meet your needs.

**Comment by Crushedice** [comment]
Most definitly! Nice.

Thank you very much!

**Comment by jchristn** [comment]
Hi @Crushedice let me know if you find any issues!

NuGet: https://www.nuget.org/packages/WatsonTcp/2.2.0
Commit: https://github.com/jchristn/WatsonTcp

Please re-open if any issues with the implementation!

Cheers and happy holidays

**Comment by jchristn** [comment]
Hi @Crushedice did this work ok for you?  Cheers!
