### ISSUE TITLE
Please relist WatsonTcp 1.0.4 and compatible WatsonCluster on NuGet

### ISSUE THREAD

**Issue by brudo** [jchristn/WatsonTcp#5]
In light of recent changes committed, can you please relist WatsonTcp 1.0.4 on NuGet? It can still be accessed by direct reference e.g. https://www.nuget.org/packages/WatsonTcp/1.0.4 but doesn't show up in NuGet Package Manager. Also, please republish WatsonCluster to restore compatibility with WatsonTcp 1.0.4, if you have not already. Thanks!

**Comment by jchristn** [comment]
Done, thank you for the reminder!
