### ISSUE TITLE
Help with multiple uploads

### ISSUE THREAD

**Issue by Crushedice** [jchristn/WatsonTcp#51]
Greetings.
Ok, this is not so much of an issue then rather asking for a bit help.

So far its working all fine, also managed to find a solution for my problem with message/stream received. 
( Just assigned streamreceived + streamreceivedwithmeta ) Works . 

now im trying to get multiple files over ,  as i already suspected before , i dont think parallel/multi upload would work here, which is fine. 
If i test the whole upload / receive methods on both ends with only 1 file / stream  
It works like i wanted. The problem occurs if i try to loop trough all the made signatures i want to upload.
For all else i used a backgroundworker to do stuff in, but for this i also tried static void methods, await tasks ( which i really dont understand well enough ) and some other small changes i tried.
but the closest result i get is , completing of uploading the file, but then the client disconnects suddenly from the server...  
this is how it looks : 
```
foreach (var x in Signatures)
            {
                Dictionary<object, object> metadata = new Dictionary<object, object>();
                    metadata.Add(x.Key, x.Value);
                    filecounter++;
                    using (FileStream fss = new FileStream(x.Value, FileMode.Open, FileAccess.Read))
                    {
                        
                        while (!client.SendAsync(metadata, fss.Length, fss).Result)
                        {
                            
                        }

                        // or just bool success = client.SendAsync(metadata, fss.Length, fss).Result
                    }
                    processedFilesCount++;
                    BackgroundWorker4.ReportProgress(i);
                    progressBar1.Value = i;
            }
````

**Comment by jchristn** [comment]
Hi @Crushedice I wouldn't ever recommend using ```.Result```.  It's a really bad practice.  Much better to use ```await```.  

For the sender, you would only use ```bool success = await client.SendAsync(metadata, fss.Length, fss);```

These would have to be done sequentially since WatsonTcp establishes one unique TCP connection per instance.

**Comment by Crushedice** [comment]
so i tried around the last hours again some bit ....
using a hand full of different methods.

Even tried to temp. Store the received streams in a dictionary with custom class . 
but it  always looks like ( looks, cause i don't really get any exception messages for this )
that the client is just pumping every iteration of the loop on to the server, which cuts off the connection after the second / a few files.

And it also seems like there's not much conversation between each endpoint.. or more like none really.

Maybe this was obvious~ don't know if that's intended , but i kinda thought that the server would at least give a callback for the file or anything i could " await " for 

Because, if " success " is the result of the server telling " Ya! i noticed your incoming stream alright!" 
than its obviously not working for any await, ?


I already put in a custom response for , when the iteration from the client is done 
as a distinct message from the client with set string, if the server receives this message ( with associated ip from the msg stream) the server starts to process the files received ... 

wouldn't be... a stopping point if there's no result callback for a successfully transferred stream,
would just be a bunch more lines of code and communication that i would have to put in.

or maybe even a complete different solution .. 

Thanks for helping out !

**Comment by Crushedice** [comment]
I made a stripped version of my bigger program now to test the uploads.
If i only send 1 file it all works like it should.
So, im pretty sure that the server discards the client , the moment the client just sends all the files without the server able to catch up with it.

Wouldnt it be possible, to set the received method to not use a non async task and 
return Task.CompletedTask;  at the end of the method to let the client know?  
( i dont know if this is actually possible from the code of watsontcp ) 

But it would definitly solve my problem.

**Comment by jchristn** [comment]
Hi @Crushedice - can you reproduce the issue using one of the ```Test``` projects?  The server should never discard the client unless explicitly kicked by the admin.

**Comment by jchristn** [comment]
Hi @Crushedice can you paste a sample file containing your implementation so I can test it on my end?

**Comment by Crushedice** [comment]
sorry took a bit to reply.
So far i got everything working 
i changed up the sending of all files just to Packing it in a zip ->
then send the one file .  A few minor bugs from my side were also causing some problems.

But so far,  all works . 
Now only left is find all bugs, optimize, visual styling and real env. testing haha
Thanks for the help!
