### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by adyp770** [jchristn/WatsonTcp#52]
I'm unable to get Test Client to connect with the Test Server with SSL enabled. The Server and Client options are given below. The certificate test.pfx exists in the same directory as the Test Server executable. 

The Client throws an exception:
System.Security.Authentication.AuthenticationException: 'The remote certificate is invalid according to the validation procedure.'

Server IP: [127.0.0.1]
Server port: [9000]
Use SSL: [y/N]? y
Certificate file: [test.pfx]
Certificate password: [password]
Accept invalid certs: [Y/n]? n
Mutually authenticate: [y/N]? n
Command [? for help]:

Server IP: [127.0.0.1]
Server port: [9000]
Use SSL: [y/N]? y
Supply SSL certificate: [y/N]? n
Accept invalid certs: [Y/n]? n
Mutually authenticate: [y/N]? n

**Comment by jchristn** [comment]
Hi @adyp770 you have to allow invalid certificates.  The ```test.pfx``` certificate in the repo is self-signed.

![image](https://user-images.githubusercontent.com/1421081/71833865-bb912000-3062-11ea-848f-f467880a1cb5.png)
