### ISSUE TITLE
Showing SendAsync Upload/Download Progress

### ISSUE THREAD

**Issue by Crushedice** [jchristn/WatsonTcp#53]
Greetings,
Me again haha. 
So far, everything worked fine, and now also as i want it.
Already made a bunch of updates with my tool.

Now im at optimizing, and improving the user experience. 
A bit portion of that is to show the user whats going on.
Got quite a few reports that it seemed like the program would " freeze " 
where, in reality it just uploaded the file still.
is there any way to get a progress report when using client.sendasync method?

I rather not use just a different upload method, as so far everything is pretty much contained and uses the same api , don't want to start mixing things up.

Here my example code were i would need such ability.

```
public async Task UploadFileAsync(string zipfile)
        {
            var metadata = new Dictionary<object, object>
            {
                {xxx, xxx}
            };
            using (var source = new FileStream(zipfile, FileMode.Open, FileAccess.Read))
            {
                await client.SendAsync(metadata, source.Length, source);
            }
          }
```

**Comment by jchristn** [comment]
Hi @Crushedice looking into this now, give me a moment please :)

**Comment by jchristn** [comment]
Hi @Crushedice I honestly don't know (right now) how I would accomplish this in my library.  I'll have to think on this some more.  A good interim solution for you would be to use SendAsync(byte[]) and read from the FileStream yourself.  That way, since you know the file length (```new FileInfo(filename).Length```) and how many bytes you've read, you could then report status.  

If you have suggestions on how I might do this in the library, I'm all ears.  

Thanks and have a great night!

**Comment by Crushedice** [comment]
Dont worry,  its not like a app breaking issue. 
Just more for the users, and ya.  as i am currently anyway on it i will try some stuff and report back if i found a proper solution. 

Another rather small thing that i wanted to ask, if we can get a small method to override your
"Log" method.
As i am not using Winforms,  and not a console app, ive written my own " console log " method,
Would be nice to be able to route the debug messages from watson to my output , to see any msg that comming.  Thanks!

**Comment by jchristn** [comment]
Great suggestion @Crushedice - I will add it to my list!

**Comment by Crushedice** [comment]
As Edit :  maybe not just an overwrite.  
i just now played around with it a bit. 
Just a new Event handler would be enough.
checking if the handler is subscribed, if it is, skip the Console output and put the msg out with the event args.  😃

**Comment by jchristn** [comment]
Here you go, just override ```Logger``` with your own method!  
```
client.Logger = Logger;
private void Logger(string msg) { Console.WriteLine(msg); }
```

Commit: https://github.com/jchristn/WatsonTcp/commit/b034ed6270936e2e30b0c601dc0b8aa1187abe16
NuGet: https://www.nuget.org/packages/WatsonTcp/2.2.1

Cheers!  Joel
