### ISSUE TITLE
Integer must be between....

### ISSUE THREAD

**Issue by Crushedice** [jchristn/WatsonTcp#55]
Greetings again, 
After re-writing my methods due to the breaking changes of V3.0  , i encountered an issue (That may be already been before an issue , just without this message)

`  -Integer must be between 0 and 9999.- at WatsonTcp.Message.WatsonMessage.IntegerToBytes(Int32 i)`

I dug around a bit , and think its related to the site of the data i want to send?  
Is the Metadata limited in some way , eather in size or format ? 

The situation: 
When my clients connecting to the server,  the server is sending a dictionary with
FileLocations as Keys ( string )  and FileHashes ad Values (string) ( String KeyValuePairs casted to object for sending ofc) .  

I thought it would make more sense to send them via the metadata as it already defines a dictionary.   /  Before the breaking changes i did send all that info as normal message as 1 big string and used JsonDeserialize at the endpoint myself . Worked all fine.  

Some help here would be nice :p  Thanks

**Comment by jchristn** [comment]
Hi @Crushedice yes, this is due to a size limitation hard-coded into the framing layer.  It can be extended to a larger size by modifying ```WatsonMessage.cs```.  How much data are you sending?

**Comment by Crushedice** [comment]
Juust did a test with debug output,
He stops at the metadata with said exception and tells me : 
"Metadata: [present,98289 bytes]"  
The file where he's reading the dictionary of is 103kb ,
In the notepad there are 1350 Lines , each one - Key + Value  as Json converted.

**Comment by jchristn** [comment]
Creating a branch for v3.0.3 and uploading, would you be able to give it a whirl and make sure it works for your use case?  Expanding metadata out to 99,999,999 bytes.

**Comment by jchristn** [comment]
Branch v3.0.3-beta: https://github.com/jchristn/WatsonTcp/tree/v3.0.3-beta
NuGet package attached here for the same (Debug version)

**Comment by Crushedice** [comment]
Branch 3.0.3 Beta :" This branch is even with master. " 

I cant see any difference.  Expected outcome - like before

**Comment by jchristn** [comment]
I'm dumb, I did it on master instead of first doing a ```git checkout v3.0.3```.  Please try with master.  Or the ZIP containing the NuGet package.  Let me know, thanks!

**Comment by jchristn** [comment]
Did this work for you @Crushedice ?

**Comment by jchristn** [comment]
Hi @Crushedice I just tested this on my side and it appears to work, definitely sending more than 10KB through metadata.  I added a hidden test command to Test.Client and Test.Server to send metadata comprised of a Dictionary where the key was integers 0...99999 and values that were identical to the key.  Thus it was sending likely 10s of megabytes of data.  

I'll go ahead and close this and package up v3.0.3 in NuGet.  Please re-open if you encounter any problems.

![image](https://user-images.githubusercontent.com/1421081/75572502-c091a080-5a0f-11ea-8b89-0181cba7cb4e.png)

**Comment by Crushedice** [comment]
Sorry,  Was unavalible today,  but just tested it out, and this reolved my issue. Thanks for this! 

A small question i now have with the breaking changes made,  
as i dont see any message system here ill ask this here. 

Whats the point of the "Data" arg ? 
so like  - StreamReceivedFromClientEventArgs args.Data ,  Its saying , i can just get the whole stream from this.  
So i could work with Data ,  and dont have to fetch all the stuff myself with the "while" and  Buffer.BlockCopy method?

**Comment by jchristn** [comment]
Awesome, I'm glad it worked for you.

Re: ```Data``` - that's right.  If you access ```Data```, then ```DataStream``` will be fully read for you, so you can access the data directly.  Cheers!
