### ISSUE TITLE
Client detects disconnection, but server doesn't

### ISSUE THREAD

**Issue by developervariety** [jchristn/WatsonTcp#57]
My WatsonTcp client randomly detects a disconnection, but my WatsonTcp server doesn't say it has been disconnected until I close the application.

I'm sending a lot of information back and forth non-stop (5Kbps+), could this be a possibility?

**Comment by jchristn** [comment]
Hi @developervariety it shouldn't be.  I explicitly test high throughput scenarios with single and multiple connections.  Have you enabled logging by setting the ```Logger``` on both the client and server to see what is causing it to indicate a disconnection?

**Comment by developervariety** [comment]
I haven't set `Logger`, doing so now and testing again. Thank you for the fast response.

**Comment by developervariety** [comment]
I have set `Logger`, and much didn't change. I removed `IdleClientTimeoutSeconds` and it fixed the issue. Not sure how...?

**Comment by jchristn** [comment]
Hi @developervariety sounds like it was intermittent.  Did you notice any log messages around the time when it randomly detected a disconnect on the client?  You would also see exception messages there if there were exceptions happening.

**Comment by developervariety** [comment]
Yeah, I really don't know what caused it. I'll keep logging until it happens again, thanks!
