### ISSUE TITLE
All connections/clients crash when one disconnects

### ISSUE THREAD

**Issue by developervariety** [jchristn/WatsonTcp#59]
I have multiple clients running instances of my application. I cap the amount of instances  each client is allowed to run, but whenever someone goes over the allowed amount, all instances on the same machine all crash. Server says it's a normal disconnect, and clients say to use `Connect()` practically meaning it was disconnected.

Here is my setup,

**Server**
```csharp
SocketServer = new WatsonTcpServer(null, 1337, "server.pfx", "password") {
 PresharedKey = "presharedkey",
  MutuallyAuthenticate = true,
  AcceptInvalidCertificates = true,
  IdleClientTimeoutSeconds = TimeSpan.FromMinutes(5).Seconds
};
```

**Client**
```csharp
SocketClient = new WatsonTcpClient(ClientAddress, 1337, "client.pfx", "password") {
 MutuallyAuthenticate = true,
  AcceptInvalidCertificates = true,
  Logger = delegate(string s) {
   Log.Debug("[{system}] {s}", "WatsonTcp", s);
  }
};
```

**Comment by jchristn** [comment]
Hi @developervariety I'd need to see more of your code to diagnose this.  Your instantiation of both the client and server look fine.  I would also try enabling the Logger on the server to see if you can determine what is happening.  

I'd also like to see the logic you have to prohibit one of your applications from running more instances than specified, and also recommend that you go to a single instance of the client.  The client has locking internally to make sure that requests do not step on one another.  Having fewer clients means fewer TCP connections and fewer background tasks/threads.

Thanks, Joel

**Comment by developervariety** [comment]
Is there a way to contact you so I can send you my project files?

**Comment by jchristn** [comment]
Hi @developervariety it would be best if you could isolate the issue into a codebase that can be shared if possible.  If that isn't possible, you could post a link here generated from file.io (one-time download) and I can take a look.  Cheers, Joel

**Comment by developervariety** [comment]
Looks like user code was causing this, so sorry!
