### ISSUE TITLE
'MessageReceived' or 'StreamReceived' must first be set

### ISSUE THREAD

**Issue by developervariety** [jchristn/WatsonTcp#60]
Add `SyncRequest`. The latest update allowed me to switch my layout completely instead of using a `List<T>` and looking thru it for a request built from the server.

**Comment by developervariety** [comment]
`WatsonTcpClient` will detect a `disconnection` (but server does not) if `MessageReceived` or `StreamReceived` is not set.

**Comment by jchristn** [comment]
Hi @developervariety one of the two ```MessageReceived``` or ```StreamReceived``` must be set.  

The intent of the metadata fields i.e. ```SyncRequestReceived``` is not to be the primary means of messaging but rather a means of including metadata with a message.  With the recent enhancements I guess this changes things somewhat.

If you're only sending ```Dictionary<object, object>``` back and forth between client and server, you can either:

1) set ```MessageReceived``` to an empty event handler and it should work fine.
2) just serialize/deserialize your Dictionary and use the Send methods carrying the serialized dictionaries

Cheers, Joel
