### ISSUE TITLE
In this project the client will connect but then is immediately disconnected

### ISSUE THREAD

**Issue by lxman** [jchristn/WatsonTcp#62]
[RemoteControl.zip](https://github.com/jchristn/WatsonTcp/files/4386989/RemoteControl.zip)

**Comment by jchristn** [comment]
Hi @lxman thanks for sending this.  Appears to be a problem in the client form.  I'm investigating this now.  When I connect from a console client, it works fine (see attached).  Will post findings and source when finished.
![image](https://user-images.githubusercontent.com/1421081/77665721-4801ff00-6f3d-11ea-8248-94c931d61824.png)

**Comment by jchristn** [comment]
Client is somehow being immediately disposed.
![image](https://user-images.githubusercontent.com/1421081/77665906-83043280-6f3d-11ea-943b-48b9f23cf723.png)

**Comment by jchristn** [comment]
Ok so it appears that when the Send methods are embedded within forms event handlers, Dispose gets called on the object (!!!).  I don't know why this is happening or what to do about it.  Any suggestions?
![image](https://user-images.githubusercontent.com/1421081/77668516-bd230380-6f40-11ea-835f-dc5eb1f670f8.png)

**Comment by lxman** [comment]
Hmm, well, that's odd - I do know a bit about winforms, so I'll think about it. Here's something else to add to the puzzle. I have a project done with a similar design, only using WPF. That project does not have this issue. I realize that at this point it only confirms your diagnosis, but I thought that might be good to know.

When I get a bit of time around my day job I'll take a look.

**Comment by jchristn** [comment]
Wait, I got it.  Give me a moment.

**Comment by jchristn** [comment]
Simple fix.

Set either ```MessageReceived``` or ```StreamReceived``` event on your client.

I'll modify ```.Start()``` to throw an exception if neither is set.  

Thanks for catching this!  I was about to pull my own hair out...

![image](https://user-images.githubusercontent.com/1421081/77669511-1d667500-6f42-11ea-95ff-902ce98ca12e.png)

**Comment by jchristn** [comment]
FYI there was a code path inside the main DataReceiver loop where a ```break``` was present without any logging.  DataReceiver was actually terminating because the main loop was broken and Dispose is called at the end of DataReceiver.

**Comment by lxman** [comment]
Hmm, okay, I've set a handler on  `MessageReceived` and that particular error does not appear any more. Thanks!

**Comment by jchristn** [comment]
I updated the package to v3.1.4 on NuGet: https://www.nuget.org/packages/WatsonTcp/3.1.4

Here's the commit: https://github.com/jchristn/WatsonTcp/commit/fcfc5487832f34cd422a3f4deb5f457951cd8ada

It adds better logging for cases in code where the DataReceiver loop is broken due to the lack of a message or stream handler, and throws an InvalidOperationException if Start or StartAsync is attempted without these being set.

Thanks for finding this!  It proves the fact that if you have a code path, somehow it will be found!

**Comment by jchristn** [comment]
By the way @lxman would you mind if I posted (public) the modified source from the .ZIP file above?  It may benefit others using the project.  If not, I understand!

**Comment by lxman** [comment]
That's fine with me - that was just a barebones to demonstrate the issue. Nothing really proprietary there.

**Comment by lxman** [comment]
Okay, it looks like I'm on to step 2, and I've got the same thing. I've started to fill out the project and  the client is getting suddenly disconnected again. Would you like me to open up a new ticket or just continue this one in order to send you the source?

**Comment by jchristn** [comment]
Let's reopen this one.

**Comment by lxman** [comment]
No, sorry, wait. I see what it is now. I was doing something stupid on the server side. It was causing the server to crash. Just saw that as I was uploading to you.

[RemoteControl.zip](https://github.com/jchristn/WatsonTcp/files/4390074/RemoteControl.zip)

I'll try to be a little more diligent. In short, I created a list of Control, tried to access the first element, but had forgotten to actually add a control to the list. I guess trying to reach in and get element 0 when the list is actually empty caused the server to go belly up.

My bad.

**Comment by jchristn** [comment]
Hey @lxman don't sweat it, happy to help.  Reclosing for now.  Don't hesitate to file new issues if/when they arise.  Cheers and stay safe.
