### ISSUE TITLE
SyncResponse data always null?

### ISSUE THREAD

**Issue by Crushedice** [jchristn/WatsonTcp#67]
Greetings!
The new Syncresponse seems pretty usefull to me, 
to send message only data as supposed to bigger file transfer over streams.
So i can split them , and not use only the one method for everything.
But i encounter now one problem.
Any Syncresponse.Data is null  for me, client + serverside.
Am i doing something wrong? 

```
try
            {
                SyncResponse resp;

                resp = client.SendAndWait(5000, "StringToSend");
                var data = resp.Data;
                if (data != null)
                {
                    var answer = Encoding.UTF8.GetString(resp.Data);

                    .......
                }
                else
                {
                    .......
                }
            }
            catch
            {
              .......
            }
```

**Comment by jchristn** [comment]
Hi @Crushedice happy Monday to you!  Could you share a bit more of the code, specifically the code that is responding?  I'd be happy to double-click into what's happening on your side.  I just tried locally with v4.0 and it is working.  Which version are you using?

Synchronous client to server:
![image](https://user-images.githubusercontent.com/1421081/79129027-55025900-7d59-11ea-8c58-786173a05982.png)

Synchronous server to client:
![image](https://user-images.githubusercontent.com/1421081/79129080-6b101980-7d59-11ea-82d6-966baff7d830.png)

**Comment by jchristn** [comment]
Hi @Crushedice wanted to see if you had a follow-up on this one?  Cheers

**Comment by developervariety** [comment]
If @Crushedice is using the latest version then they won't encounter any issues.

**Comment by jchristn** [comment]
Please re-open if the issue persists after moving to the latest version.  There were issues with this that were resolved.  Thanks!
