### ISSUE TITLE
Feature request - async-friendly send/flush and idle/poll operations

### ISSUE THREAD

**Issue by brudo** [jchristn/WatsonTcp#7]
This is not a bug report, but a feature request. I may help implement it, on my own time, but no promises!

Currently, WatsonTcp and WatsonCluster perform nicely for the basic use case of a simple peer-to-peer cluster with limited messaging. However, internally, the library uses methods like Flush() that block the calling thread when sending messages, instead of non-blocking awaitable equivalents like FlushAsync(). (Although non-blocking code is already used to Connect and Receive messages.)

Likewise, when looping and polling, the present code uses blocking calls such as Thread.Sleep(ms) and Task.Delay(ms).Wait() instead of non-blocking variations based on `await Task.Delay(ms)` which would unschedule the present Task, and release the thread back to the thread pool to be reused.

Use of blocking code, even with short-interval delays and sending on a known-healthy connection, limits scalability and capacity to support concurrent operations in applications leveraging WatsonCluster for internal messaging. At least in theory, some calls to WatsonTcp will tie up threads from the thread pool even when WatsonTcp is idling or waiting for an IO operation to complete, whereas other async Tasks running on the thread pool could be making use of those threads.

So far it does not seem to be hitting any limits in my present use case, as I can mostly fire-and-forget messages to a partner instance using something like `Task.Run(()=>cluster.IsHealthy() && cluster.Send(...))`, but the library would be more versatile if this were implemented. Nothing preventing you from continuing to provide the current blocking Send() as well as a non-blocking `async Task<bool> SendAsync(...[, cancelToken])`.

**Comment by brudo** [comment]
Please see my branch WatsonTcp/tree/async-to-the-core for an initial stab at this to show what I had in mind - completely untested but builds fine. When it's ready for a pull request, I'll be happy to share and collaborate on refining it.

**Comment by jchristn** [comment]
This is perfect @brudo , thank you for sharing this.  Would you mind making a pull request and I'll merge it in and publish a NuGet update?  Cheers!

**Comment by brudo** [comment]
Sure. Mind you I did not test it (could not get the tests to run - probably a problem at my end), so I really suggest putting it through its paces before you update. Also, I missed WatsonTcpClient.cs in my initial commit last night - added now. See pull request #8.

Next after this would be a change in WatsonCluster to use the async methods.

**Comment by brudo** [comment]
As this is tested now, and deployed to NuGet, and working in WatsonCluster, I guess this can be closed. Thanks for accepting the changes @jchristn.
