### ISSUE TITLE
Deserialization exception when using compression and SSL together

### ISSUE THREAD

**Issue by jchristn** [jchristn/WatsonTcp#71]
CC: @developervariety since this was his enhancement request

Steps to reproduce:
1) instantiate both server and client using SSL
2) set client compression mode to ```Gzip``` or ```Deflate```
3) send two or more messages

First message received ok:
![image](https://user-images.githubusercontent.com/1421081/79600473-0ed03100-809c-11ea-9436-86f587f09777.png)

Second message:
![image](https://user-images.githubusercontent.com/1421081/79600533-25768800-809c-11ea-8bad-4723123fa61a.png)

Exception output:
```
Exception while deserializing (note the binary data prior to the JSON metadata)
?l\M   {"Status":"Normal","SyncRequest":false,"SyncResponse":false,"Compression":"Gzip","ContentLength":26,"Metadata":{}}



Exception:
{
  "ClassName": "Newtonsoft.Json.JsonReaderException",
  "Message": "Unexpected character encountered while parsing value: ?. Path '', line 0, position 0.",
  "Data": null,
  "InnerException": null,
  "HelpURL": null,
  "StackTraceString": "   at Newtonsoft.Json.JsonTextReader.ParseValue()\r\n   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)\r\n   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)\r\n   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)\r\n   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)\r\n   at WatsonTcp.SerializationHelper.DeserializeJson[T](String json)",
  "RemoteStackTraceString": null,
  "RemoteStackIndex": 0,
  "ExceptionMethod": "8\nParseValue\nNewtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed\nNewtonsoft.Json.JsonTextReader\nBoolean ParseValue()",
  "HResult": -2146233088,
  "Source": "Newtonsoft.Json",
  "WatsonBuckets": null
}

[WatsonMessage] BuildStream exception:
{
  "ClassName": "Newtonsoft.Json.JsonReaderException",
  "Message": "Unexpected character encountered while parsing value: ?. Path '', line 0, position 0.",
  "Data": null,
  "InnerException": null,
  "HelpURL": null,
  "StackTraceString": "   at WatsonTcp.SerializationHelper.DeserializeJson[T](String json)\r\n   at WatsonTcp.WatsonMessage.<BuildFromStream>d__36.MoveNext()",
  "RemoteStackTraceString": null,
  "RemoteStackIndex": 0,
  "ExceptionMethod": "8\nParseValue\nNewtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed\nNewtonsoft.Json.JsonTextReader\nBoolean ParseValue()",
  "HResult": -2146233088,
  "Source": "Newtonsoft.Json",
  "WatsonBuckets": null
}
```

Theory: it seems the compression stream is not being read fully, or, when reading, the position is not advancing.

**Comment by developervariety** [comment]
Is this the issue? `?l\M�`

**Comment by jchristn** [comment]
Yep, that's exactly it.  It seems that when I read out of the DeflateStream or the GZipStream (and then close it, leaving the underlying NetworkStream or SslStream open) it leaves some remnants behind and I'm not sure why.  Then, when I go to read the next message, the first bits it reads are those extranneous bytes before the next message's header.

**Comment by jchristn** [comment]
I'm going to run a test to see if the size of that garbage scales with the size of the message.  If so it's likely not advancing the position on the stream.

**Comment by jchristn** [comment]
Doesn't seem to scale with the message.
![image](https://user-images.githubusercontent.com/1421081/79609535-c587dd80-80ab-11ea-83a1-78d6fa92cb07.png)

I'll need to do some digging into how the ```bool leaveOpen``` in the DeflateStream and GZipStream constructors work with the underlying stream.  Could be with SSL there needs to be an extra step after closing the encapsulating DeflateStream or GZipStream.

**Comment by jchristn** [comment]
I have a fix and will be packaging it up in the next day.  

It comes down to this.  When reading from GZipStream or DeflateStream, you may leave extranneous bytes in the stream if you only read out the number of content bytes you think you need.

i.e. if I write 1024 bytes to GZipStream, one would expect that I could then as a consumer just read 1024 bytes.  That appears to NOT be the case.

When I moved the internals to simply read the streams fully (only for GZipStream and DeflateStream) the issue went away, even for SSL.

Will package up a new release and publish to Github and NuGet ASAP!  There is also a minor refactor in there and a little more cleanup I need to do.

@developervariety FYI :)

**Comment by developervariety** [comment]
I knew only reading the `ContentLength` provided number was the issue here! I'm surprised it was JSON.NET throwing the error instead of the compressor trying to decompress the stream/data.

Glad to see the issue has been resolved. Thank you!

**Comment by jchristn** [comment]
NuGet v4.1.3: https://www.nuget.org/packages/WatsonTcp/4.1.3
Commit: https://github.com/jchristn/WatsonTcp/commit/34d5cde5f55826e83e0684f4ed5d5741e3a3a14e

@developervariety I hope some of the internal refactoring doesn't throw off your PR too much.  Cheers and have a good night
