### ISSUE TITLE
Feature request: Data Encryption

### ISSUE THREAD

**Issue by developervariety** [jchristn/WatsonTcp#73]
I forked the repository and added `Data Encryption`. This somewhat protects users that do not want to use a SSL certificate, but don't want to send plain data thru the network.

I have yet to push the changes bc I would like some feedback along with extensive testing once a submit a PR.

- What types of algorithms should be offered by default?
- What ciphers should be used per algorithm?
- What should be the minimum key length?

**Comment by developervariety** [comment]
Files changed if merged:
- WatsonTcpClient.cs
- WatsonTcpServer.cs
- WatsonMessage.cs

New files:
- EncryptionHelper.cs
- EncryptionType.cs

**Comment by jchristn** [comment]
Hi Justin, I think AES256 would be a good enough start.  Cheers!

**Comment by developervariety** [comment]
Alright, sounds like a plan!

So the way I wanted to go about it didn't go as planned by putting it in `SendDataStream`/`SendDataStreamAsync` bc `ContentLength` is bigger after the the message data is encrypted unless `Compression` was used.

I'm currently encrypting the data, and updating the content length before either of those methods are executed.

**Comment by jchristn** [comment]
I wanted to keep ContentLength in the header to be the original data length - you'll notice that instead of updating the ContentLength for compressed vs uncompressed data, I left it in tact and relegated handling to the DeflateStream and GZipStream.  Perhaps we could add another header that indicates the BlockSize and other parameters so that ContentLength can remain a representation of the source data?

**Comment by developervariety** [comment]
Yeah we could definitely do that, I'll submit the draft PR as soon as I finish cleaning up so we can tweak some things.

For encryption-related parameters that would be a major plus bc currently I'm using the same salt and I would love to generate a new salt for every data exchange between the two parties.

**Comment by developervariety** [comment]
Long time since I've been on GitHub, thanks for not closing the PR/issue! I'll get the PR draft ready ASAP.
