### ISSUE TITLE
Client disconnection only in SyncRequest after TimeoutException

### ISSUE THREAD

**Issue by ozrecsec** [jchristn/WatsonTcp#75]
Hi,
I'm getting in a strange problem, I'll describe by steps:
- Client connects fine and sends messages and syncRequest correctly
- Client sends a SyncRequest that the server takes long to respond and client goes in timeoutException
- After this the client can send regularly standard messages with .Send(...) and works fine
- But if I send another SyncRequest and the server completes the request and sends back the response correctly, the client receives the disconnection event and after some seconds receives a timeoutexception  and never receives the response.

It seems that the first timeoutException on Clientside "closed" something only for SyncRequest and we can see the effects only at the next SyncRequest.

Now I'll prepare and post in this issue two Program.cs (client/server) to test the situation.

thanks
Michele

**Comment by jchristn** [comment]
Hi @ozrecsec I appreciate the level of detail.  I'm working on reproducing this now; I think I have an idea of what is happening.  Thanks!

**Comment by jchristn** [comment]
1) Synchronous request timeout handled correctly by client (discarded timed-out response)
![image](https://user-images.githubusercontent.com/1421081/80122930-116ed280-8543-11ea-8900-832b542336d2.png)

2) Async message sent client to server works after timed-out sync request
![image](https://user-images.githubusercontent.com/1421081/80123000-277c9300-8543-11ea-846f-ba0455622f6d.png)

3) Subsequent synchronous request sent client -> server fails with Exception
![image](https://user-images.githubusercontent.com/1421081/80123097-4844e880-8543-11ea-9526-f2c06e658d3e.png)

Issue appears to be that previous message data is either not read out from the socket, or, is going out without a header.  The former is more likely, and similar to the issue seen with compression and SSL previously.  The latter is far less likely.
```
Command [? for help]: sendandwait
Data: This synchronous request should not be delayed and should succeed
Timeout (milliseconds): [5000]
[WatsonMessage] ReadHeaders found header demarcation

Exception while deserializing:
Here is your response!{"Status":"Normal","SyncRequest":false,"SyncResponse":true,"Expiration":"2020-04-23T09:17:14.0376783-07:00","ConversationGuid":"4ce12a76-6dd9-4479-abf1-273c9c0da963","Compression":"None","ContentLength":22,"Metadata":{"foo":"bar","bar":"baz"}}



Exception:
{
  "ClassName": "Newtonsoft.Json.JsonReaderException",
  "Message": "Unexpected character encountered while parsing value: H. Path '', line 0, position 0.",
```

Going to amend my test program to customize the server response to indicate whether it was a delayed response (based on the client message) or a standard response.  This will confirm if it's the former (message data not read from stream) or the latter (message data sent without header)

**Comment by jchristn** [comment]
I need to check here to see if payload was read:
![image](https://user-images.githubusercontent.com/1421081/80123532-e042d200-8543-11ea-8615-c54b9a72e76a.png)

Ok, as suspected, it appears the expired message **data** is not read by the client and left in the underlying stream - see ```I waited 6 to send this to you```:
![image](https://user-images.githubusercontent.com/1421081/80123622-fe103700-8543-11ea-84f0-659d729910ad.png)

I need to make sure expired message data is read from the underlying stream.  Working on this now.

**Comment by jchristn** [comment]
I suspect this is the problematic code in the server DataReceiver:
```
                    else if (msg.SyncResponse)
                    { 
                        if (DateTime.Now < msg.Expiration.Value)
                        {
                            byte[] msgData = await WatsonCommon.ReadMessageDataAsync(msg, _StreamBufferSize);

                            lock (_SyncResponseLock)
                            {
                                _SyncResponses.Add(msg.ConversationGuid, new SyncResponse(msg.Expiration.Value, msg.Metadata, msgData));
                            }
                        }
                        else
                        {
                            Logger?.Invoke("[WatsonTcpServer] Expired synchronous response received and discarded from " + client.IpPort);
                        }
                    }
```

And in the client DataReceiver:
```
                    else if (msg.SyncResponse)
                    {
                        if (DateTime.Now < msg.Expiration.Value)
                        {
                            byte[] msgData = await WatsonCommon.ReadMessageDataAsync(msg, _StreamBufferSize);

                            lock (_SyncResponseLock)
                            {
                                _SyncResponses.Add(msg.ConversationGuid, new SyncResponse(msg.Expiration.Value, msg.Metadata, msgData));
                            }
                        }
                        else
                        {
                            Logger?.Invoke("[WatsonTcpClient] Expired synchronous response received and discarded");
                        }
                    }
```

**Comment by jchristn** [comment]
Testing a fix.

**Comment by jchristn** [comment]
Tested with fix:

1) Sent message that should timeout (instructed server to wait 6 seconds on a 5 second timeout); it timed out as expected
![image](https://user-images.githubusercontent.com/1421081/80124373-09b02d80-8545-11ea-90f4-2376c06b632d.png)

2) Sent another message that should not timeout (it didn't)
![image](https://user-images.githubusercontent.com/1421081/80124419-1af93a00-8545-11ea-9e83-6504f42849cf.png)

3) Sent another message that should timeout (it did)
![image](https://user-images.githubusercontent.com/1421081/80124513-395f3580-8545-11ea-84fe-3fa07f6175ae.png)

This seems to fix it!  I'll publish to NuGet and commit here momentarily.

Thanks @ozrecsec !

**Comment by jchristn** [comment]
NuGet: https://www.nuget.org/packages/WatsonTcp/4.1.5
Commit: https://github.com/jchristn/WatsonTcp/commit/65a20937ede1434d246cb459ec57b63617af7253

Thanks again @ozrecsec - closing this, please let me know if the issue continues!

**Comment by ozrecsec** [comment]
I've tested and works geatly

thanks!
