### ISSUE TITLE
SendAndWait is not working if receivers system time is later than senders system time

### ISSUE THREAD

**Issue by karstennilsen** [jchristn/WatsonTcp#76]
Of course in an ideal world al system times are totally in sync. In real life system time of different computer can be easily out of sync several seconds. 
Both WatsonTcpClient.cs and WatsonTcpServer.cs have the following expiration check which. 
I would suggest to determine time diference on connect and use this difference or add a possiblitiy to remove expiration check (of course keep the timeoutexception in GetSyncResponse).

                    if (msg.SyncRequest)
                    { 
                        if (SyncRequestReceived != null)
                        {
                            byte[] msgData = await WatsonCommon.ReadMessageDataAsync(msg, _StreamBufferSize);
                            if (DateTime.Now < msg.Expiration.Value)
                            {

**Comment by jchristn** [comment]
Hi @karstennilsen thanks for sending this over.  Agreed this is a problem.  I was thinking of amending the metadata sent with every message to include the sender's timestamp.  That way the receiver would understand the sender's local time within +/- the one-way network latency.  Then things like the expiration timestamp could be derived based on the difference.  The downside to this is it would be adding ~40 bytes overhead to every message.

How would you feel about that as a solution?

**Comment by jchristn** [comment]
Hi @karstennilsen please let me know if this fixes the issue for you.

NuGet v4.1.6: https://www.nuget.org/packages/WatsonTcp/4.1.6
Commit: https://github.com/jchristn/WatsonTcp/commit/e8131037ec1cb7846c5d4e00bf588a459dde616f

**Comment by karstennilsen** [comment]
Wow, already a fix, nice! 
Just took a quick peek at the code at this looks like a decent way on handling it. 
It's already late here. Will do some test tomorrow with the new version.

**Comment by karstennilsen** [comment]
In my test situation it doesn't work. I think I know why:
```
                // TimeSpan will be negative if sender timestamp is earlier than now or positive if sender timestamp is later than now
                // Goal #1: if sender has a later timestamp, increase expiration by the difference between sender time and our time
                // Goal #2: if sender has an earlier timestamp, decrease expiration by the difference between sender time and our time
                //
                TimeSpan ts = msg.SenderTimestamp.Value - DateTime.Now;
                expiration = expiration.AddMilliseconds(ts.TotalMilliseconds);
```
I believe you have to reverse it, e.g.:
If sender time is 10:40 and receiver time is 10:45 and expiration is 1 minute, so 10:41.
ts = 10:40 - 10:45 = -5 minutes
expiration = 10:41 + -5 = 10:36
But the expiration needs to be 10:46 because that's 1 minute later than receiver time 10:45.

**Comment by jchristn** [comment]
Hi @karstennilsen just merged, committed, and updated NuGet. Thanks for this!

NuGet: https://www.nuget.org/packages/WatsonTcp/4.1.8
Commit: 754ba48

Cheers, Joel
