### ISSUE TITLE
Disconnect Clients inside ClientConnected event

### ISSUE THREAD

**Issue by Motridox** [jchristn/WatsonTcp#78]
Hi,

not sure if this is classified as an Issue. 
If you try to disconnect a client inside the ClientConnected event, the client simply refuses to disconnect.

Code example I guess:
`		private void TcpServer_ClientConnected(object sender, ClientConnectedEventArgs e)
		{
			Console.WriteLine("connect");
			WatsonServer.DisconnectClient(e.IpPort);
		}`

Executing the DisconectClient method inside a task however will disconnect the client.

PS: This is happening on the same machine (server+client). I haven't tested it on different machines yet, but I will do as soon as possible.

**Comment by jchristn** [comment]
Hi @Motridox interesting, this is definitely not the intention.  I'll test this right now!  Thanks for filing this.

**Comment by jchristn** [comment]
Was able to reproduce immediately, seems like the ```OperationCanceledException``` was being caught inside of the ```DataReceiver``` task for that particular client, but did not break out of the outer while loop.  Testing a fix.

**Comment by jchristn** [comment]
Fix seems to be working:
![image](https://user-images.githubusercontent.com/1421081/80820477-c7fa3500-8b8b-11ea-9ea8-27cb52d1dc6c.png)

Server code:
```
        private static void ClientConnected(object sender, ClientConnectedEventArgs args)
        {
            lastIpPort = args.IpPort;
            Console.WriteLine("Client connected: " + args.IpPort);
            Console.WriteLine("Disconnecting: " + args.IpPort);
            server.DisconnectClient(args.IpPort);
        }         
```

Publishing commit and new version to NuGet momentarily.

**Comment by jchristn** [comment]
NuGet v4.1.9: https://www.nuget.org/packages/WatsonTcp/4.1.9
Commit: https://github.com/jchristn/WatsonTcp/commit/5dec60b8b6eb8cc14598b9552b3d2c851d3454c2

@Motridox thank you for filing this; this should fix it.  Please re-open if it does not.  Thanks!
