### ISSUE TITLE
WatsonTcpClient.Dispose() disposes resources used by the MonitorForExpiredSyncResponses() task resulting in System.NullReferenceException

### ISSUE THREAD

**Issue by leviculus** [jchristn/WatsonTcp#82]
I've come into a new project that calls Dispose on a WatsonTcpClient after a System.TimeoutException from a WatsonTcpClient.Start() call. This results in a System.NullReferenceException as I think the MonitorForExpiredSyncResponses() function is referencing disposed objects after its wait expires.

My apologies if calling Dispose post a client connection failure is not supported or recommended and therefore this issue is non-existent.

Example to trigger issue.

```C#
class Program
{
    static void Main(string[] args)
    {

        Task.Run(() =>
        {
            WatsonTcpClient client = new WatsonTcpClient("10.1.2.3", 1234); // NonExistant Server

            client.ServerConnected += HandleServerConnected;
            client.ServerDisconnected += HandleServerDisconnected;
            client.MessageReceived += HandleMessageReceived;

            try
            {
                Console.WriteLine("Starting Client");
                client.Start();
            }
            catch (Exception ex)
            {
                Console.WriteLine("Exception: {0}", ex.Message);
                client.Dispose();
            }
        });
      
        Console.WriteLine("Waiting on NullReferenceException");
        Thread.Sleep(10000);
    }

    static void HandleServerConnected(object sender, EventArgs e)
    {
        Console.WriteLine("Server Connected");
    }
    static void HandleServerDisconnected(object sender, EventArgs e)
    {
        Console.WriteLine("Server Disconnected");
    }
    static void HandleMessageReceived(object sender, MessageReceivedFromServerEventArgs e)
    {
        Console.WriteLine("Message Recieved");
    }
}
```

**Comment by jchristn** [comment]
Hi @leviculus I posted an update earlier this morning for that exact issue. What version are you using? Have you tried with the update from this morning? Cheers

**Comment by leviculus** [comment]
Thanks for getting back to me so quick @jchristn !

The test code above runs using 4.1.12 as well I've updated the project I've inherited to 4.1.12 with the exception still being thrown

**Comment by jchristn** [comment]
Thanks - do you have anything keeping the client open after the task has finished executing?  It looks like it is being disposed after completion of the task; I don't see anything there to keep it open or long-lived.

**Comment by jchristn** [comment]
I just added another project called ```Test.NonExistentServer``` with this code and I get the expected timeout exception:
```
C:\Code\Watson\WatsonTcp-4.1>Test.NonExistentServer\bin\Debug\netcoreapp3.1\Test.NonExistentServer.exe
Waiting on NullReferenceException
Starting Client
Exception: Timeout connecting to 10.1.2.3:1234
```

I also tried running using Visual Studio Debugger, same result.

![image](https://user-images.githubusercontent.com/1421081/85788158-5f3dbd80-b6e1-11ea-942c-421e14d918bb.png)

**Comment by jchristn** [comment]
Are you using .NET Framework or .NET Core?  Version?  Windows/Mac/Linux?

**Comment by leviculus** [comment]
Sorry, I should have included that from the beginning. The test code above was run on Windows 10, .Net Core 3.1

The project I'm working on targets .NET Framework 4.8 also running on Windows 10

**Comment by jchristn** [comment]
Weird.  I'm also using Windows 10 and tested the above using .NET Core 3.1...  

Could you send me a screenshot showing the exception?

**Comment by leviculus** [comment]
The exception details I'm seeing, screenshots coming

'''
$exception	{"Object reference not set to an instance of an object."}	System.NullReferenceException
Data	{System.Collections.ListDictionaryInternal}	System.Collections.IDictionary {System.Collections.ListDictionaryInternal}
HResult	-2147467261	int
HelpLink	null	string
InnerException	null	System.Exception
Message	"Object reference not set to an instance of an object."	string
SerializationRemoteStackTraceString	null	string
SerializationStackTraceString	"   at WatsonTcp.WatsonTcpClient.MonitorForExpiredSyncResponses()"	string
SerializationWatsonBuckets	null	object
Source	"WatsonTcp"	string
StackTrace	"   at WatsonTcp.WatsonTcpClient.<MonitorForExpiredSyncResponses>d__107.MoveNext()"	string
TargetSite	{Void MoveNext()}	System.Reflection.MethodBase {System.Reflection.RuntimeMethodInfo}
_HResult	-2147467261	int
_data	{System.Collections.ListDictionaryInternal}	System.Collections.IDictionary {System.Collections.ListDictionaryInternal}
_dynamicMethods	null	object
_exceptionMethod	null	System.Reflection.MethodBase
_helpURL	null	string
_innerException	null	System.Exception
_ipForWatsonBuckets	0x00007ffbf4b4a209	System.UIntPtr
_message	"Object reference not set to an instance of an object."	string
_remoteStackTraceString	null	string
_source	null	string
_stackTrace	{sbyte[48]}	object {sbyte[]}
_stackTraceString	null	string
_watsonBuckets	null	object
_xcode	-532462766	int
_xptrs	0x0000000000000000	System.IntPtr
Static members		

'''

**Comment by leviculus** [comment]
Test code Exception:
![TestException](https://user-images.githubusercontent.com/4295366/85790668-1fe29180-b720-11ea-920e-aa4f53e9d610.PNG)

Project Exception:
![ProjectException](https://user-images.githubusercontent.com/4295366/85790679-27a23600-b720-11ea-9801-4e34f33a6193.PNG)

**Comment by leviculus** [comment]
This change seems to fix my issue. I don't think it would introduce additional errors but your expertise will be a better decider of that!

```
diff --git a/WatsonTcp/WatsonTcpClient.cs b/WatsonTcp/WatsonTcpClient.cs
index c42f60d..b30268e 100644
--- a/WatsonTcp/WatsonTcpClient.cs
+++ b/WatsonTcp/WatsonTcpClient.cs
@@ -1508,12 +1508,10 @@ namespace WatsonTcp
          
         private async Task MonitorForExpiredSyncResponses()
         {
-            while (!_TokenSource.IsCancellationRequested)
+            while (!(_TokenSource is null) && !_TokenSource.IsCancellationRequested)
             {
                 if (_Token.IsCancellationRequested) break;
 
-                await Task.Delay(1000);
-
                 lock (_SyncResponseLock)
                 { 
                     if (_SyncResponses.Any(s => 
@@ -1531,6 +1529,8 @@ namespace WatsonTcp
                         }
                     }
                 }
+
+                await Task.Delay(1000);
             }
         }
 

```

**Comment by jchristn** [comment]
Hi @leviculus wow, thank you for tracking this down!  I uploaded v4.1.12.1 to NuGet: https://www.nuget.org/packages/WatsonTcp/4.1.12.1

The commit is here: https://github.com/jchristn/WatsonTcp/commit/b25ef80a026704646c6e97a0323cd76a9363efa4

Please re-open if this needs to be amended.  Really appreciate you identifying the source here.

**Comment by leviculus** [comment]
@jchristn You're welcome! Thank you for following up so quickly, you've made a great library and its very helpful so thank you!
