### ISSUE TITLE
Message content mixing when sending big message with send and a lot of small messages with sendandwait

### ISSUE THREAD

**Issue by ozrecsec** [jchristn/WatsonTcp#86]
Hi,
sometimes in my project I'm getting in a problem of data transmission.

The situation is:
- the server sends (with Send method) to one client a big message (a string representing a list o 3000 objects serialized with json, about 10MB of data) 
- at the same time, in another thread the server sends to the same client a request with SendAndWait
- the client receives the BIG message but the data received contains also the string of the other message (sent with SendandWait) and throws an exception when deserializing
- the request SendAndWait never receives response and goes in timeout

here below the portion of big message with inside the other message
...................{"Number":2,"Title":"Fine","pageFrom":11,"pageTo":100}]},{"Title":"Libro 7287 delle 30/07/2020 09:43:35","Author":"io","Pag{"Status":"Normal","SyncRequest":true,"SyncResponse":false,"SenderTimestamp":"2020-07-30T09:43:37.6117071+02:00","Expiration":"2020-07-30T09:44:07.6117071+02:00","ConversationGuid":"4f7112b9-df28-4ee0-926f-f2ac79b18812","Compression":"None","ContentLength":84,"Metadata":{"MT":"RqtBASEPing","PT":"Generic"}}

es":100,"Chapters":[{"Number":1,"Title":"Inizio","pageFrom":1,"pageTo":10},{"Number":2,"Title":"Fine"............................

this happens with WatsonTCP version 4.1.12.6

In my application I solved with a mutually exclusive lock to avoid parallel sending to the same client.

Methods to permit only one sending at time for the same IpPort

        private List<string> _clientsSending= new List<string>();
        private void StartClientSending(string ipPort)
        {
            bool added = false;
            while (!added)
            {
                lock (_clientsSending)
                {
                    if (!_clientsSending.Contains(ipPort))
                    {
                        _clientsSending.Add(ipPort);
                        added = true;
                    }
                }
                if (!added)
                {
                    //it's already sending, so i wait some time to retry
                    System.Threading.Thread.Sleep(50);
                }
            }
        }

        private void EndClientSending(string ipPort)
        {
            lock (_clientsSending)
            {
                int idx = _clientsSending.IndexOf(ipPort);
                if (idx >= 0)
                    _clientsSending.RemoveAt(idx);
            }
        }

When I send a request 
            StartClientSending(ipPort);
            SyncResponse rsp = server.SendAndWait(ipPort, meta, _defaultTimeoutCalls, serializedPacket);
            EndClientSending(ipPort);

When I send a message
            StartClientSending(ipPort);
            server.Send(ipPort, meta, serializedPacket);
            EndClientSending(ipPort);

Have you a smarter solution for this message mixing? :-)
many thank for attention

**Comment by jchristn** [comment]
Hi @ozrecsec thanks for bringing this up.  It definitely should **not** be happening.  There are locks within both the client and server libraries that **should** prevent this, so I will definitely look into this right away.

Does this happen only from server to client, or have you tried the reverse direction as well?

Thanks, Joel

**Comment by ozrecsec** [comment]
no, I'm sorry, i've tested this only from server to client.
maybe in the next hour I can do the test from client to server.

**Comment by jchristn** [comment]
That's ok @ozrecsec - appreciate you bringing this up.  I'm investigating now.  I think it has to do with use of ```SemaphoreSlim``` internally instead of a simple ```lock```.

**Comment by jchristn** [comment]
Hi @ozrecsec I was able to reproduce this, quite quickly, by including ```SendAndWait``` calls in my ```Test.MultiThread``` project.
```
C:\Code\Watson\WatsonTcp-4.1\Test.MultiThread\bin\Debug\net461>test.multithread
Large Data MD5: F1C9645DBC14EFDDC7D8A322685F26EB
Small Data MD5: F09F35A5637839458E462E6350ECBCE4
Starting in 3 seconds...
[WatsonTcpServer] Starting on 0.0.0.0:8000
[WatsonTcpClient] Connecting to localhost:8000
[WatsonTcpClient] Connected to server, starting data receiver
[WatsonTcpServer] Accepted connection from 127.0.0.1:60929
[WatsonTcpServer] Starting data receiver for 127.0.0.1:60929
[server] connection from 127.0.0.1:60929
Press ENTER to exit
[async] Data MD5 validation success: F1C9645DBC14EFDDC7D8A322685F26EB
[async] Data MD5 validation success: F1C9645DBC14EFDDC7D8A322685F26EB
[async] Data MD5 validation success: F1C9645DBC14EFDDC7D8A322685F26EB
[async] Data MD5 validation success: F1C9645DBC14EFDDC7D8A322685F26EB
[sync ] Data MD5 validation success: F09F35A5637839458E462E6350ECBCE4
[sync ] Data MD5 validation success: F09F35A5637839458E462E6350ECBCE4
[sync ] Data MD5 validation success: F09F35A5637839458E462E6350ECBCE4
[sync ] Data MD5 validation success: F09F35A5637839458E462E6350ECBCE4
[async] Data MD5 validation success: F09F35A5637839458E462E6350ECBCE4
[async] Data MD5 validation success: F09F35A5637839458E462E6350ECBCE4
[async] Data MD5 validation success: F09F35A5637839458E462E6350ECBCE4
[async] Data MD5 validation success: F1C9645DBC14EFDDC7D8A322685F26EB
[async] Data MD5 validation success: F09F35A5637839458E462E6350ECBCE4
[async] Data MD5 validation success: F1C9645DBC14EFDDC7D8A322685F26EB
[async] Data MD5 validation success: F1C9645DBC14EFDDC7D8A322685F26EB
[async] Data MD5 validation success: F1C9645DBC14EFDDC7D8A322685F26EB
[async] Data MD5 validation success: F09F35A5637839458E462E6350ECBCE4
[async] Data MD5 validation success: F09F35A5637839458E462E6350ECBCE4
[async] Data MD5 validation success: F09F35A5637839458E462E6350ECBCE4
[sync ] Data MD5 validation success: F09F35A5637839458E462E6350ECBCE4
[async] Data MD5 validation success: F09F35A5637839458E462E6350ECBCE4
[sync ] Data MD5 validation success: F09F35A5637839458E462E6350ECBCE4
[sync ] Data MD5 validation success: F09F35A5637839458E462E6350ECBCE4
[sync ] Data MD5 validation success: F09F35A5637839458E462E6350ECBCE4
[async] Data MD5 validation success: F1C9645DBC14EFDDC7D8A322685F26EB
[async] Data MD5 validation success: F1C9645DBC14EFDDC7D8A322685F26EB
[sync ] Data MD5 validation success: F09F35A5637839458E462E6350ECBCE4
[async] Data MD5 validation failed
```
I'll be working on this today!  Thanks

**Comment by ozrecsec** [comment]
I've tested the client and it works fine.
the problem seems to be only on server side.

**Comment by jchristn** [comment]
Hi @ozrecsec I've implemented a solution similar to yours that I'll be incorporating into the next commit and push to NuGet.  I'm not sure what I've done wrong with my ```SemaphoreSlim``` implementation, but it is indeed a problem.  Will report back when it's updated!  Cheers, Joel

**Comment by ozrecsec** [comment]
Thank you so much for the speed :-) 
Next week I'm in holyday so I get and test the new version in 10 days...

thanks again

**Comment by jchristn** [comment]
Hi @ozrecsec I've published an update.  You can find the commit here: https://github.com/jchristn/WatsonTcp/commit/a59ceddba83493a109270f04ca543b3db9f23e96

And the NuGet package here: https://www.nuget.org/packages/WatsonTcp/4.1.12.7

Please re-open if this doesn't address the issue for you!  Also please check out Test.MultiThread, I've amended it to make it better test this issue.  

Thanks for making the library better!
