### ISSUE TITLE
Overlapping data

### ISSUE THREAD

**Issue by Crushedice** [jchristn/WatsonTcp#87]
Greetings.
So far, didnt had any problems anymore until now.
Im working atm on a tool for our staff that includes a bunch of functions,
most of them using the watsonTCP for communication.
Now i noticed, sometimes, some code runs faster then the other, and both using SendAsync.
It can happen that the client then receives both streams and merge them together, which makes no sense anymore for the client and throws an exception.
Now im sure the most obvious step todo here would be re-code my stuff to make sure its one after another...
But as i already build it this way i just wanted to ask if there isnt any way to "Catch" an incomming stream and process this on another task ?   something like this pseudo code- 
```
 static async Task CatchStream(object sender, StreamReceivedFromServerEventArgs args)
    {
       //Move the used code from Stream Received into here, and be ready for any other incomming streams
    }

    private static void StreamReceived(object sender, StreamReceivedFromServerEventArgs args)
    {
        Task.Run((() => CatchStream(sender, args)));
    }
```
i know this doesnt work like i wrote it,  but thats the basic idea.  

Thanks . crushed

**Comment by jchristn** [comment]
Hi @Crushedice can you use MessageReceived?  It fully reads the data out of the stream then fires the even whereas StreamReceived passes the underlying stream and blocks until finished. 

Alternatively I could add another event like MessageReceived but fully read the data out into a MemoryStream and pass that to you (but that's what MessageReceived already does, except it gives you the byte array). 

MessageReceived doesn't block BTW. 

Let me know your thoughts. 

Cheers, Joel

**Comment by Job79** [comment]
Best solution would be sending the length of the stream. This way you know the end of every stream.
But then it is no longer possible to send streams with an unknown length.

So best solution would be writing an extension for this problem, that would do the following:

Send
- Send length of stream (8 bytes)
- Send stream

Receive (receive into other stream for really big data)
- Receive length of stream
- Receive stream (loop with buffer)

This won't be not to hard to implement, however, there is another bug(or feature?) that makes this impossible.
The header that is meant for messages is send when sending 2 streams in a short time.
Code to reproduce: (linux)
```cs
await using var stream = new MemoryStream(Encoding.UTF8.GetBytes("Test data"));
            await using var stream2 = new MemoryStream(Encoding.UTF8.GetBytes("Test data"));
            
            using var watsonServer = new WatsonTcpServer("127.0.0.1", 9999);
            watsonServer.StreamReceived += (sender, stream) =>
            {
                byte[] receivedData = new byte[1024];
                stream.DataStream.Read(receivedData);
                Console.WriteLine(Encoding.UTF8.GetString(receivedData));
            };
            watsonServer.Start();
            await Task.Delay(100);

            var client = new WatsonTcpClient("127.0.0.1", 9999);
            client.StreamReceived += (sender, stream) => Console.WriteLine("Client received stream!");
            client.Start();

            await client.SendAsync(stream.Length, stream);
            // await Task.Delay(100); Fix
            await client.SendAsync(stream2.Length, stream2);
            await Task.Delay(-1);
```
And output:
```
Test data{"Status":"Normal","SyncRequest":false,"SyncResponse":false,"Compression":"None","ContentLength":9,"Metadata":{}}

Test data
```


<br/><br/><br/>
And here the extension I tried to write but couldn't finish, and probably doesn't work:
```cs
static class StreamExtension
    {
        public static async Task SendStream(this WatsonTcpClient client, Stream stream, bool sendLengthPrefix = true)
        {
            if (!stream.CanRead) throw new InvalidDataException("Stream is not readable");

            if (sendLengthPrefix)
            {
                await using var lengthStream = new MemoryStream(BitConverter.GetBytes(stream.Length));
                await client.SendAsync(lengthStream.Length, lengthStream);
            }

            await client.SendAsync(stream.Length, stream);
        }

        public static void ReceiveStream(this StreamReceivedFromClientEventArgs receivedStream, Stream stream, long count = 0)
        {
            if (!stream.CanWrite) throw new InvalidDataException("Stream is not writable");

            //Get length of stream
            if (count == 0)
            {
                var length = new byte[8];
                receivedStream.DataStream.Read(length);
                count = BitConverter.ToInt64(length, 0);
            }

            var buffer = new byte[1024];
            long totalReceivedBytes = 0;
            int read;

            while (totalReceivedBytes < count &&
                   (read = receivedStream.DataStream.Read(buffer, 0, (int)Math.Min(1024, count - totalReceivedBytes))) > 0)
            {
                stream.Write(buffer, 0, read);
                totalReceivedBytes += read;
            }
            
            if (stream.CanSeek) stream.Seek(0, SeekOrigin.Begin);
        }
```

**Comment by Crushedice** [comment]
True.  this i have happen in my code as well. 
Sometimes, the internal header is taken into the message that i sent , 
and , in this case.  will be displayed in the internal Chat feature of the app. 
Nothing too severe that it breaks stuff.  but confusing nonetheless

**Comment by jchristn** [comment]
Hi @Job79 in which version did you reproduce this?  I added a fix for this issue in 4.1.12.x.  It had to do with ```SemaphoreSlim``` not behaving the way I was expecting within the previous design.

**Comment by Crushedice** [comment]
Interesting. I didnt knew about the Data wrapper.  
And yes. true,  sometimes the method did read into the next header and messed up.
So, using the supplied "Data" byte array this wont happen?  how would i implement this?  
Currently i did stick to the example projects with the method.

I just tried to commend the so far used method out and use args.data, which im sure is the wrong approach . 
->
```

 private static void StreamReceived(object sender, StreamReceivedFromServerEventArgs args)
    {

      

        string MessageCollect = string.Empty;
        try
        {
            int bytesRead = 0;
            int bufferSize = 65536;
            byte[] buffer = new byte[bufferSize];
            long bytesRemaining = args.ContentLength;
          

            if(args.DataStream != null && args.DataStream.CanRead)
            {
                //while(bytesRemaining > 0)
                //{
                //    bytesRead = args.DataStream.Read(buffer, 0, buffer.Length);
                //    
                //
                //    if(bytesRead > 0)
                //    {
                //        byte[] consoleBuffer = new byte[bytesRead];
                //        Buffer.BlockCopy(buffer, 0, consoleBuffer, 0, bytesRead);
                //        MessageCollect += (Encoding.UTF8.GetString(consoleBuffer));
                //    }
                //
                //
                //    bytesRemaining -= bytesRead;
                //}
                   
                    MessageCollect  = Encoding.UTF8.GetString(args.Data);
            }
            if(args.Metadata != null && args.Metadata.Count > 0)
            {
                string Header = args.Metadata.Keys.First().ToString();
                AddNewEntry($"New Header:{Header}");
                HeaderMsgReceived(Header, MessageCollect);
                return;
            } else
            {
                AddNewEntry($"MSG without Header");
                ProcessStream(MessageCollect);
            }
               
        } catch(Exception e)
        {
            AddNewEntry($"error in getting stream \n {e.Message}");
        }
    }
```

**Comment by Crushedice** [comment]
Just now as Edit to the problem i got.
I Just found, while debugging some issue i got already a bunch of times, where the connection just dropped.
After now some time searching, i found, that WatsonTCP had problems with the Json data i did send, as some of the characters were invalid ( weird symbols etc. that players used in their usernames ) 

After some more time i now got a small method together to filter this out, maybe it proves use full for some of you . 

```
 static string CleanInput(string strIn)
        {
            try
            {
                return Regex.Replace(strIn, @"[^a-zA-Z0-9`!@#$%^&*()_+|\-=\\{}\[\]:"""";'<>?,.\ \/]", "",
                    RegexOptions.None, TimeSpan.FromSeconds(5.5));
            }
            catch (RegexMatchTimeoutException)
            {
                return String.Empty;
            }
        }

```


Sooo far.  It - atleast - solved some of my problems i had .

**Comment by jchristn** [comment]
Hi @Crushedice using the ```.Data``` wrapper within the ```StreamReceivedFrom*EventArgs``` object is functionally equivalent to using the ```MessageReceived``` event as opposed to the ```StreamReceived``` event.  

StreamReceived is primarily used when you're going to be receiving large amounts of data whereas MessageReceived should be used when receiving manageable message sizes (up to tens of megabytes).  The main differences are:

- StreamReceived expects you to read up to a specific number of bytes from the underlying network stream directly
- MessageReceived does this for you
- If you use the Data property in StreamReceived (and not touch the DataStream property) it behaves just like MessageReceived

It appears to me that something is reading too far into the stream, which creates problems with framing.  Could you try using MessageReceived and make sure compression is set to None on both client and server?  Also if you could send a sample of the JSON you send that would be helpful.

**Comment by Crushedice** [comment]
Okay.  It seems like it likes the " MessageReceived " event more. 
Or better said,  with the somewhat fast data exchange , its not that good to process the stream myself . As there is a high probablility of hikkups. 
Good. 
I was used to using the stream received from my other application, where i  use it atm as an update system for our players with remote delta compression.  Big files,  Sent-one after another.

Good Good.  
Thank you very much for that. 

Ps-( the Json was  not corrupt, i specially added the regex now for this aswell, the stream did just read into the next json...)

**Comment by jchristn** [comment]
Hi @Crushedice 

I committed v4.2.0 just now (https://github.com/jchristn/WatsonTcp/commit/89dd514ce50cbca39051413ec7f0d8aec3b8405b) and published to NuGet (https://www.nuget.org/packages/WatsonTcp/4.2.0).  

There are a couple key changes:

1) You shouldn't be able to 'over-read' now when using streams, i.e. reading too many bytes and getting into the next message's header; this is applicable to when integrating using ```StreamReceived``` instead of ```MessageReceived```, and
2) Compression is gone, for now; it was causing too many problems across multiple OS and runtimes

I plan to re-add compression back in soon, but using an over-the-top model instead of something that encapsulates the underlying data stream.  

Cheers, Joel
