### ISSUE TITLE
SSL client certificate authentication?

### ISSUE THREAD

**Issue by brudo** [jchristn/WatsonTcp#9]
Can you confirm, does the new SSL support include client certificate Authentication? If so, can you document how that is configured? If not, can it be implemented as a feature request?

**Comment by jchristn** [comment]
Hi @brudo yes indeed, WatsonTcp does support SSL client authentication.  I'll add an example to the README right now.  Thanks!

**Comment by jchristn** [comment]
Just posted a README update.  Please let me know if this helps clarify.

**Comment by brudo** [comment]
I think I see that it supports using a password-protected .pfx file, and can authenticate that the server reached by the client is using the certificate expected by the client. I was actually asking about client certificates, where the client also proves its identity to the server.

**Comment by jchristn** [comment]
Hi @brudo , isn't that what this does?

```
Ssl.AuthenticateAsClient(ServerIp, SslCertificateCollection, SslProtocols.Tls12, !AcceptInvalidCerts);
```

**Comment by brudo** [comment]
Not an expert @jchristn but I think there is more to it than that, e.g.
probably involving two certificates, and possibly checking
IsMutuallyAuthenticated after AuthenticateAsClient. If this feature doesn't
get implemented it's OK; client certificate authentication is a bit
esoteric and in many cases can be replaced with application-level
authentication over an encrypted channel...

On Mar 27, 2017 2:08 PM, "Joel Christner" <notifications@github.com> wrote:

Hi @brudo <https://github.com/brudo> , isn't that what this does?

Ssl.AuthenticateAsClient(ServerIp, SslCertificateCollection,
SslProtocols.Tls12, !AcceptInvalidCerts);

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/jchristn/WatsonTcp/issues/9#issuecomment-289586675>,
or mute
the thread

**Comment by jchristn** [comment]
Hi @brudo I think I see what you mean.  From what I gather, AuthenticateAsClient will start authentication from the server side, and AuthenticateAsServer will start authentication from the server side, but it seems I may need to also check whether or not both sides of authentication succeeded (at least from what I see here: http://stackoverflow.com/questions/13667018/sslstream-mutual-authentication).

Thanks for the heads-up on this, I'll be sure to get this added ASAP!

**Comment by jchristn** [comment]
Hi @brudo just added this and updated NuGet to v1.1.2.  It added a constructor change to both WatsonTcpSslClient and WatsonTcpSslServer, so I left v1.1.1 in NuGet as well.  Please let me know if you agree with the changes!

**Comment by jchristn** [comment]
Closing - feel free to re-open if any issues!

**Comment by brudo** [comment]
Thanks very much. I think that does it although as I said I'm no expert.
