### ISSUE TITLE
WatsonTCP Client disconnects instantly.

### ISSUE THREAD

**Issue by cal3432** [jchristn/WatsonTcp#90]
Similar to #62 but have followed instructions on that issue and still have the problem.

OS: Windows 10 LTS
Screenshots:
![image](https://user-images.githubusercontent.com/57721560/90058603-d6530380-dcd9-11ea-86e9-8f50b9596188.png)

Our code:
```cs
// Start the server:
public void Start(ushort port = 52512, string name = "My Server", string password = "", ushort maxplayers = 10)
        {
            Password = password;
            MaxPlayers = maxplayers;
            Port = port;
            server = new WatsonTcpServer(null, Port);
            server.ClientConnected += ClientConnected;
            server.ClientDisconnected += ClientDisconnected;
            server.MessageReceived += MessageReceived;
            server.StreamReceived += StreamRecieved;
            server.SyncRequestReceived = SyncRequestReceived;
            server.Start();
            Logging.Info($"[Server] Server started.");

            Logging.Info("[Server] Load/Create ServerData");
            serverdata = new ServerData(name);
        }
```

```cs
// Connect to the server:
public void Connect(string ip, ushort port = 52512, string password = "", Helpers.UserRole userRole = Helpers.UserRole.Client)
        {
            client = new WatsonTcpClient(ip, port);
            client.ServerConnected += ServerConnected;
            client.ServerDisconnected += ServerDisconnected;
            client.MessageReceived += MessageReceived;
            client.SyncRequestReceived = SyncRequestReceived;
            client.Start();
            if (client.Connected)
                Login(password);
            else
                Logging.Warn("[Client] Couldn't connect to the server!");
        }
```

**Comment by cal3432** [comment]
Could it be we haven't set a handler in the client class? We get no errors in our Unity Log file and it acts like its a normal feature.

**Comment by jchristn** [comment]
Hi @cal3432 it looks like you have your event handlers set, but you only need one of StreamReceived or MessageReceived.

Could you set ```server.DebugMessages = true``` and ```client.DebugMessages = true```, as well as ```server.Logger = Console.WriteLine``` and ```client.Logger = Console.WriteLine```?  And then post the output from both client and server?

It **appears** at first glance that the client is being disposed, perhaps it's in a variable that's being garbage collected.

**Comment by cal3432** [comment]
Sure, i'll get the logs. :+1:

**Comment by cal3432** [comment]
![image](https://user-images.githubusercontent.com/57721560/90063845-dc4ce280-dce1-11ea-8205-d2232ac22492.png)

Logs ^

Blue [Multiplayer] is the client.

I can see from here there is a IOexception.

**Comment by jchristn** [comment]
Do you have the client logs as well?

**Comment by daredloco** [comment]
I made the client.DebugMessages = true and client.Logger to an own logger class, this is the output:

![big](https://user-images.githubusercontent.com/60240491/90065449-af3d0780-dcc2-11ea-962a-e6c0c2566c67.jpg)

This happens at the moment the client disconnects and on Windows 8.1. Seems like there is a problem with Newtonsoft.Json

It's the same code as cal3432s

**Comment by cal3432** [comment]
Same with windows 10, and Proton on linux

**Comment by jchristn** [comment]
Thanks @daredloco and @cal3432 - does the client send any data to the server prior to disconnection?  Watson uses Newtonsoft.Json for header serialization.  Since it is a ```System.IO.FileNotFoundException```, I'm wondering if perhaps the DLL could not be found?  

You mention Windows 10 and Proton when running on Linux - is it .NET Core or .NET Framework?  

If .NET Framework, do you see the file ```Newtonsoft.Json.dll``` in the application directory?  

If .NET Core, do you see something similar to the following in your application's ```.deps.json``` file?
```
  "libraries": { 
    "Newtonsoft.Json/12.0.3": {
      "type": "package",
      "serviceable": true,
      "sha512": "sha512-6mgjfnRB4jKMlzHSl+VD+oUc1IebOZabkbyWj2RiTgWwYPPuaK1H97G1sHqGwPlS5npiF5Q0OrxN1wni2n5QWg==",
      "path": "newtonsoft.json/12.0.3",
      "hashPath": "newtonsoft.json.12.0.3.nupkg.sha512"
    },
    "WatsonTcp/4.2.0": {
      "type": "project",
      "serviceable": false,
      "sha512": ""
    }
  }
```

Also, what version of WatsonTcp are you using?

Sorry for the billions of questions.  We'll get to the bottom of this.  Thanks, Joel

**Comment by cal3432** [comment]
Its .Net Framework 3.5 running with Unity.

Newtonsoft JSON is present as we have other uses for it.

**Comment by jchristn** [comment]
Ok.  I've never tried running WatsonTcp on .NET Framework 3.5.  It's targeted to .NET Framework 4.6.1 (and .NET Standard 2.0).  

What is the WatsonTcp version you are using?  And the version of Newtonsoft.Json that you're using for other purposes?  

I'm going to spin up a test project on .NET Framework 3.5 right now to see if there are any glaring issues.

**Comment by jchristn** [comment]
Did you clone and retarget to .NET Framework 3.5?  
![image](https://user-images.githubusercontent.com/1421081/90074522-4cdb0b80-dcb0-11ea-8d27-063de0f98e9b.png)

**Comment by cal3432** [comment]
It seems watsonTCP doesn't support 3.5, a shit ton of errors showed up when I opened watsonTCP in 3.5 targeted environment.

No problem, we switched to Telepathy which has better Unity support.
