### ISSUE TITLE
How to only receive the body messege

### ISSUE THREAD

**Issue by bianshifeng** [jchristn/WatsonTcp#92]
When I send the Json string form server to client,  I received the header msg and body msg mixed together

![20200905001601](https://user-images.githubusercontent.com/3129676/92261885-d75c0700-ef0c-11ea-8b44-baaf1e6c7633.jpg)

I only need the body json string

**Comment by jchristn** [comment]
Are you using WatsonTcp for both client and server?

**Comment by jchristn** [comment]
Hi @bianshifeng are you using WatsonTcp for both client and server or are you using something else?

**Comment by jchristn** [comment]
Closing this as I'm making the assumption that you were using WatsonTcp only for the server, and not for the client.  WatsonTcp has its own mechanism for framing, which most need to build to support application-layer message delivery between processes.  That also means both sides must be aware of the framing, meaning you cannot use a generic TCP client with WatsonTcp. 

If you need a simpler implementation, please refer to SimpleTcp (https://github.com/jchristn/simpletcp), CavemanTcp (https://github.com/jchristn/cavemantcp), or EasyTcp (https://github.com/Job79/EasyTcp)

Please re-open if I'm mistaken and you were indeed using WatsonTcp for both client and server.
