### ISSUE TITLE
[WatsonMessage] BuildStream IOexception, disconnect detected

### ISSUE THREAD

**Issue by xenioo** [jchristn/WatsonTcp#94]
I've several client connected to a server. Everything works fine except for one client.

This client once connected, get disconnected immediately. Then it tries to reconnect, connect succesfully again, and then get disconnected again. This continues for 20 minutes or so, then remain connected and quite stable.

Enabling all the logs on the client, I see:
...
[WatsonMessage] BuildFromStream header processing complete
[WatsonTcpClient] Authentication successful
[WatsonMessage] BuildStream IOexception, disconnect detected
[WatsonTcpClient] Message build failed due to disconnect
[WatsonTcpClient] Data receiver terminated
...

What it could be?

**Comment by jchristn** [comment]
Hi @xenioo this is interesting.  Are all clients the same code or different?  If they are all the same code, then what I'd want to do is amend ```WatsonMessage``` to throw the ```IOException``` so we could see why it's happening.

Out of curiosity, on the server-side process, how is the thread count, CPU utilization, and memory utilization?  How does the CPU/memory utilization compare against your local system resources?  

i.e. from Task Manager:
![image](https://user-images.githubusercontent.com/1421081/93912082-1f727c00-fcb8-11ea-8c7a-243b2d7c39e0.png)

**Comment by xenioo** [comment]
All clients use the same code.

On the server side, the server is a .net core running both http api and tcp server. The server process is occupying low resources, both in terms of memory and cpu, so don't think the issues is around here.

Let's me explain in detail what the client does.

The client start with:

`Task.Factory.StartNew(() =>
            {
                while (true)
                {
                    if (_client == null || !_client.Connected)
                    {
                        if (!_connecting)
                        {
                            ConnectToServer();
                        }
                    }

                    Thread.Sleep(5000);

                    if (_token.IsCancellationRequested)
                        break;
                }
            },
            _token,
            TaskCreationOptions.None,
            TaskScheduler.Default);`


This is the ConnectToServer function:

`public static void ConnectToServer()
        {
            _connecting = true;

            Log.Information($"Connecting to ForexPos Console server at {AppConfig.ForexConsoleSocketAddress()}:{AppConfig.ForexConsoleSocketPort()}");

            try
            {
                if (_client != null)
                    _client.Dispose();

                _client = new WatsonTcpClient(AppConfig.ServerIp(), AppConfig.ServerPort());

                _client.Events.AuthenticationSucceeded += AuthenticationSucceeded;
                _client.Events.AuthenticationFailure += AuthenticationFailure;
                _client.Events.ServerConnected += ServerConnected;
                _client.Events.ServerDisconnected += ServerDisconnected;
                _client.Events.MessageReceived += MessageReceived;

                _client.Callbacks.AuthenticationRequested = AuthenticationRequested;
                _client.Callbacks.SyncRequestReceived = SyncRequestReceived;

                _client.Settings.DebugMessages = true;
                _client.Settings.Logger = Logger;

                _client.Keepalive.EnableTcpKeepAlives = true;
                _client.Keepalive.TcpKeepAliveInterval = 1;
                _client.Keepalive.TcpKeepAliveTime = 1;
                _client.Keepalive.TcpKeepAliveRetryCount = 3;

                Task clientStart = _client.StartAsync();

                Log.Information($"Connection is on: {_client.Connected}");
            }
            catch (Exception ex)
            {
                Log.Warning($"Failed to connect to server: {ex.Message}");
            }
            finally
            {
                _connecting = false;
            }
        }`

**Comment by xenioo** [comment]
If I remove the polling task from the client, client stay connected and disconnection does not happen.

Seems like that checking the client.Connected property is what causing the problem. Could it be?

Anyway,  in that case it happens that sometimes the client disconnect from the server but and I'm not be able to check it because the ServerDisconnected event is not fired.

**Comment by jchristn** [comment]
Hi @xenioo I'd recommend putting the ```client.Connect()``` into a separate method, and have the ```client.Events.ServerDisconnected``` event call the method to reconnect, rather than watching ```client.Connected```.  The problem with ```client.Connected``` is that it is not set to ```true``` until everything has been done post-TCP-setup.  i.e. starting background data receiver tasks, and so on.

If you choose to keep the polling loop using ```client.Connected```, I'd suggest putting a ```Task.Delay(100).Wait()``` in there or something to give the client background tasks an opportunity to start (and thus allow them to set ```client.Connected = true```.

Could you give that a try and see if it helps?

Cheers,
Joel

**Comment by xenioo** [comment]
Hi @jchristn,
i'll give a try to what you're suggesting for the polling loop.

About client.Connect(), i've already put my reconnect method into the ServerDisconnected event call, but I've noticed that clients become unreachable by the server (I know just by forcing a sendandwait call) without firing ServerDisconnected event.
So this is a problem, because not firing that event does not call the reconnect and that client remain lost.

What do you think could happen?

**Comment by jchristn** [comment]
Hi @xenioo to make sure I understand, the client thinks it is connected (the ```ServerDisconnected``` event doesn't fire) but the server can't reach it (because of failed/failing ```SendAndWait``` calls initiated by the server).  Is that correct?

Are all of the clients running on a single machine or multiple machines?  Is the server on a separate machine?  What I've often seen happen while testing is that the thread pool doesn't expand/contract to keep up with background task demands when everything is running on a single system.

**Comment by xenioo** [comment]
@jchristn yes, correct.

Each client is running in a single machine. The server in a separate machine.

**Comment by jchristn** [comment]
Got it.

Do you by chance have the source locally, or are you using the NuGet package?  If you have the source, we could remove 291...295 in ```WatsonMessage.cs``` to see the exception:

![image](https://user-images.githubusercontent.com/1421081/94041330-f537c180-fd7e-11ea-9c0b-0640a07406ce.png)

Alternatively I could add another property in both client and server that would force all exceptions to be logged.

**Comment by xenioo** [comment]
I'm using nuget, but I could download the sources and make the changes.

In fact, IOException was the error that is detected when I run the polling loop and cause repetitive reconnections.

**Comment by xenioo** [comment]
hi @jchristn, i've setup a test environment with the client running on my machine and connecting to the server running on a machine in the cloud.
I'm using the client version with the polling loop.

After 2 hours I've noticed that:
- client connect to the server succesfully
- immediate client disconnections does not happens and everything seems to work fine
- I try to send message from server to client, and client respond succesfully
- after something like 15/20 minutes, if I try to send a message to the client, the server does not receive any response because 
  the client is unreachable, probably disconnected.
  If I look at the client log, there are no signs of Server Disconnect event logs. Why?
  If I set a breakpoint into the client while is running, I see the client.Connected is always True. Why?

Any hint?

**Comment by jchristn** [comment]
Hi @xenioo on the last one, i.e. a breakpoint, I would assume that would prevent the background tasks that monitor the connections from running while it's in the breakpoint.  That would explain the last issue.

Are you using TCP keepalives?  I let client and server run for hours and am still able to exchange messages after prolonged periods of inactivity.  There are a lot of factors to consider such as network changes (interface up/down, connectivity loss, etc).  In your case, does the client still appear in the clients list on the server?

Did you test with the removal of the caught IOException to see what the exception was?  I have a feeling that will lead us to the source of your issue.

**Comment by xenioo** [comment]
hi @jchristn,

I did set up the breakpoint only after having seen that the server wasn't able to reach the client. Until then, the client was running without any stop or pause.

And setting up the breakpoint showed that the Connected property was set to True even if client unreachable.

Now I'm running a test session with keepalives configured on both client and server.

Next test will be removing IOException.

For my scenario it doesn't care if there are disconnections here and there. The important things is being able to intercept those disconnection so to be able to reconnect.

I'll get you updated.

**Comment by xenioo** [comment]
hi @jchristn ,
i've tested with the removal of the caught IOException like you said.

This is the error I get:

2020-09-24 11:12:28.671 +02:00 [DBG] [WatsonMessage] BuildStream exception: 
{
  "ClassName": "System.IO.IOException",
  "Message": "Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.",
  "Data": null,
  "InnerException": {
    "NativeErrorCode": 10060,
    "ClassName": "System.Net.Sockets.SocketException",
    "Message": "A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond",
    "Data": null,
    "InnerException": null,
    "HelpURL": null,
    "StackTraceString": "   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)",
    "RemoteStackTraceString": null,
    "RemoteStackIndex": 0,
    "ExceptionMethod": "8\nEndReceive\nSystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\nSystem.Net.Sockets.Socket\nInt32 EndReceive(System.IAsyncResult)",
    "HResult": -2147467259,
    "Source": "System",
    "WatsonBuckets": null
  },
  "HelpURL": null,
  "StackTraceString": "   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)\r\n   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at WatsonTcp.WatsonCommon.<ReadFromStreamAsync>d__3.MoveNext() in D:\\WatsonTcp-master\\WatsonTcp-master\\WatsonTcp\\WatsonCommon.cs:line 112\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at WatsonTcp.WatsonMessage.<BuildFromStream>d__33.MoveNext() in D:\\WatsonTcp-master\\WatsonTcp-master\\WatsonTcp\\WatsonMessage.cs:line 255",
  "RemoteStackTraceString": null,
  "RemoteStackIndex": 0,
  "ExceptionMethod": "8\nEndRead\nSystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\nSystem.Net.Sockets.NetworkStream\nInt32 EndRead(System.IAsyncResult)",
  "HResult": -2146232800,
  "Source": "System",
  "WatsonBuckets": null
}

2020-09-24 11:12:28.708 +02:00 [DBG] [WatsonTcpClient] Message build failed due to disconnect
2020-09-24 11:12:28.710 +02:00 [DBG] [WatsonTcpClient] Data receiver terminated
2020-09-24 11:12:28.716 +02:00 [INF] Server disconnected

**Comment by jchristn** [comment]
Thank you @xenioo - one of the unfortunate realities of building a messaging layer on top of an operating system's networking stack is that I'm stuck getting what they give me.  WatsonTcp uses the underlying OS TCP implementation and they tend to have weird behavior about when a connection is considered alive vs not and when it is torn down forcefully vs gracefully.  This seems to be a situation where the OS is reporting the socket alive to WatsonTcp for a period of time, even though the other side no longer considers it alive.  This is often due to some kind of network change in between client and server (but not always) and a FIN/RST packet is not received informing them to close gracefully or forcefully.

**Comment by xenioo** [comment]
Ok understood. So what are you suggesting? Is there a fix or a workaround you can work out in order to mitigate that issue?

**Comment by jchristn** [comment]
This is an issue that TCP keepalives is supposed to address, but doesn't do very reliably.  Another approach is to use application-layer heartbeats, where you maintain a timer/state of when the last heartbeat was sent and acknowledged.  It has its own problems though, for instance, it would be sharing the same connection as your actual application data, which could be problematic if you don't interleave messages or are sending large messages.  There are unfortunate corner cases in networking that can only be addressed by "waiting".  I'm open to any suggestions.

**Comment by xenioo** [comment]
Should tcp keepalives also be configured on the client? At the moment I've enabled keepalives only in the server.

**Comment by jchristn** [comment]
You can, in my testing I've only found it to work (somewhat) reliably server-side.  I haven't had any luck with clients actually using them.  I've tried with both Windows and Ubuntu - Windows with both .NET Framework 4.6.1 and .NET Core 3.1, and Ubuntu with .NET Core 3.1.  Really wish I could give you a better answer on this one.

**Comment by xenioo** [comment]
Not sure 100%, but maybe found how to remove the repetitive disconnection happening on some clients.

I've put a delay after the client.Start() and this seems to have fixed that issue

Task clientStart =_client.StartAsync();
Task.Delay(1000).Wait();

Need to monitor next few hours...

**Comment by jchristn** [comment]
Hi @xenioo are you still polling on ```client.Connected```?  If so adding the delay is definitely a good idea, since the ```Connected``` property isn't set until after all of the background work (starting data receiver, etc) is started.  Cheers

**Comment by xenioo** [comment]
@jchristn yes, i'm doing polling.

```
Task clientStart =_client.StartAsync();
Task.Delay(1000).Wait();
Log.Information($"Connection is on: {_client.Connected}");
```

Probably the issue, before inserting the Task.Delay, was the logging that was inspecting the _client.Connected property?

**Comment by jchristn** [comment]
Exactly.  The ```Connected``` property is set after a handful of internal items which take time.

**Comment by xenioo** [comment]
@jchristn don't want to annoy too much on that issues...but I've found another strange behaviour.

Clients are connected.

At some point, I see in the server log that 1 client disconnected. In this case, the polling loop in the client should trigger the reconnection of the client. Since the client didn't reconnect, I gave a look at the client log and found nothing: seems like that the client is considering still connected, that is client is having the Connected property still = true and no server disconnected event has been fired.

**Comment by jchristn** [comment]
Hi @xenioo not an annoyance at all - are you using TCP keepalives?  If so it could be that the server keepalives failed.  For some reason keepalives only seem to be working server-side and not client-side.  

It may be worthwhile to implement a heartbeat within your application, i.e. periodically sending a 'hello' and updating a timer within your app of when the last hello was received.  

WatsonTcp really only accounts for process termination (graceful or not) and partially through keepalives.  Intermediary network hiccups that leave the underlying TCP implementation thinking it is still connected leave WatsonTcp thinking it is still connected.  My hands are pretty tied on that unless I write my own TCP/IP stack :)

**Comment by xenioo** [comment]
@jchristn sending the hearbeat from the client, right?

**Comment by jchristn** [comment]
I'd do it from both sides to be safe.  

Are you sending large messages or small?  If large, be aware that messages are sent in series, and a heartbeat could get stuck behind a larger message.

**Comment by xenioo** [comment]
I'm sending small messages.

Anyway, I've implemented a second polling loop on the client that will send a hearbeat message every minute to the server.

Now, thanks to the yesterday's "task.delay" put just after being connected and thanks to the second polling loop, connections seems to be really stable and reliable.

**Comment by jchristn** [comment]
Thanks @xenioo glad to know that the client-initiated heartbeat is helping.  Closing this out for now.
