### ISSUE TITLE
WatsonMessage.BuildFromStream very slow

### ISSUE THREAD

**Issue by broms95** [jchristn/WatsonTcp#95]
Hi,

I have been using your very helpful WatsonTcp library for some simple TCP communications on a Raspberry Pi 4 and Zero.  It seems to have issues with overwhelming the CPU/Memory subsystems in one part of your library: WatsonMessage.BuildFromStream.  It was consuming more than 100% of the CPU on one of the cores and overflowing the TCP receive queue on a very modest amount of network communication (50 messages/second, 2KB each--its a realtime audio project).  

It looks like the code required to pull one byte in at a time and determine if it is the end of your message header is too much for these processors (although RPi4 is no slouch).  Locally, I modified the message serialization to just send the Status and ContentLength variables as a 5 byte binary chunk and then read this all at once.  This worked and dropped the Pi from 120% CPU usage to 30%.  Obviously you are trying to handle many more features in your library than my little test and want to robustly resync the message header frame, but I don't know if you want to investigate how that method handles pulling in bytes and converting it to a WatsonMessage.  It made a dramatic difference for me.

Regards,
Joe Broms
aptuner@gmail.com

**Comment by jchristn** [comment]
Hi @broms95 thank you so much for the kind words and thoughtful feedback.  

Originally I had been using a custom binary framing format which was much faster than what is in place today but not as extensible and really difficult for me to maintain.  This is what led me to moving to a JSON frame header, which of course lengthened the header substantially.

I have some ideas on things I can do to help address the issue you're experiencing with the library (prior to the modifications you made).
1) some of the header fields can be made nullable with a default null value (serializer won't include key/value pairs where the value is null) which could save some space
2) decorate the message class with shorter names for the header fields which would also save some space
3) modify some of the message class properties (i.e. user metadata) to be null by default and automatically initialize to a new dictionary during get operations

Let me see what I can do on my end and please let me know if you have any other suggestions!

Cheers, Joel

**Comment by broms95** [comment]
Sounds good.  Probably some more profiling in this area would guide this--I didn't really check if it was the 1-byte at a time call to convert the JSON string to a watson string is the culprit -- probably the 1 byte call.  It goes in and calls ReadFromStreamAsync which allocates a new byte array of stream buffer size then asks for 1 byte.  Seems overkill.  There's also multiple streams created and torn down here.  For a very simple header (status=normal, content length=45), it converts to 98 bytes or so -- that means all the buffer allocation, memory stream allocation, everything gets called 98 times.

suggestion #1
If you could figure out the minimum frame size in bytes, then read that all at once for your first time through the loop.

suggestion #2
Different super easy optimization is do not write out the default values in the JSON string.  I see
{"Status":"Normal","SyncRequest":false,"SyncResponse":false,"ContentLength":45,"Metadata":{}}\n\r\n\r
to
{"ContentLength":45}\n\r\n\r

which goes from 98 bytes to 24.

I doubt you want to break your message protocol, but you could use smaller names.
{"CL":45"}\n\r\n\r

which is 14 bytes.

suggestion #4: harder
Avoid the call to ReadFromStreamAsync and do it all in BuidFromStream with more object reuse or manual buffer management.  If you are willing to handle the extra logic/memory of a temporary buffer, then you could read all non-blocking bytes in one-shot.  You'll need to prepend those bytes onto the next header/data read call--no fun, but faster. 
 Avoids changing the protocol.

At minimum you could replace line: 
byte[] data = await WatsonCommon.ReadFromStreamAsync(_DataStream, 1, _ReadStreamBuffer);
with 
int read = await _DataStream.ReadAsync(buffer, 0, 1); <--- reuse same buffer = new byte[1] above loop if possible.

I suppose one last idea would be to read 4 bytes at a time and look for a /n or /r anywhere in the 4 bytes-- if detected, then you can slow down to 1 byte and finish reading the stream.

**Comment by jchristn** [comment]
Great suggestions Joe.  I don't mind using shorter names in the JSON as long as I rev the minor version at minimum.  Looking into this ASAP!

**Comment by jchristn** [comment]
Hi @broms95 let me know if this works out better for you!

v4.4 commit: https://github.com/jchristn/WatsonTcp/commit/22a324848848aebade9df3772de252544b92e4b7
NuGet: https://www.nuget.org/packages/WatsonTcp/4.4.0

I'll leave it for you to close if this helps with the issue, or let me know if this does the trick.

**Comment by broms95** [comment]
Looks good!
