### ISSUE TITLE
Server.Stop(); Function availability

### ISSUE THREAD

**Issue by Antwns** [jchristn/WatsonTcp#98]
Hello! Do you also have the Server.Stop(); function (To essentially stop listening without disposing the server/client) on this Nuget package as well? Or is it only available on SimpleTCP?  Would this feature be added in the future? Thanks in advance and have a good day! 😄

**Comment by jchristn** [comment]
Hi @Antwns sure do, it's in v4.4.  You have a good day as well!  Cheers, Joel
```
        /// <summary>
        /// Stop accepting connections.
        /// </summary>
        public void Stop()
        {
            if (!_IsListening) throw new InvalidOperationException("WatsonTcpServer is not running.");

            _IsListening = false;
            _Listener.Stop();
            _TokenSource.Cancel();

            _Settings?.Logger.Invoke(_Header + "stopped");
        }
```
